import ctypes

def configure_native(library, buffer_type):
    library.api_abi_version.argtypes = []
    library.api_abi_version.restype = ctypes.c_uint32
    library.buffer_last_error.argtypes = []
    library.buffer_last_error.restype = ctypes.c_char_p
    library.buffer_last_error_details.argtypes = []
    library.buffer_last_error_details.restype = buffer_type
    library.buffer_free.argtypes = [buffer_type]
    library.buffer_free.restype = None
    library.secret_len.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t)]
    library.secret_len.restype = ctypes.c_bool
    library.secret_copy.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.secret_copy.restype = ctypes.c_bool
    library.secret_free.argtypes = [ctypes.c_void_p]
    library.secret_free.restype = None
    library.lockbox_format_version.argtypes = []
    library.lockbox_format_version.restype = ctypes.c_uint16
    library.lockbox_probe_format_version.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_probe_format_version.restype = ctypes.c_uint16
    library.lockbox_create.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_create.restype = ctypes.c_void_p
    library.lockbox_create_with_options.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t]
    library.lockbox_create_with_options.restype = ctypes.c_void_p
    library.lockbox_create_password.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_create_password.restype = ctypes.c_void_p
    library.lockbox_create_contact.argtypes = [ctypes.c_void_p]
    library.lockbox_create_contact.restype = ctypes.c_void_p
    library.lockbox_create_with_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.lockbox_create_with_signing_key.restype = ctypes.c_void_p
    library.lockbox_open.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_open.restype = ctypes.c_void_p
    library.lockbox_open_with_options.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t]
    library.lockbox_open_with_options.restype = ctypes.c_void_p
    library.lockbox_open_password.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_open_password.restype = ctypes.c_void_p
    library.lockbox_open_contact.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.lockbox_open_contact.restype = ctypes.c_void_p
    library.lockbox_add_file.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.lockbox_add_file.restype = ctypes.c_bool
    library.lockbox_add_file_with_permissions.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint32, ctypes.c_bool]
    library.lockbox_add_file_with_permissions.restype = ctypes.c_bool
    library.lockbox_get_file.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_get_file.restype = buffer_type
    library.lockbox_extract_file.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.lockbox_extract_file.restype = ctypes.c_bool
    library.lockbox_extract_directory.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64, ctypes.c_uint64, ctypes.c_size_t, ctypes.c_bool, ctypes.c_bool, ctypes.c_bool]
    library.lockbox_extract_directory.restype = ctypes.c_bool
    library.lockbox_stream_content.argtypes = [ctypes.c_void_p, ctypes.c_bool]
    library.lockbox_stream_content.restype = buffer_type
    library.lockbox_cache_stats.argtypes = [ctypes.c_void_p]
    library.lockbox_cache_stats.restype = buffer_type
    library.lockbox_import_stats.argtypes = [ctypes.c_void_p]
    library.lockbox_import_stats.restype = buffer_type
    library.lockbox_reset_import_stats.argtypes = [ctypes.c_void_p]
    library.lockbox_reset_import_stats.restype = ctypes.c_bool
    library.lockbox_inspect_file.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_inspect_file.restype = buffer_type
    library.lockbox_page_inspection.argtypes = [ctypes.c_void_p]
    library.lockbox_page_inspection.restype = buffer_type
    library.lockbox_recovery_report.argtypes = [ctypes.c_void_p]
    library.lockbox_recovery_report.restype = buffer_type
    library.lockbox_recovery_report_render.argtypes = [ctypes.c_void_p, ctypes.c_bool, ctypes.c_size_t]
    library.lockbox_recovery_report_render.restype = buffer_type
    library.lockbox_recovery_scan_path.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_recovery_scan_path.restype = buffer_type
    library.lockbox_storage_len.argtypes = [ctypes.c_void_p]
    library.lockbox_storage_len.restype = ctypes.c_uint64
    library.lockbox_set_workload_profile.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_set_workload_profile.restype = ctypes.c_bool
    library.lockbox_set_worker_policy.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_size_t]
    library.lockbox_set_worker_policy.restype = ctypes.c_bool
    library.lockbox_runtime_options.argtypes = [ctypes.c_void_p]
    library.lockbox_runtime_options.restype = buffer_type
    library.lockbox_commit.argtypes = [ctypes.c_void_p]
    library.lockbox_commit.restype = ctypes.c_bool
    library.lockbox_create_dir.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.lockbox_create_dir.restype = ctypes.c_bool
    library.lockbox_delete.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_delete.restype = ctypes.c_bool
    library.lockbox_remove_dir.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.lockbox_remove_dir.restype = ctypes.c_bool
    library.lockbox_create_parent_dirs.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_create_parent_dirs.restype = ctypes.c_bool
    library.lockbox_rename.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_rename.restype = ctypes.c_bool
    library.lockbox_list.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.lockbox_list.restype = buffer_type
    library.lockbox_list_with_options.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool, ctypes.c_bool, ctypes.c_bool, ctypes.c_bool, ctypes.c_size_t]
    library.lockbox_list_with_options.restype = buffer_type
    library.lockbox_stat.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_stat.restype = buffer_type
    library.lockbox_set_variable.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_set_variable.restype = ctypes.c_bool
    library.lockbox_set_secret_variable.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_set_secret_variable.restype = ctypes.c_bool
    library.lockbox_get_variable.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_get_variable.restype = buffer_type
    library.lockbox_get_secret_variable.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_void_p)]
    library.lockbox_get_secret_variable.restype = ctypes.c_bool
    library.lockbox_delete_variable.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_delete_variable.restype = ctypes.c_bool
    library.lockbox_move_variables.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_move_variables.restype = ctypes.c_bool
    library.lockbox_list_variables.argtypes = [ctypes.c_void_p]
    library.lockbox_list_variables.restype = buffer_type
    library.lockbox_variable_sensitivity.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_variable_sensitivity.restype = buffer_type
    library.lockbox_add_symlink.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.lockbox_add_symlink.restype = ctypes.c_bool
    library.lockbox_get_symlink_target.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_get_symlink_target.restype = buffer_type
    library.lockbox_id.argtypes = [ctypes.c_void_p]
    library.lockbox_id.restype = buffer_type
    library.lockbox_exists.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_exists.restype = ctypes.c_bool
    library.lockbox_is_dir.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_is_dir.restype = ctypes.c_bool
    library.lockbox_permissions.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_permissions.restype = ctypes.c_uint32
    library.lockbox_set_permissions.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint32]
    library.lockbox_set_permissions.restype = ctypes.c_bool
    library.lockbox_read_range.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64, ctypes.c_uint64]
    library.lockbox_read_range.restype = buffer_type
    library.lockbox_recovery_scan.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_recovery_scan.restype = buffer_type
    library.lockbox_recovery_salvage.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.lockbox_recovery_salvage.restype = ctypes.c_void_p
    library.lockbox_add_password.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_add_password.restype = ctypes.c_uint64
    library.lockbox_add_contact.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_add_contact.restype = ctypes.c_uint64
    library.lockbox_delete_key.argtypes = [ctypes.c_void_p, ctypes.c_uint64]
    library.lockbox_delete_key.restype = ctypes.c_bool
    library.lockbox_list_key_slots.argtypes = [ctypes.c_void_p]
    library.lockbox_list_key_slots.restype = buffer_type
    library.lockbox_set_owner_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
    library.lockbox_set_owner_signing_key.restype = ctypes.c_bool
    library.lockbox_owner_inspection.argtypes = [ctypes.c_void_p]
    library.lockbox_owner_inspection.restype = buffer_type
    library.lockbox_define_form.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_define_form.restype = buffer_type
    library.lockbox_list_form_definitions.argtypes = [ctypes.c_void_p]
    library.lockbox_list_form_definitions.restype = buffer_type
    library.lockbox_resolve_form.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_resolve_form.restype = buffer_type
    library.lockbox_list_form_revisions.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_list_form_revisions.restype = buffer_type
    library.lockbox_create_form_record.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_create_form_record.restype = buffer_type
    library.lockbox_set_form_field.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_set_form_field.restype = ctypes.c_bool
    library.lockbox_set_secret_form_field.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_set_secret_form_field.restype = ctypes.c_bool
    library.lockbox_list_form_records.argtypes = [ctypes.c_void_p]
    library.lockbox_list_form_records.restype = buffer_type
    library.lockbox_get_form_record.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_get_form_record.restype = buffer_type
    library.lockbox_delete_form_record.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_delete_form_record.restype = ctypes.c_bool
    library.lockbox_move_form_records.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_move_form_records.restype = ctypes.c_bool
    library.lockbox_get_form_field.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.lockbox_get_form_field.restype = buffer_type
    library.lockbox_get_secret_form_field.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.POINTER(ctypes.c_void_p)]
    library.lockbox_get_secret_form_field.restype = ctypes.c_bool
    library.lockbox_to_bytes.argtypes = [ctypes.c_void_p]
    library.lockbox_to_bytes.restype = buffer_type
    library.lockbox_free.argtypes = [ctypes.c_void_p]
    library.lockbox_free.restype = None
    library.vault_is_running.argtypes = []
    library.vault_is_running.restype = ctypes.c_bool
    library.vault_forget_all.argtypes = []
    library.vault_forget_all.restype = ctypes.c_bool
    library.key_contact_generate.argtypes = []
    library.key_contact_generate.restype = ctypes.c_void_p
    library.key_contact_from_private.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.key_contact_from_private.restype = ctypes.c_void_p
    library.key_contact_public.argtypes = [ctypes.c_void_p]
    library.key_contact_public.restype = buffer_type
    library.key_contact_private.argtypes = [ctypes.c_void_p]
    library.key_contact_private.restype = buffer_type
    library.key_contact_public_from_bytes.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.key_contact_public_from_bytes.restype = ctypes.c_void_p
    library.key_contact_public_free.argtypes = [ctypes.c_void_p]
    library.key_contact_public_free.restype = None
    library.key_contact_free.argtypes = [ctypes.c_void_p]
    library.key_contact_free.restype = None
    library.key_contact_encrypt.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.key_contact_encrypt.restype = ctypes.c_void_p
    library.key_contact_decrypt.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
    library.key_contact_decrypt.restype = buffer_type
    library.key_contact_wrapped_public.argtypes = [ctypes.c_void_p]
    library.key_contact_wrapped_public.restype = buffer_type
    library.key_contact_wrapped_ciphertext.argtypes = [ctypes.c_void_p]
    library.key_contact_wrapped_ciphertext.restype = buffer_type
    library.key_contact_wrapped_encrypted.argtypes = [ctypes.c_void_p]
    library.key_contact_wrapped_encrypted.restype = buffer_type
    library.key_contact_wrapped_free.argtypes = [ctypes.c_void_p]
    library.key_contact_wrapped_free.restype = None
    library.key_signing_generate.argtypes = []
    library.key_signing_generate.restype = ctypes.c_void_p
    library.key_signing_from_private.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.key_signing_from_private.restype = ctypes.c_void_p
    library.key_signing_public.argtypes = [ctypes.c_void_p]
    library.key_signing_public.restype = buffer_type
    library.key_signing_private.argtypes = [ctypes.c_void_p]
    library.key_signing_private.restype = buffer_type
    library.key_signing_public_from_bytes.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.key_signing_public_from_bytes.restype = ctypes.c_void_p
    library.key_signing_public_free.argtypes = [ctypes.c_void_p]
    library.key_signing_public_free.restype = None
    library.key_signing_free.argtypes = [ctypes.c_void_p]
    library.key_signing_free.restype = None
    library.vault_key_export_private.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_export_private.restype = buffer_type
    library.vault_key_export_public.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_export_public.restype = buffer_type
    library.vault_key_import_private.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_import_private.restype = ctypes.c_void_p
    library.vault_key_import_public.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_import_public.restype = ctypes.c_void_p
    library.vault_key_fingerprint.argtypes = [ctypes.c_void_p]
    library.vault_key_fingerprint.restype = buffer_type
    library.vault_key_format_hex.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_format_hex.restype = buffer_type
    library.vault_key_decode_hex.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_decode_hex.restype = buffer_type
    library.vault_key_format_crockford.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_format_crockford.restype = buffer_type
    library.vault_key_format_crockford_reading.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_format_crockford_reading.restype = buffer_type
    library.vault_key_decode_crockford.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_decode_crockford.restype = buffer_type
    library.vault_key_hex_encode.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_hex_encode.restype = buffer_type
    library.vault_key_hex_decode.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_key_hex_decode.restype = buffer_type
    library.vault_directory_open.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_open.restype = ctypes.c_void_p
    library.vault_structure_version_current.argtypes = []
    library.vault_structure_version_current.restype = ctypes.c_uint32
    library.vault_directory_probe_structure_version.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_probe_structure_version.restype = ctypes.c_uint32
    library.vault_directory_open_or_create_default.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_open_or_create_default.restype = ctypes.c_void_p
    library.vault_directory_replace_default.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_replace_default.restype = ctypes.c_void_p
    library.vault_directory_change_password.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_change_password.restype = ctypes.c_bool
    library.vault_directory_change_default_password.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_change_default_password.restype = ctypes.c_bool
    library.vault_directory_replace.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_replace.restype = ctypes.c_void_p
    library.vault_directory_open_or_create.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_open_or_create.restype = ctypes.c_void_p
    library.vault_directory_root.argtypes = [ctypes.c_void_p]
    library.vault_directory_root.restype = buffer_type
    library.vault_directory_structure_version.argtypes = [ctypes.c_void_p]
    library.vault_directory_structure_version.restype = ctypes.c_uint32
    library.vault_directory_list_private_keys.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_private_keys.restype = buffer_type
    library.vault_directory_list_private_key_names.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_private_key_names.restype = buffer_type
    library.vault_directory_list_contact_names.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_contact_names.restype = buffer_type
    library.vault_directory_list_form_aliases.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_form_aliases.restype = buffer_type
    library.vault_directory_private_key_exists.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_private_key_exists.restype = ctypes.c_bool
    library.vault_directory_delete_private_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_delete_private_key.restype = ctypes.c_bool
    library.vault_directory_store_private_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.vault_directory_store_private_key.restype = ctypes.c_bool
    library.vault_directory_load_private_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_load_private_key.restype = ctypes.c_void_p
    library.vault_directory_load_private_key_generation.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint16]
    library.vault_directory_load_private_key_generation.restype = ctypes.c_void_p
    library.vault_directory_store_contact.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.vault_directory_store_contact.restype = ctypes.c_bool
    library.vault_directory_load_contact.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_load_contact.restype = ctypes.c_void_p
    library.vault_directory_contact_exists.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_contact_exists.restype = ctypes.c_bool
    library.vault_directory_delete_contact.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_delete_contact.restype = ctypes.c_bool
    library.vault_directory_list_contacts.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_contacts.restype = buffer_type
    library.vault_directory_store_profile_email.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_store_profile_email.restype = ctypes.c_bool
    library.vault_directory_profile_email.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_profile_email.restype = buffer_type
    library.vault_directory_store_backup.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_store_backup.restype = ctypes.c_bool
    library.vault_directory_load_backup.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_load_backup.restype = buffer_type
    library.vault_directory_backup_count.argtypes = [ctypes.c_void_p]
    library.vault_directory_backup_count.restype = ctypes.c_uint64
    library.vault_directory_restore_private_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_bool]
    library.vault_directory_restore_private_key.restype = ctypes.c_bool
    library.vault_directory_load_owner_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_load_owner_signing_key.restype = ctypes.c_void_p
    library.vault_directory_load_owner_signing_key_generation.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint16]
    library.vault_directory_load_owner_signing_key_generation.restype = ctypes.c_void_p
    library.vault_directory_store_contact_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.vault_directory_store_contact_signing_key.restype = ctypes.c_bool
    library.vault_directory_load_contact_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_load_contact_signing_key.restype = ctypes.c_void_p
    library.vault_directory_list_profile_generations.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_list_profile_generations.restype = buffer_type
    library.vault_directory_rotate_private_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_rotate_private_key.restype = buffer_type
    library.vault_directory_remember_lockbox.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_remember_lockbox.restype = ctypes.c_bool
    library.vault_directory_list_known_lockboxes.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_known_lockboxes.restype = buffer_type
    library.vault_directory_forget_lockbox.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_forget_lockbox.restype = ctypes.c_bool
    library.vault_directory_remember_access_slot_label.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_remember_access_slot_label.restype = ctypes.c_bool
    library.vault_directory_list_access_slot_labels.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_list_access_slot_labels.restype = buffer_type
    library.vault_directory_find_access_slot_labels.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_find_access_slot_labels.restype = buffer_type
    library.vault_directory_forget_access_slot_label.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64]
    library.vault_directory_forget_access_slot_label.restype = ctypes.c_bool
    library.vault_directory_define_form.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_define_form.restype = buffer_type
    library.vault_directory_resolve_form.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_resolve_form.restype = buffer_type
    library.vault_directory_list_forms.argtypes = [ctypes.c_void_p]
    library.vault_directory_list_forms.restype = buffer_type
    library.vault_directory_list_form_revisions.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_list_form_revisions.restype = buffer_type
    library.vault_directory_seed_forms.argtypes = [ctypes.c_void_p]
    library.vault_directory_seed_forms.restype = ctypes.c_size_t
    library.vault_directory_remember_password.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_remember_password.restype = ctypes.c_bool
    library.vault_directory_remembered_password.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_directory_remembered_password.restype = buffer_type
    library.vault_backup_default.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.vault_backup_default.restype = buffer_type
    library.vault_restore_default.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_bool]
    library.vault_restore_default.restype = buffer_type
    library.vault_directory_free.argtypes = [ctypes.c_void_p]
    library.vault_directory_free.restype = None
    library.vault_read_only_open.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_read_only_open.restype = ctypes.c_void_p
    library.vault_read_only_open_default.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_read_only_open_default.restype = ctypes.c_void_p
    library.vault_read_only_list_profile_names.argtypes = [ctypes.c_void_p]
    library.vault_read_only_list_profile_names.restype = buffer_type
    library.vault_read_only_list_contact_names.argtypes = [ctypes.c_void_p]
    library.vault_read_only_list_contact_names.restype = buffer_type
    library.vault_read_only_list_form_aliases.argtypes = [ctypes.c_void_p]
    library.vault_read_only_list_form_aliases.restype = buffer_type
    library.vault_read_only_list_known_lockboxes.argtypes = [ctypes.c_void_p]
    library.vault_read_only_list_known_lockboxes.restype = buffer_type
    library.vault_read_only_free.argtypes = [ctypes.c_void_p]
    library.vault_read_only_free.restype = None
    library.vault_agent_serve.argtypes = []
    library.vault_agent_serve.restype = ctypes.c_bool
    library.vault_agent_verify_transport.argtypes = []
    library.vault_agent_verify_transport.restype = ctypes.c_bool
    library.vault_agent_get.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_get.restype = buffer_type
    library.vault_agent_put.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_put.restype = ctypes.c_bool
    library.vault_agent_forget.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_forget.restype = ctypes.c_bool
    library.vault_agent_stop.argtypes = []
    library.vault_agent_stop.restype = ctypes.c_bool
    library.vault_agent_start.argtypes = []
    library.vault_agent_start.restype = ctypes.c_bool
    library.vault_agent_list.argtypes = []
    library.vault_agent_list.restype = buffer_type
    library.vault_agent_sleep_support.argtypes = []
    library.vault_agent_sleep_support.restype = buffer_type
    library.vault_platform_status.argtypes = []
    library.vault_platform_status.restype = buffer_type
    library.vault_platform_set_scope.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_platform_set_scope.restype = ctypes.c_bool
    library.vault_platform_forget_password.argtypes = []
    library.vault_platform_forget_password.restype = ctypes.c_bool
    library.vault_platform_put_password.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_platform_put_password.restype = ctypes.c_bool
    library.vault_platform_enable.argtypes = []
    library.vault_platform_enable.restype = ctypes.c_bool
    library.vault_platform_disable.argtypes = []
    library.vault_platform_disable.restype = ctypes.c_bool
    library.vault_platform_disabled.argtypes = []
    library.vault_platform_disabled.restype = ctypes.c_bool
    library.vault_platform_get_password.argtypes = []
    library.vault_platform_get_password.restype = buffer_type
    library.vault_default_directory.argtypes = []
    library.vault_default_directory.restype = buffer_type
    library.vault_default_path.argtypes = []
    library.vault_default_path.restype = buffer_type
    library.vault_agent_log_path.argtypes = []
    library.vault_agent_log_path.restype = buffer_type
    library.vault_agent_log_destination.argtypes = []
    library.vault_agent_log_destination.restype = buffer_type
    library.vault_agent_get_vault_unlock_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_get_vault_unlock_key.restype = buffer_type
    library.vault_agent_put_vault_unlock_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64]
    library.vault_agent_put_vault_unlock_key.restype = ctypes.c_bool
    library.vault_agent_forget_vault_unlock_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_forget_vault_unlock_key.restype = ctypes.c_bool
    library.vault_agent_get_owner_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_get_owner_signing_key.restype = ctypes.c_void_p
    library.vault_agent_put_owner_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_uint64]
    library.vault_agent_put_owner_signing_key.restype = ctypes.c_bool
    library.vault_agent_forget_owner_signing_key.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_forget_owner_signing_key.restype = ctypes.c_bool
    library.vault_agent_begin_activity.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    library.vault_agent_begin_activity.restype = ctypes.c_void_p
    library.vault_agent_end_activity.argtypes = [ctypes.c_void_p]
    library.vault_agent_end_activity.restype = None
    library.vault_local.argtypes = []
    library.vault_local.restype = ctypes.c_void_p
    library.vault_create_lockbox_password.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_create_lockbox_password.restype = ctypes.c_void_p
    library.vault_open_lockbox_password.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_open_lockbox_password.restype = ctypes.c_void_p
    library.vault_create_lockbox_content_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.vault_create_lockbox_content_key.restype = ctypes.c_void_p
    library.vault_create_lockbox_contact.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.vault_create_lockbox_contact.restype = ctypes.c_void_p
    library.vault_open_lockbox_content_key.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
    library.vault_open_lockbox_content_key.restype = ctypes.c_void_p
    library.vault_cache_lockbox_password.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p, ctypes.c_size_t, ctypes.c_uint64]
    library.vault_cache_lockbox_password.restype = ctypes.c_bool
    library.vault_close_lockbox.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
    library.vault_close_lockbox.restype = ctypes.c_bool
    library.vault_close_all.argtypes = [ctypes.c_void_p]
    library.vault_close_all.restype = ctypes.c_bool
    library.vault_free.argtypes = [ctypes.c_void_p]
    library.vault_free.restype = None
