package com.onepub.revault;

import java.lang.foreign.*;
import java.lang.invoke.MethodHandle;

/** Generated complete FFM surface for revault_api.h. */
final class RevaultNativeApi {
  private static final MemoryLayout BUFFER = MemoryLayout.structLayout(ValueLayout.ADDRESS, ValueLayout.JAVA_LONG);
  private final Linker linker;
  private final SymbolLookup symbols;
  public final MethodHandle api_abi_version;
  public final MethodHandle buffer_last_error;
  public final MethodHandle buffer_last_error_details;
  public final MethodHandle buffer_free;
  public final MethodHandle secret_len;
  public final MethodHandle secret_copy;
  public final MethodHandle secret_free;
  public final MethodHandle lockbox_format_version;
  public final MethodHandle lockbox_probe_format_version;
  public final MethodHandle lockbox_create;
  public final MethodHandle lockbox_create_with_options;
  public final MethodHandle lockbox_create_password;
  public final MethodHandle lockbox_create_contact;
  public final MethodHandle lockbox_create_with_signing_key;
  public final MethodHandle lockbox_open;
  public final MethodHandle lockbox_open_with_options;
  public final MethodHandle lockbox_open_password;
  public final MethodHandle lockbox_open_contact;
  public final MethodHandle lockbox_add_file;
  public final MethodHandle lockbox_add_file_with_permissions;
  public final MethodHandle lockbox_get_file;
  public final MethodHandle lockbox_extract_file;
  public final MethodHandle lockbox_extract_directory;
  public final MethodHandle lockbox_stream_content;
  public final MethodHandle lockbox_cache_stats;
  public final MethodHandle lockbox_import_stats;
  public final MethodHandle lockbox_reset_import_stats;
  public final MethodHandle lockbox_inspect_file;
  public final MethodHandle lockbox_page_inspection;
  public final MethodHandle lockbox_recovery_report;
  public final MethodHandle lockbox_recovery_report_render;
  public final MethodHandle lockbox_recovery_scan_path;
  public final MethodHandle lockbox_storage_len;
  public final MethodHandle lockbox_set_workload_profile;
  public final MethodHandle lockbox_set_worker_policy;
  public final MethodHandle lockbox_runtime_options;
  public final MethodHandle lockbox_commit;
  public final MethodHandle lockbox_create_dir;
  public final MethodHandle lockbox_delete;
  public final MethodHandle lockbox_remove_dir;
  public final MethodHandle lockbox_create_parent_dirs;
  public final MethodHandle lockbox_rename;
  public final MethodHandle lockbox_list;
  public final MethodHandle lockbox_list_with_options;
  public final MethodHandle lockbox_stat;
  public final MethodHandle lockbox_set_variable;
  public final MethodHandle lockbox_set_secret_variable;
  public final MethodHandle lockbox_get_variable;
  public final MethodHandle lockbox_get_secret_variable;
  public final MethodHandle lockbox_delete_variable;
  public final MethodHandle lockbox_move_variables;
  public final MethodHandle lockbox_list_variables;
  public final MethodHandle lockbox_variable_sensitivity;
  public final MethodHandle lockbox_add_symlink;
  public final MethodHandle lockbox_get_symlink_target;
  public final MethodHandle lockbox_id;
  public final MethodHandle lockbox_exists;
  public final MethodHandle lockbox_is_dir;
  public final MethodHandle lockbox_permissions;
  public final MethodHandle lockbox_set_permissions;
  public final MethodHandle lockbox_read_range;
  public final MethodHandle lockbox_recovery_scan;
  public final MethodHandle lockbox_recovery_salvage;
  public final MethodHandle lockbox_add_password;
  public final MethodHandle lockbox_add_contact;
  public final MethodHandle lockbox_delete_key;
  public final MethodHandle lockbox_list_key_slots;
  public final MethodHandle lockbox_set_owner_signing_key;
  public final MethodHandle lockbox_owner_inspection;
  public final MethodHandle lockbox_define_form;
  public final MethodHandle lockbox_list_form_definitions;
  public final MethodHandle lockbox_resolve_form;
  public final MethodHandle lockbox_list_form_revisions;
  public final MethodHandle lockbox_create_form_record;
  public final MethodHandle lockbox_set_form_field;
  public final MethodHandle lockbox_set_secret_form_field;
  public final MethodHandle lockbox_list_form_records;
  public final MethodHandle lockbox_get_form_record;
  public final MethodHandle lockbox_delete_form_record;
  public final MethodHandle lockbox_move_form_records;
  public final MethodHandle lockbox_get_form_field;
  public final MethodHandle lockbox_get_secret_form_field;
  public final MethodHandle lockbox_to_bytes;
  public final MethodHandle lockbox_free;
  public final MethodHandle vault_is_running;
  public final MethodHandle vault_forget_all;
  public final MethodHandle key_contact_generate;
  public final MethodHandle key_contact_from_private;
  public final MethodHandle key_contact_public;
  public final MethodHandle key_contact_private;
  public final MethodHandle key_contact_public_from_bytes;
  public final MethodHandle key_contact_public_free;
  public final MethodHandle key_contact_free;
  public final MethodHandle key_contact_encrypt;
  public final MethodHandle key_contact_decrypt;
  public final MethodHandle key_contact_wrapped_public;
  public final MethodHandle key_contact_wrapped_ciphertext;
  public final MethodHandle key_contact_wrapped_encrypted;
  public final MethodHandle key_contact_wrapped_free;
  public final MethodHandle key_signing_generate;
  public final MethodHandle key_signing_from_private;
  public final MethodHandle key_signing_public;
  public final MethodHandle key_signing_private;
  public final MethodHandle key_signing_public_from_bytes;
  public final MethodHandle key_signing_public_free;
  public final MethodHandle key_signing_free;
  public final MethodHandle vault_key_export_private;
  public final MethodHandle vault_key_export_public;
  public final MethodHandle vault_key_import_private;
  public final MethodHandle vault_key_import_public;
  public final MethodHandle vault_key_fingerprint;
  public final MethodHandle vault_key_format_hex;
  public final MethodHandle vault_key_decode_hex;
  public final MethodHandle vault_key_format_crockford;
  public final MethodHandle vault_key_format_crockford_reading;
  public final MethodHandle vault_key_decode_crockford;
  public final MethodHandle vault_key_hex_encode;
  public final MethodHandle vault_key_hex_decode;
  public final MethodHandle vault_directory_open;
  public final MethodHandle vault_structure_version_current;
  public final MethodHandle vault_directory_probe_structure_version;
  public final MethodHandle vault_directory_open_or_create_default;
  public final MethodHandle vault_directory_replace_default;
  public final MethodHandle vault_directory_change_password;
  public final MethodHandle vault_directory_change_default_password;
  public final MethodHandle vault_directory_replace;
  public final MethodHandle vault_directory_open_or_create;
  public final MethodHandle vault_directory_root;
  public final MethodHandle vault_directory_structure_version;
  public final MethodHandle vault_directory_list_private_keys;
  public final MethodHandle vault_directory_list_private_key_names;
  public final MethodHandle vault_directory_list_contact_names;
  public final MethodHandle vault_directory_list_form_aliases;
  public final MethodHandle vault_directory_private_key_exists;
  public final MethodHandle vault_directory_delete_private_key;
  public final MethodHandle vault_directory_store_private_key;
  public final MethodHandle vault_directory_load_private_key;
  public final MethodHandle vault_directory_load_private_key_generation;
  public final MethodHandle vault_directory_store_contact;
  public final MethodHandle vault_directory_load_contact;
  public final MethodHandle vault_directory_contact_exists;
  public final MethodHandle vault_directory_delete_contact;
  public final MethodHandle vault_directory_list_contacts;
  public final MethodHandle vault_directory_store_profile_email;
  public final MethodHandle vault_directory_profile_email;
  public final MethodHandle vault_directory_store_backup;
  public final MethodHandle vault_directory_load_backup;
  public final MethodHandle vault_directory_backup_count;
  public final MethodHandle vault_directory_restore_private_key;
  public final MethodHandle vault_directory_load_owner_signing_key;
  public final MethodHandle vault_directory_load_owner_signing_key_generation;
  public final MethodHandle vault_directory_store_contact_signing_key;
  public final MethodHandle vault_directory_load_contact_signing_key;
  public final MethodHandle vault_directory_list_profile_generations;
  public final MethodHandle vault_directory_rotate_private_key;
  public final MethodHandle vault_directory_remember_lockbox;
  public final MethodHandle vault_directory_list_known_lockboxes;
  public final MethodHandle vault_directory_forget_lockbox;
  public final MethodHandle vault_directory_remember_access_slot_label;
  public final MethodHandle vault_directory_list_access_slot_labels;
  public final MethodHandle vault_directory_find_access_slot_labels;
  public final MethodHandle vault_directory_forget_access_slot_label;
  public final MethodHandle vault_directory_define_form;
  public final MethodHandle vault_directory_resolve_form;
  public final MethodHandle vault_directory_list_forms;
  public final MethodHandle vault_directory_list_form_revisions;
  public final MethodHandle vault_directory_seed_forms;
  public final MethodHandle vault_directory_remember_password;
  public final MethodHandle vault_directory_remembered_password;
  public final MethodHandle vault_backup_default;
  public final MethodHandle vault_restore_default;
  public final MethodHandle vault_directory_free;
  public final MethodHandle vault_read_only_open;
  public final MethodHandle vault_read_only_open_default;
  public final MethodHandle vault_read_only_list_profile_names;
  public final MethodHandle vault_read_only_list_contact_names;
  public final MethodHandle vault_read_only_list_form_aliases;
  public final MethodHandle vault_read_only_list_known_lockboxes;
  public final MethodHandle vault_read_only_free;
  public final MethodHandle vault_agent_serve;
  public final MethodHandle vault_agent_verify_transport;
  public final MethodHandle vault_agent_get;
  public final MethodHandle vault_agent_put;
  public final MethodHandle vault_agent_forget;
  public final MethodHandle vault_agent_stop;
  public final MethodHandle vault_agent_start;
  public final MethodHandle vault_agent_list;
  public final MethodHandle vault_agent_sleep_support;
  public final MethodHandle vault_platform_status;
  public final MethodHandle vault_platform_set_scope;
  public final MethodHandle vault_platform_forget_password;
  public final MethodHandle vault_platform_put_password;
  public final MethodHandle vault_platform_enable;
  public final MethodHandle vault_platform_disable;
  public final MethodHandle vault_platform_disabled;
  public final MethodHandle vault_platform_get_password;
  public final MethodHandle vault_default_directory;
  public final MethodHandle vault_default_path;
  public final MethodHandle vault_agent_log_path;
  public final MethodHandle vault_agent_log_destination;
  public final MethodHandle vault_agent_get_vault_unlock_key;
  public final MethodHandle vault_agent_put_vault_unlock_key;
  public final MethodHandle vault_agent_forget_vault_unlock_key;
  public final MethodHandle vault_agent_get_owner_signing_key;
  public final MethodHandle vault_agent_put_owner_signing_key;
  public final MethodHandle vault_agent_forget_owner_signing_key;
  public final MethodHandle vault_agent_begin_activity;
  public final MethodHandle vault_agent_end_activity;
  public final MethodHandle vault_local;
  public final MethodHandle vault_create_lockbox_password;
  public final MethodHandle vault_open_lockbox_password;
  public final MethodHandle vault_create_lockbox_content_key;
  public final MethodHandle vault_create_lockbox_contact;
  public final MethodHandle vault_open_lockbox_content_key;
  public final MethodHandle vault_cache_lockbox_password;
  public final MethodHandle vault_close_lockbox;
  public final MethodHandle vault_close_all;
  public final MethodHandle vault_free;

  public RevaultNativeApi(SymbolLookup symbols) {
    this.linker = Linker.nativeLinker();
    this.symbols = symbols;
    api_abi_version = linker.downcallHandle(symbols.find("api_abi_version").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    buffer_last_error = linker.downcallHandle(symbols.find("buffer_last_error").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS));
    buffer_last_error_details = linker.downcallHandle(symbols.find("buffer_last_error_details").orElseThrow(), FunctionDescriptor.of(BUFFER));
    buffer_free = linker.downcallHandle(symbols.find("buffer_free").orElseThrow(), FunctionDescriptor.ofVoid(BUFFER));
    secret_len = linker.downcallHandle(symbols.find("secret_len").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    secret_copy = linker.downcallHandle(symbols.find("secret_copy").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    secret_free = linker.downcallHandle(symbols.find("secret_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    lockbox_format_version = linker.downcallHandle(symbols.find("lockbox_format_version").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_SHORT));
    lockbox_probe_format_version = linker.downcallHandle(symbols.find("lockbox_probe_format_version").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_SHORT, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_create = linker.downcallHandle(symbols.find("lockbox_create").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_create_with_options = linker.downcallHandle(symbols.find("lockbox_create_with_options").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    lockbox_create_password = linker.downcallHandle(symbols.find("lockbox_create_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_create_contact = linker.downcallHandle(symbols.find("lockbox_create_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    lockbox_create_with_signing_key = linker.downcallHandle(symbols.find("lockbox_create_with_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    lockbox_open = linker.downcallHandle(symbols.find("lockbox_open").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_open_with_options = linker.downcallHandle(symbols.find("lockbox_open_with_options").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    lockbox_open_password = linker.downcallHandle(symbols.find("lockbox_open_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_open_contact = linker.downcallHandle(symbols.find("lockbox_open_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    lockbox_add_file = linker.downcallHandle(symbols.find("lockbox_add_file").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    lockbox_add_file_with_permissions = linker.downcallHandle(symbols.find("lockbox_add_file_with_permissions").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_BOOLEAN));
    lockbox_get_file = linker.downcallHandle(symbols.find("lockbox_get_file").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_extract_file = linker.downcallHandle(symbols.find("lockbox_extract_file").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    lockbox_extract_directory = linker.downcallHandle(symbols.find("lockbox_extract_directory").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_BOOLEAN));
    lockbox_stream_content = linker.downcallHandle(symbols.find("lockbox_stream_content").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_BOOLEAN));
    lockbox_cache_stats = linker.downcallHandle(symbols.find("lockbox_cache_stats").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_import_stats = linker.downcallHandle(symbols.find("lockbox_import_stats").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_reset_import_stats = linker.downcallHandle(symbols.find("lockbox_reset_import_stats").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS));
    lockbox_inspect_file = linker.downcallHandle(symbols.find("lockbox_inspect_file").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_page_inspection = linker.downcallHandle(symbols.find("lockbox_page_inspection").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_recovery_report = linker.downcallHandle(symbols.find("lockbox_recovery_report").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_recovery_report_render = linker.downcallHandle(symbols.find("lockbox_recovery_report_render").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));
    lockbox_recovery_scan_path = linker.downcallHandle(symbols.find("lockbox_recovery_scan_path").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_storage_len = linker.downcallHandle(symbols.find("lockbox_storage_len").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    lockbox_set_workload_profile = linker.downcallHandle(symbols.find("lockbox_set_workload_profile").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_set_worker_policy = linker.downcallHandle(symbols.find("lockbox_set_worker_policy").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    lockbox_runtime_options = linker.downcallHandle(symbols.find("lockbox_runtime_options").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_commit = linker.downcallHandle(symbols.find("lockbox_commit").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS));
    lockbox_create_dir = linker.downcallHandle(symbols.find("lockbox_create_dir").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    lockbox_delete = linker.downcallHandle(symbols.find("lockbox_delete").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_remove_dir = linker.downcallHandle(symbols.find("lockbox_remove_dir").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    lockbox_create_parent_dirs = linker.downcallHandle(symbols.find("lockbox_create_parent_dirs").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_rename = linker.downcallHandle(symbols.find("lockbox_rename").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_list = linker.downcallHandle(symbols.find("lockbox_list").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    lockbox_list_with_options = linker.downcallHandle(symbols.find("lockbox_list_with_options").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_BOOLEAN, ValueLayout.JAVA_LONG));
    lockbox_stat = linker.downcallHandle(symbols.find("lockbox_stat").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_set_variable = linker.downcallHandle(symbols.find("lockbox_set_variable").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_set_secret_variable = linker.downcallHandle(symbols.find("lockbox_set_secret_variable").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_get_variable = linker.downcallHandle(symbols.find("lockbox_get_variable").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_get_secret_variable = linker.downcallHandle(symbols.find("lockbox_get_secret_variable").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    lockbox_delete_variable = linker.downcallHandle(symbols.find("lockbox_delete_variable").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_move_variables = linker.downcallHandle(symbols.find("lockbox_move_variables").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_list_variables = linker.downcallHandle(symbols.find("lockbox_list_variables").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_variable_sensitivity = linker.downcallHandle(symbols.find("lockbox_variable_sensitivity").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_add_symlink = linker.downcallHandle(symbols.find("lockbox_add_symlink").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    lockbox_get_symlink_target = linker.downcallHandle(symbols.find("lockbox_get_symlink_target").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_id = linker.downcallHandle(symbols.find("lockbox_id").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_exists = linker.downcallHandle(symbols.find("lockbox_exists").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_is_dir = linker.downcallHandle(symbols.find("lockbox_is_dir").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_permissions = linker.downcallHandle(symbols.find("lockbox_permissions").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_set_permissions = linker.downcallHandle(symbols.find("lockbox_set_permissions").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    lockbox_read_range = linker.downcallHandle(symbols.find("lockbox_read_range").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    lockbox_recovery_scan = linker.downcallHandle(symbols.find("lockbox_recovery_scan").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_recovery_salvage = linker.downcallHandle(symbols.find("lockbox_recovery_salvage").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    lockbox_add_password = linker.downcallHandle(symbols.find("lockbox_add_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_add_contact = linker.downcallHandle(symbols.find("lockbox_add_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_delete_key = linker.downcallHandle(symbols.find("lockbox_delete_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_list_key_slots = linker.downcallHandle(symbols.find("lockbox_list_key_slots").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_set_owner_signing_key = linker.downcallHandle(symbols.find("lockbox_set_owner_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    lockbox_owner_inspection = linker.downcallHandle(symbols.find("lockbox_owner_inspection").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_define_form = linker.downcallHandle(symbols.find("lockbox_define_form").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_list_form_definitions = linker.downcallHandle(symbols.find("lockbox_list_form_definitions").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_resolve_form = linker.downcallHandle(symbols.find("lockbox_resolve_form").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_list_form_revisions = linker.downcallHandle(symbols.find("lockbox_list_form_revisions").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_create_form_record = linker.downcallHandle(symbols.find("lockbox_create_form_record").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_set_form_field = linker.downcallHandle(symbols.find("lockbox_set_form_field").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_set_secret_form_field = linker.downcallHandle(symbols.find("lockbox_set_secret_form_field").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_list_form_records = linker.downcallHandle(symbols.find("lockbox_list_form_records").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_get_form_record = linker.downcallHandle(symbols.find("lockbox_get_form_record").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_delete_form_record = linker.downcallHandle(symbols.find("lockbox_delete_form_record").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_move_form_records = linker.downcallHandle(symbols.find("lockbox_move_form_records").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_get_form_field = linker.downcallHandle(symbols.find("lockbox_get_form_field").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    lockbox_get_secret_form_field = linker.downcallHandle(symbols.find("lockbox_get_secret_form_field").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    lockbox_to_bytes = linker.downcallHandle(symbols.find("lockbox_to_bytes").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    lockbox_free = linker.downcallHandle(symbols.find("lockbox_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    vault_is_running = linker.downcallHandle(symbols.find("vault_is_running").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_forget_all = linker.downcallHandle(symbols.find("vault_forget_all").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    key_contact_generate = linker.downcallHandle(symbols.find("key_contact_generate").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS));
    key_contact_from_private = linker.downcallHandle(symbols.find("key_contact_from_private").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    key_contact_public = linker.downcallHandle(symbols.find("key_contact_public").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_contact_private = linker.downcallHandle(symbols.find("key_contact_private").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_contact_public_from_bytes = linker.downcallHandle(symbols.find("key_contact_public_from_bytes").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    key_contact_public_free = linker.downcallHandle(symbols.find("key_contact_public_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    key_contact_free = linker.downcallHandle(symbols.find("key_contact_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    key_contact_encrypt = linker.downcallHandle(symbols.find("key_contact_encrypt").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    key_contact_decrypt = linker.downcallHandle(symbols.find("key_contact_decrypt").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    key_contact_wrapped_public = linker.downcallHandle(symbols.find("key_contact_wrapped_public").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_contact_wrapped_ciphertext = linker.downcallHandle(symbols.find("key_contact_wrapped_ciphertext").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_contact_wrapped_encrypted = linker.downcallHandle(symbols.find("key_contact_wrapped_encrypted").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_contact_wrapped_free = linker.downcallHandle(symbols.find("key_contact_wrapped_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    key_signing_generate = linker.downcallHandle(symbols.find("key_signing_generate").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS));
    key_signing_from_private = linker.downcallHandle(symbols.find("key_signing_from_private").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    key_signing_public = linker.downcallHandle(symbols.find("key_signing_public").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_signing_private = linker.downcallHandle(symbols.find("key_signing_private").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    key_signing_public_from_bytes = linker.downcallHandle(symbols.find("key_signing_public_from_bytes").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    key_signing_public_free = linker.downcallHandle(symbols.find("key_signing_public_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    key_signing_free = linker.downcallHandle(symbols.find("key_signing_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    vault_key_export_private = linker.downcallHandle(symbols.find("vault_key_export_private").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_export_public = linker.downcallHandle(symbols.find("vault_key_export_public").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_import_private = linker.downcallHandle(symbols.find("vault_key_import_private").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_import_public = linker.downcallHandle(symbols.find("vault_key_import_public").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_fingerprint = linker.downcallHandle(symbols.find("vault_key_fingerprint").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_key_format_hex = linker.downcallHandle(symbols.find("vault_key_format_hex").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_decode_hex = linker.downcallHandle(symbols.find("vault_key_decode_hex").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_format_crockford = linker.downcallHandle(symbols.find("vault_key_format_crockford").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_format_crockford_reading = linker.downcallHandle(symbols.find("vault_key_format_crockford_reading").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_decode_crockford = linker.downcallHandle(symbols.find("vault_key_decode_crockford").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_hex_encode = linker.downcallHandle(symbols.find("vault_key_hex_encode").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_key_hex_decode = linker.downcallHandle(symbols.find("vault_key_hex_decode").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_open = linker.downcallHandle(symbols.find("vault_directory_open").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_structure_version_current = linker.downcallHandle(symbols.find("vault_structure_version_current").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT));
    vault_directory_probe_structure_version = linker.downcallHandle(symbols.find("vault_directory_probe_structure_version").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_open_or_create_default = linker.downcallHandle(symbols.find("vault_directory_open_or_create_default").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_replace_default = linker.downcallHandle(symbols.find("vault_directory_replace_default").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_change_password = linker.downcallHandle(symbols.find("vault_directory_change_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_change_default_password = linker.downcallHandle(symbols.find("vault_directory_change_default_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_replace = linker.downcallHandle(symbols.find("vault_directory_replace").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_open_or_create = linker.downcallHandle(symbols.find("vault_directory_open_or_create").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_root = linker.downcallHandle(symbols.find("vault_directory_root").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_structure_version = linker.downcallHandle(symbols.find("vault_directory_structure_version").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    vault_directory_list_private_keys = linker.downcallHandle(symbols.find("vault_directory_list_private_keys").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_list_private_key_names = linker.downcallHandle(symbols.find("vault_directory_list_private_key_names").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_list_contact_names = linker.downcallHandle(symbols.find("vault_directory_list_contact_names").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_list_form_aliases = linker.downcallHandle(symbols.find("vault_directory_list_form_aliases").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_private_key_exists = linker.downcallHandle(symbols.find("vault_directory_private_key_exists").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_delete_private_key = linker.downcallHandle(symbols.find("vault_directory_delete_private_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_store_private_key = linker.downcallHandle(symbols.find("vault_directory_store_private_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_directory_load_private_key = linker.downcallHandle(symbols.find("vault_directory_load_private_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_load_private_key_generation = linker.downcallHandle(symbols.find("vault_directory_load_private_key_generation").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_SHORT));
    vault_directory_store_contact = linker.downcallHandle(symbols.find("vault_directory_store_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_directory_load_contact = linker.downcallHandle(symbols.find("vault_directory_load_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_contact_exists = linker.downcallHandle(symbols.find("vault_directory_contact_exists").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_delete_contact = linker.downcallHandle(symbols.find("vault_directory_delete_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_list_contacts = linker.downcallHandle(symbols.find("vault_directory_list_contacts").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_store_profile_email = linker.downcallHandle(symbols.find("vault_directory_store_profile_email").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_profile_email = linker.downcallHandle(symbols.find("vault_directory_profile_email").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_store_backup = linker.downcallHandle(symbols.find("vault_directory_store_backup").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_load_backup = linker.downcallHandle(symbols.find("vault_directory_load_backup").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_backup_count = linker.downcallHandle(symbols.find("vault_directory_backup_count").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_directory_restore_private_key = linker.downcallHandle(symbols.find("vault_directory_restore_private_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_BOOLEAN));
    vault_directory_load_owner_signing_key = linker.downcallHandle(symbols.find("vault_directory_load_owner_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_load_owner_signing_key_generation = linker.downcallHandle(symbols.find("vault_directory_load_owner_signing_key_generation").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_SHORT));
    vault_directory_store_contact_signing_key = linker.downcallHandle(symbols.find("vault_directory_store_contact_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_directory_load_contact_signing_key = linker.downcallHandle(symbols.find("vault_directory_load_contact_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_list_profile_generations = linker.downcallHandle(symbols.find("vault_directory_list_profile_generations").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_rotate_private_key = linker.downcallHandle(symbols.find("vault_directory_rotate_private_key").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_remember_lockbox = linker.downcallHandle(symbols.find("vault_directory_remember_lockbox").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_list_known_lockboxes = linker.downcallHandle(symbols.find("vault_directory_list_known_lockboxes").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_forget_lockbox = linker.downcallHandle(symbols.find("vault_directory_forget_lockbox").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_remember_access_slot_label = linker.downcallHandle(symbols.find("vault_directory_remember_access_slot_label").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_list_access_slot_labels = linker.downcallHandle(symbols.find("vault_directory_list_access_slot_labels").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_find_access_slot_labels = linker.downcallHandle(symbols.find("vault_directory_find_access_slot_labels").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_forget_access_slot_label = linker.downcallHandle(symbols.find("vault_directory_forget_access_slot_label").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    vault_directory_define_form = linker.downcallHandle(symbols.find("vault_directory_define_form").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_resolve_form = linker.downcallHandle(symbols.find("vault_directory_resolve_form").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_list_forms = linker.downcallHandle(symbols.find("vault_directory_list_forms").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_directory_list_form_revisions = linker.downcallHandle(symbols.find("vault_directory_list_form_revisions").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_seed_forms = linker.downcallHandle(symbols.find("vault_directory_seed_forms").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_directory_remember_password = linker.downcallHandle(symbols.find("vault_directory_remember_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_directory_remembered_password = linker.downcallHandle(symbols.find("vault_directory_remembered_password").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_backup_default = linker.downcallHandle(symbols.find("vault_backup_default").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    vault_restore_default = linker.downcallHandle(symbols.find("vault_restore_default").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_BOOLEAN));
    vault_directory_free = linker.downcallHandle(symbols.find("vault_directory_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    vault_read_only_open = linker.downcallHandle(symbols.find("vault_read_only_open").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_read_only_open_default = linker.downcallHandle(symbols.find("vault_read_only_open_default").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_read_only_list_profile_names = linker.downcallHandle(symbols.find("vault_read_only_list_profile_names").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_read_only_list_contact_names = linker.downcallHandle(symbols.find("vault_read_only_list_contact_names").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_read_only_list_form_aliases = linker.downcallHandle(symbols.find("vault_read_only_list_form_aliases").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_read_only_list_known_lockboxes = linker.downcallHandle(symbols.find("vault_read_only_list_known_lockboxes").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS));
    vault_read_only_free = linker.downcallHandle(symbols.find("vault_read_only_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    vault_agent_serve = linker.downcallHandle(symbols.find("vault_agent_serve").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_agent_verify_transport = linker.downcallHandle(symbols.find("vault_agent_verify_transport").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_agent_get = linker.downcallHandle(symbols.find("vault_agent_get").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_put = linker.downcallHandle(symbols.find("vault_agent_put").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_forget = linker.downcallHandle(symbols.find("vault_agent_forget").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_stop = linker.downcallHandle(symbols.find("vault_agent_stop").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_agent_start = linker.downcallHandle(symbols.find("vault_agent_start").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_agent_list = linker.downcallHandle(symbols.find("vault_agent_list").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_agent_sleep_support = linker.downcallHandle(symbols.find("vault_agent_sleep_support").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_platform_status = linker.downcallHandle(symbols.find("vault_platform_status").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_platform_set_scope = linker.downcallHandle(symbols.find("vault_platform_set_scope").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_platform_forget_password = linker.downcallHandle(symbols.find("vault_platform_forget_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_platform_put_password = linker.downcallHandle(symbols.find("vault_platform_put_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_platform_enable = linker.downcallHandle(symbols.find("vault_platform_enable").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_platform_disable = linker.downcallHandle(symbols.find("vault_platform_disable").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_platform_disabled = linker.downcallHandle(symbols.find("vault_platform_disabled").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN));
    vault_platform_get_password = linker.downcallHandle(symbols.find("vault_platform_get_password").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_default_directory = linker.downcallHandle(symbols.find("vault_default_directory").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_default_path = linker.downcallHandle(symbols.find("vault_default_path").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_agent_log_path = linker.downcallHandle(symbols.find("vault_agent_log_path").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_agent_log_destination = linker.downcallHandle(symbols.find("vault_agent_log_destination").orElseThrow(), FunctionDescriptor.of(BUFFER));
    vault_agent_get_vault_unlock_key = linker.downcallHandle(symbols.find("vault_agent_get_vault_unlock_key").orElseThrow(), FunctionDescriptor.of(BUFFER, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_put_vault_unlock_key = linker.downcallHandle(symbols.find("vault_agent_put_vault_unlock_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    vault_agent_forget_vault_unlock_key = linker.downcallHandle(symbols.find("vault_agent_forget_vault_unlock_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_get_owner_signing_key = linker.downcallHandle(symbols.find("vault_agent_get_owner_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_put_owner_signing_key = linker.downcallHandle(symbols.find("vault_agent_put_owner_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_forget_owner_signing_key = linker.downcallHandle(symbols.find("vault_agent_forget_owner_signing_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_begin_activity = linker.downcallHandle(symbols.find("vault_agent_begin_activity").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_agent_end_activity = linker.downcallHandle(symbols.find("vault_agent_end_activity").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    vault_local = linker.downcallHandle(symbols.find("vault_local").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS));
    vault_create_lockbox_password = linker.downcallHandle(symbols.find("vault_create_lockbox_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_open_lockbox_password = linker.downcallHandle(symbols.find("vault_open_lockbox_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_create_lockbox_content_key = linker.downcallHandle(symbols.find("vault_create_lockbox_content_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_create_lockbox_contact = linker.downcallHandle(symbols.find("vault_create_lockbox_contact").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_open_lockbox_content_key = linker.downcallHandle(symbols.find("vault_open_lockbox_content_key").orElseThrow(), FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    vault_cache_lockbox_password = linker.downcallHandle(symbols.find("vault_cache_lockbox_password").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG, ValueLayout.JAVA_LONG));
    vault_close_lockbox = linker.downcallHandle(symbols.find("vault_close_lockbox").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_LONG));
    vault_close_all = linker.downcallHandle(symbols.find("vault_close_all").orElseThrow(), FunctionDescriptor.of(ValueLayout.JAVA_BOOLEAN, ValueLayout.ADDRESS));
    vault_free = linker.downcallHandle(symbols.find("vault_free").orElseThrow(), FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
  }
}
