[package]
name = "revault_wasm_bindings"
version = "0.0.3"
edition = "2021"
rust-version = "1.88"
license-file = "../revault_lockbox_api/LICENSE"
description = "WebAssembly bindings for the reVault APIs"
repository = "https://github.com/onepub-dev/reVault"
documentation = "https://docs.rs/revault_wasm_bindings"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
revault_lockbox_api = { version = "0.0.9", path = "../revault_lockbox_api", features = ["bindings"] }
revault_page_api = { version = "0.0.4", path = "../revault_page_api" }
revault_vault_api = { version = "0.0.10", path = "../revault_vault_api" }
wasm-bindgen = "0.2"
js-sys = "0.3"
