use super::context::{cli_error, default_vault, CliResult};
use clap::{Arg, ArgAction, ArgMatches, Command};
use revault_publish_protocol::exchange::{
    random_token, verification, Acceptance, Bundle, ExchangeClient, LocalExchange, Offer, Request,
};
use revault_vault_api::VaultDirectory;
use std::io::{self, IsTerminal, Write};
use std::time::{SystemTime, UNIX_EPOCH};

pub(super) fn commands() -> Vec<Command> {
    let profile = || {
        Arg::new("profile")
            .long("profile")
            .required(true)
            .help("The one local profile whose encryption and signing keys will be shared.")
    };
    let id = || {
        Arg::new("id")
            .required(true)
            .help("Exchange ID shown by exchanges.")
    };
    vec![
        Command::new("exchange").about("Invite someone to a reciprocal public-key exchange.")
            .arg(Arg::new("email").required(true))
            .arg(profile())
            .arg(Arg::new("key-server").long("key-server").required(true).help("HTTPS invitation relay origin."))
            .arg(Arg::new("ttl-hours").long("ttl-hours").default_value("24")
                .value_parser(clap::value_parser!(u64).range(1..=168))),
        Command::new("accept").about("Accept an invitation and return your selected profile's keys.")
            .arg(Arg::new("invitation").required(true).help("Invitation URL generated by exchange."))
            .arg(profile()),
        Command::new("exchanges").about("Fetch replies and show local exchange/verification status.")
            .arg(Arg::new("offline").long("offline").action(ArgAction::SetTrue)),
        Command::new("verify").about("Compare one full shared fingerprint and save both contact keys.")
            .arg(id()).arg(Arg::new("name").required(true))
            .arg(Arg::new("fingerprint").long("fingerprint")
                .help("Full shared fingerprint obtained through an independently trusted channel."))
            .arg(Arg::new("channel").long("channel")
                .value_parser(["in-person", "known-phone-call", "trusted-messenger"])
                .help("Independent channel used to compare both identities and the full fingerprint.")),
        Command::new("cancel-exchange").about("Cancel an invitation you created before acceptance.").arg(id()),
        Command::new("verify-author").about("Authenticate a lockbox against a saved contact signing key.")
            .arg(Arg::new("name").required(true)).arg(Arg::new("lockbox").required(true)),
        Command::new("forget-exchange").about("Remove local exchange state; retain any verified contact.").arg(id()),
    ]
}

fn value<'a>(args: &'a ArgMatches, name: &str) -> &'a str {
    args.get_one::<String>(name)
        .map(String::as_str)
        .unwrap_or_default()
}

fn now() -> u64 {
    u64::try_from(
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis(),
    )
    .unwrap_or(u64::MAX)
}

fn bundle(vault: &VaultDirectory, profile: &str) -> CliResult<Bundle> {
    let email = vault
        .profile_email(profile)?
        .ok_or_else(|| cli_error("set the selected profile email before exchanging keys"))?;
    Ok(Bundle {
        profile: profile.to_owned(),
        email,
        generation: vault.list_profile_generations(profile)?.active_generation,
        encryption_key: vault.load_private_key(profile)?.public_key().to_bytes(),
        signing_key: vault
            .load_owner_signing_key(profile)?
            .public_key()
            .to_bytes(),
    })
}

pub(super) fn run(command: &str, args: &ArgMatches) -> CliResult<()> {
    let vault = default_vault()?;
    match command {
        "exchange" => invite(&vault, args),
        "accept" => accept(&vault, args),
        "exchanges" => list(&vault, args),
        "verify" => verify(&vault, args),
        "cancel-exchange" => cancel(&vault, args),
        "verify-author" => verify_author(&vault, args),
        "forget-exchange" => forget(&vault, args),
        _ => Err(cli_error("unknown exchange command")),
    }
}

fn invite(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    let client = ExchangeClient::new(value(args, "key-server"))?;
    let server = client.origin().to_owned();
    let profile = value(args, "profile");
    let created = now();
    let mut offer = Offer {
        version: 1,
        id: random_token()?,
        inviter: bundle(vault, profile)?,
        recipient_email: revault_publish_protocol::normalize_contact_email(value(args, "email"))?,
        created_ms: created,
        expires_ms: created + args.get_one::<u64>("ttl-hours").copied().unwrap_or(24) * 3_600_000,
        signature: Vec::new(),
    };
    offer.sign(&vault.load_owner_signing_key(profile)?)?;
    offer.validate(created)?;
    let local = LocalExchange {
        server: server.clone(),
        inviter: true,
        token: random_token()?,
        offer,
        acceptance: None,
        verified_contact: None,
    };
    // Persist capability before the network mutation so lost responses are retryable.
    vault.save_exchange(&local)?;
    client.request(&Request::Create {
        offer: local.offer.clone(),
        owner_token: local.token.clone(),
    })?;
    show(&local)?;
    println!("Send the invitation to the intended recipient. Compare identities and the full shared fingerprint through another trusted channel after acceptance.");
    Ok(())
}

fn accept(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    let invitation = value(args, "invitation");
    let (base, id) = invitation
        .rsplit_once("/exchange#")
        .ok_or_else(|| cli_error("invalid invitation URL"))?;
    if !revault_publish_protocol::exchange::valid_token(id) {
        return Err(cli_error("invalid invitation ID"));
    }
    let client = ExchangeClient::new(base)?;
    let mut local = if let Some(existing) = vault
        .list_exchanges()?
        .into_iter()
        .find(|e| e.offer.id == id)
    {
        if existing.inviter
            || existing.server != client.origin()
            || existing
                .acceptance
                .as_ref()
                .map(|a| a.recipient.profile.as_str())
                != Some(value(args, "profile"))
        {
            return Err(cli_error("invitation conflicts with pinned local state"));
        }
        existing
    } else {
        let response = client.request(&Request::Inspect { id: id.to_owned() })?;
        let offer = response
            .offer
            .ok_or_else(|| cli_error("relay omitted invitation"))?;
        offer.validate(now())?;
        if offer.id != id {
            return Err(cli_error("relay substituted invitation"));
        }
        let profile = value(args, "profile");
        let acceptance = Acceptance::new(
            &offer,
            bundle(vault, profile)?,
            &vault.load_owner_signing_key(profile)?,
        )?;
        acceptance.validate(&offer)?;
        LocalExchange {
            server: client.origin().to_owned(),
            inviter: false,
            token: random_token()?,
            offer,
            acceptance: Some(acceptance),
            verified_contact: None,
        }
    };
    vault.save_exchange(&local)?;
    sync(vault, &mut local)?;
    show(&local)?;
    Ok(())
}

fn list(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    for mut local in vault.list_exchanges()? {
        if !args.get_flag("offline") && local.verified_contact.is_none() {
            if let Err(error) = sync(vault, &mut local) {
                eprintln!("Exchange {}: {error}", local.offer.id);
            }
        }
        show(&local)?;
    }
    Ok(())
}

fn verify(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    let mut local = vault.load_exchange(value(args, "id"))?;
    if local.acceptance.is_none() {
        sync(vault, &mut local)?;
    }
    show(&local)?;
    if local.acceptance.is_none() {
        return Err(cli_error("waiting for reciprocal acceptance"));
    }
    let interactive = io::stdin().is_terminal();
    if args.get_one::<String>("channel").is_none() {
        if !interactive {
            return Err(cli_error("--channel is required when not interactive"));
        }
        let answer =
            prompt("Comparison channel (in-person / known-phone-call / trusted-messenger): ")?;
        if !["in-person", "known-phone-call", "trusted-messenger"].contains(&answer.as_str()) {
            return Err(cli_error(
                "an independently trusted comparison channel is required",
            ));
        }
    }
    let compared = if let Some(fingerprint) = args.get_one::<String>("fingerprint") {
        fingerprint.clone()
    } else if interactive {
        prompt("Enter the other person's full shared fingerprint after checking both identities: ")?
    } else {
        return Err(cli_error("--fingerprint is required when not interactive"));
    };
    vault.verify_exchange(&local.offer.id, value(args, "name"), &compared)?;
    println!("contact={}\nverified=yes", value(args, "name"));
    if let Err(error) = ExchangeClient::new(&local.server)?.request(&Request::Complete {
        id: local.offer.id,
        token: local.token,
    }) {
        eprintln!("Contact saved; relay acknowledgement pending: {error}");
    }
    Ok(())
}

fn cancel(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    let local = vault.load_exchange(value(args, "id"))?;
    if !local.inviter {
        return Err(cli_error("only the inviter can cancel"));
    }
    ExchangeClient::new(&local.server)?.request(&Request::Cancel {
        id: local.offer.id.clone(),
        owner_token: local.token,
    })?;
    vault.forget_exchange(&local.offer.id)?;
    println!("cancelled=yes");
    Ok(())
}

fn verify_author(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    let expected = vault.load_contact_signing_key(value(args, "name"))?;
    let path = std::path::Path::new(value(args, "lockbox"));
    let mut authenticated = false;
    for profile in vault.list_private_keys()? {
        let key = vault.load_private_key(&profile)?;
        match revault_lockbox_api::Lockbox::open(
            path,
            revault_lockbox_api::LockboxOpen::ContactKeyPair(key),
        ) {
            Ok(lockbox) => {
                if !lockbox.owner_signing_public_key_matches(&expected)? {
                    return Err(cli_error(
                        "lockbox signer does not match the selected contact",
                    ));
                }
                authenticated = true;
                break;
            }
            Err(revault_lockbox_api::Error::InvalidKey) => (),
            Err(error) => return Err(error.into()),
        }
    }
    if !authenticated {
        return Err(cli_error("no local profile can open this lockbox"));
    }
    println!("author={}\nverified=yes", value(args, "name"));
    Ok(())
}

fn forget(vault: &VaultDirectory, args: &ArgMatches) -> CliResult<()> {
    vault.forget_exchange(value(args, "id"))?;
    println!("forgotten=yes");
    Ok(())
}

fn sync(vault: &VaultDirectory, local: &mut LocalExchange) -> CliResult<()> {
    local.offer.validate(now())?;
    let client = ExchangeClient::new(&local.server)?;
    let request = if local.inviter {
        Request::Create {
            offer: local.offer.clone(),
            owner_token: local.token.clone(),
        }
    } else {
        Request::Accept {
            id: local.offer.id.clone(),
            recipient_token: local.token.clone(),
            acceptance: local
                .acceptance
                .clone()
                .ok_or_else(|| cli_error("missing local acceptance"))?,
        }
    };
    let response = client.request(&request)?;
    if response.offer.as_ref() != Some(&local.offer) {
        return Err(cli_error("relay changed the pinned invitation"));
    }
    if let Some(acceptance) = response.acceptance {
        acceptance.validate(&local.offer)?;
        if local
            .acceptance
            .as_ref()
            .is_some_and(|old| old != &acceptance)
        {
            return Err(cli_error("relay changed the pinned acceptance"));
        }
        local.acceptance = Some(acceptance);
        vault.save_exchange(local)?;
    }
    Ok(())
}

fn show(local: &LocalExchange) -> CliResult<()> {
    if local.inviter {
        println!("invitation={}/exchange#{}", local.server, local.offer.id);
    }
    println!("expires_at_unix_ms={}", local.offer.expires_ms);
    println!(
        "exchange={}\nfrom={} ({})\nto={}",
        local.offer.id,
        local.offer.inviter.email,
        local.offer.inviter.profile,
        local.offer.recipient_email
    );
    if let Some(acceptance) = &local.acceptance {
        println!(
            "reply_profile={}\nverification={}",
            acceptance.recipient.profile,
            verification(&local.offer, acceptance)?
        );
    }
    println!(
        "state={}",
        if local.verified_contact.is_some() {
            "verified"
        } else if local.acceptance.is_some() {
            "verification-needed"
        } else if now() >= local.offer.expires_ms {
            "expired"
        } else {
            "awaiting-acceptance"
        }
    );
    Ok(())
}

fn prompt(message: &str) -> CliResult<String> {
    print!("{message}");
    io::stdout().flush()?;
    let mut value = String::new();
    io::stdin().read_line(&mut value)?;
    Ok(value.trim().to_owned())
}
