local revault = require('revault_api')
local api = revault.Vault.new()
local separator = package.config:sub(1, 1)
local windows = separator == '\\'
local temporary = os.getenv('TMPDIR') or os.getenv('TEMP') or (windows and '.' or '/tmp')

local function pass(symbol, assertions)
  print(string.format('PASS\tlua\t%s\t%d', symbol, assertions or 1))
end
local function check(value, message) if not value then error(message, 2) end end
local function quote(path) return '"' .. path:gsub('"', '\\"') .. '"' end
local function mkdir(path)
  local command = windows and ('mkdir ' .. quote(path) .. ' 2>NUL') or ('mkdir -p ' .. quote(path))
  local ok = os.execute(command); assert(ok == true or ok == 0)
end
local function remove(path)
  os.execute(windows and ('rmdir /s /q ' .. quote(path) .. ' 2>NUL') or ('rm -rf ' .. quote(path)))
end
local function pause()
  local ffi = require('ffi')
  if windows then ffi.cdef('void Sleep(unsigned long);'); ffi.C.Sleep(50)
  else ffi.cdef('int usleep(unsigned int);'); ffi.C.usleep(50000) end
end
local function write(path, bytes)
  local file = assert(io.open(path, 'wb')); assert(file:write(bytes)); file:close()
end
local function read(path)
  local file = assert(io.open(path, 'rb')); local value = assert(file:read('*a')); file:close(); return value
end
local function bytes(first, last)
  local value = {}; for index = first, last do value[#value + 1] = string.char(index) end
  return table.concat(value)
end
local function artifact_root()
  local path = (os.getenv('REVAULT_E2E_ARTIFACT_DIR') or '/tmp/revault-e2e-artifacts') .. '/lua'
  mkdir(path); return path
end
local function fields()
  return revault.Models.FormFieldList.new({ values = {
    revault.Models.FormField.new({ id = 'username', label = 'Username', kind = 'text', required = true })
  }}):encode()
end
local function moves(source, destination)
  return revault.Models.PathMoveList.new({ values = {
    revault.Models.PathMove.new({ source = source, destination = destination })
  }}):encode()
end

local function archive_lifecycle()
  local key = string.rep('K', 32)
  local box = api:lockbox_create(key); pass('lockbox_create')
  box:add_file('/hello.txt', 'hello from lua conformance', false); pass('lockbox_add_file', 2)
  check(box:get_file('/hello.txt') == 'hello from lua conformance', 'get file'); pass('lockbox_get_file', 3)
  box:add_file_with_permissions('/hello.txt', 'replacement payload', 416, true); pass('lockbox_add_file_with_permissions', 2)
  check(box:permissions('/hello.txt') == 416, 'permissions'); pass('lockbox_permissions')
  box:create_dir('/tree', true); pass('lockbox_create_dir', 2)
  check(box:is_dir('/tree'), 'directory'); pass('lockbox_is_dir')
  box:create_parent_dirs('/tree/a/b/file'); pass('lockbox_create_parent_dirs', 2)
  box:rename('/hello.txt', '/renamed.txt'); pass('lockbox_rename', 3)
  check(box:exists('/renamed.txt') and not box:exists('/hello.txt'), 'exists'); pass('lockbox_exists', 2)
  box:set_permissions('/renamed.txt', 384); pass('lockbox_set_permissions', 2)
  check(box:read_range('/renamed.txt', 0, 11) == 'replacement', 'range'); pass('lockbox_read_range', 3)
  box:set_variable('normal', 'value', false); pass('lockbox_set_variable')
  check(box:get_variable('normal') == 'value', 'variable'); pass('lockbox_get_variable', 3)
  box:move_variables(moves('normal', 'moved')); check(box:get_variable('moved') == 'value', 'moved variable')
  box:move_variables(moves('moved', 'normal')); pass('lockbox_move_variables', 3)
  box:set_variable('secret', 'hidden', true); box:variable_sensitivity('secret'); pass('lockbox_variable_sensitivity', 2)
  check(#box:list_variables().values == 2, 'variables'); pass('lockbox_list_variables')
  box:delete_variable('normal'); pass('lockbox_delete_variable')
  box:add_symlink('/link', '/renamed.txt', false); pass('lockbox_add_symlink')
  check(box:get_symlink_target('/link') == '/renamed.txt', 'symlink'); pass('lockbox_get_symlink_target', 3)
  check(#box:list('/', true).entries > 0, 'list'); box:stat('/renamed.txt'); pass('lockbox_list', 2); pass('lockbox_stat', 2)
  box:set_workload_profile('read-mostly'); box:set_worker_policy('single', 1); box:runtime_options()
  pass('lockbox_set_workload_profile'); pass('lockbox_set_worker_policy'); pass('lockbox_runtime_options')
  box:commit(); pass('lockbox_commit'); check(box:storage_len() > 0, 'storage'); pass('lockbox_storage_len')
  local archive = box:to_bytes(); pass('lockbox_to_bytes', 2); pass('buffer_free')
  local format = api:lockbox_format_version(); check(format > 0 and api:lockbox_probe_format_version(archive) == format, 'format probe')
  pass('lockbox_format_version', 2); pass('lockbox_probe_format_version', 2)
  check(api:lockbox_probe_format_version('bad') == 0 and #api:last_error_details().message > 0, 'error details'); pass('buffer_last_error_details', 2)
  local path = artifact_root() .. '/archive.lbox'; write(path, archive)
  print('ARTIFACT\tlua\tarchive-created\t' .. path); box:free()
  local opened = api:lockbox_open(archive, key); pass('lockbox_open', 2)
  check(opened:get_file('/renamed.txt') == 'replacement payload', 'opened')
  print('ARTIFACT\tlua\tarchive-opened\t' .. path)
  opened:delete('/renamed.txt'); pass('lockbox_delete', 2)
  opened:remove_dir('/tree', true); pass('lockbox_remove_dir', 2); opened:free(); pass('lockbox_free', 2)
end

local function key_lifecycle()
  local content = bytes(0, 31)
  local contact = api:key_contact_generate(); pass('key_contact_generate')
  local private_key = contact:private(); pass('key_contact_private', 2)
  local copy = api:key_contact_from_private(private_key); pass('key_contact_from_private')
  local public_bytes = contact:public(); pass('key_contact_public', 2)
  local public_key = api:key_contact_public_from_bytes(public_bytes); pass('key_contact_public_from_bytes')
  local wrapped = public_key:encrypt(content); pass('key_contact_encrypt')
  check(copy:decrypt(wrapped) == content, 'decrypt'); pass('key_contact_decrypt', 3)
  check(#wrapped:public() > 0 and #wrapped:ciphertext() > 0 and #wrapped:encrypted() > 0, 'wrapped')
  pass('key_contact_wrapped_public', 2); pass('key_contact_wrapped_ciphertext', 2); pass('key_contact_wrapped_encrypted', 2)
  wrapped:free(); pass('key_contact_wrapped_free')
  local imported_private = api:vault_key_import_private(api:vault_key_export_private(contact, 'raw-hex'))
  pass('vault_key_export_private', 2); pass('vault_key_import_private')
  local imported_public = api:vault_key_import_public(api:vault_key_export_public(public_key, 'lockbox-pem'))
  pass('vault_key_export_public', 2); pass('vault_key_import_public')
  local fingerprint = api:vault_key_fingerprint(imported_public); pass('vault_key_fingerprint', 2)
  local hex = api:vault_key_format_hex(fingerprint); check(api:vault_key_decode_hex(hex) == fingerprint, 'hex')
  pass('vault_key_format_hex', 2); pass('vault_key_decode_hex', 2)
  local short = fingerprint:sub(1, 12); local code = api:vault_key_format_crockford(short)
  api:vault_key_format_crockford_reading(code); check(api:vault_key_decode_crockford(code) == short, 'crockford')
  pass('vault_key_format_crockford', 2); pass('vault_key_format_crockford_reading', 2); pass('vault_key_decode_crockford', 2)
  imported_public:public_free(); public_key:public_free(); pass('key_contact_public_free', 2)
  imported_private:free(); copy:free(); contact:free(); pass('key_contact_free', 3)
  local plain = api:vault_key_hex_encode(content); check(api:vault_key_hex_decode(plain) == content, 'plain hex')
  pass('vault_key_hex_encode', 2); pass('vault_key_hex_decode', 2)
  local signing = api:key_signing_generate(); pass('key_signing_generate')
  local signing_private, signing_public = signing:private(), signing:public()
  pass('key_signing_private', 2); pass('key_signing_public', 2)
  api:key_signing_from_private(signing_private):free(); pass('key_signing_from_private')
  api:key_signing_public_from_bytes(signing_public):public_free()
  pass('key_signing_public_from_bytes'); pass('key_signing_public_free', 2)
  signing:free(); pass('key_signing_free', 3)
end

local function advanced_archive()
  local key = string.rep('A', 32)
  local box = api:lockbox_create_with_options(key, 'bytes', 4 * 1024 * 1024, 'bulk-import', 'single', 1); pass('lockbox_create_with_options')
  box:add_file('/account.txt', 'account data', false)
  box:list_with_options('/', '*.txt', true, true, false, false, 20); pass('lockbox_list_with_options', 2)
  local definition = box:define_form('account', 'Account', 'Account form', fields()); pass('lockbox_define_form', 2)
  box:list_form_definitions(); box:resolve_form('account'); box:list_form_revisions(definition.type_id)
  pass('lockbox_list_form_definitions'); pass('lockbox_resolve_form'); pass('lockbox_list_form_revisions')
  box:create_form_record('/account.form', 'account', 'Primary'); pass('lockbox_create_form_record')
  box:set_form_field('/account.form', 'username', 'alice', false); pass('lockbox_set_form_field')
  box:get_form_record('/account.form'); box:get_form_field('/account.form', 'username'); box:list_form_records()
  pass('lockbox_get_form_record'); pass('lockbox_get_form_field'); pass('lockbox_list_form_records')
  box:move_form_records(moves('/account.form', '/moved.form')); box:get_form_record('/moved.form')
  box:move_form_records(moves('/moved.form', '/account.form')); pass('lockbox_move_form_records', 3)
  local signing, contact = api:key_signing_generate(), api:key_contact_generate()
  local public_key = api:key_contact_public_from_bytes(contact:public())
  box:set_owner_signing_key(signing); pass('lockbox_set_owner_signing_key')
  local slot = box:add_password('archive password'); pass('lockbox_add_password')
  box:add_contact(public_key, 'recipient'); pass('lockbox_add_contact'); box:list_key_slots(); pass('lockbox_list_key_slots')
  box:delete_key(slot); pass('lockbox_delete_key'); box:commit(); box:owner_inspection(); pass('lockbox_owner_inspection', 2)
  box:cache_stats(); box:import_stats(); box:reset_import_stats(); box:page_inspection(); box:recovery_report()
  box:recovery_report_render(true, 100); box:stream_content(false); box:id()
  for _, symbol in ipairs({'lockbox_cache_stats','lockbox_import_stats','lockbox_reset_import_stats','lockbox_page_inspection','lockbox_recovery_report'}) do pass(symbol) end
  pass('lockbox_recovery_report_render', 2); pass('lockbox_stream_content'); pass('lockbox_id', 2)
  local archive = box:to_bytes(); local path = artifact_root() .. '/advanced.lbox'; write(path, archive)
  api:lockbox_inspect_file(path); api:lockbox_recovery_scan_path(path, key); api:lockbox_recovery_scan(archive, key)
  pass('lockbox_inspect_file'); pass('lockbox_recovery_scan_path'); pass('lockbox_recovery_scan')
  api:lockbox_recovery_salvage(archive:sub(1, -33), key, signing):free(); pass('lockbox_recovery_salvage', 2)
  api:lockbox_open_with_options(archive, key, 'bytes', 4 * 1024 * 1024, 'bulk-import', 'single', 1):free(); pass('lockbox_open_with_options', 2)
  local password_box = api:lockbox_create_password('archive password'); password_box:add_file('/password.txt', 'password protected', false); password_box:commit()
  local password_archive = password_box:to_bytes(); password_box:free(); pass('lockbox_create_password')
  local password_open = api:lockbox_open_password(password_archive, 'archive password'); password_open:get_file('/password.txt'); password_open:free(); pass('lockbox_open_password', 2)
  local contact_box = api:lockbox_create_contact(public_key); contact_box:add_file('/contact.txt', 'contact protected', false); contact_box:commit()
  local contact_archive = contact_box:to_bytes(); contact_box:free(); pass('lockbox_create_contact')
  local contact_open = api:lockbox_open_contact(contact_archive, contact); contact_open:get_file('/contact.txt'); contact_open:free(); pass('lockbox_open_contact', 2)
  local signed = api:lockbox_create_with_signing_key(key, signing); signed:commit(); signed:free(); pass('lockbox_create_with_signing_key', 2)
  local extract = temporary .. separator .. 'revault-lua-extract'; remove(extract); mkdir(extract)
  box:extract_file('/account.txt', extract .. '/account.txt', false); pass('lockbox_extract_file', 2)
  local tree = extract .. '/tree'; mkdir(tree); box:extract_directory(tree, 1024 * 1024, 4 * 1024 * 1024, 100, false, true, false); pass('lockbox_extract_directory', 2)
  box:delete_form_record('/account.form'); pass('lockbox_delete_form_record')
  box:free(); public_key:public_free(); contact:free(); signing:free()
end

local function vault_lifecycle()
  local root = artifact_root() .. '/vault'; remove(root); mkdir(root)
  local password, changed, id = 'vault password', 'new vault password', bytes(160, 175)
  local profile, contact = api:key_contact_generate(), api:key_contact_generate()
  local contact_public = api:key_contact_public_from_bytes(contact:public())
  local owner = api:key_signing_generate(); local owner_public = api:key_signing_public_from_bytes(owner:public())
  local vault = api:vault_directory_replace(root, password); pass('vault_directory_replace')
  print('ARTIFACT\tlua\tvault-created\t' .. root)
  check(vault:root() == root and vault:structure_version() > 0, 'vault'); pass('vault_directory_root', 3); pass('vault_directory_structure_version')
  local current = api:vault_structure_version_current()
  check(current == vault:structure_version() and api:vault_directory_probe_structure_version(root, password) == current, 'vault probe')
  pass('vault_structure_version_current', 2); pass('vault_directory_probe_structure_version', 2)
  vault:store_private_key('alice', profile); pass('vault_directory_store_private_key')
  vault:private_key_exists('alice'); pass('vault_directory_private_key_exists')
  vault:load_private_key('alice'):free(); vault:load_private_key_generation('alice', 1):free()
  pass('vault_directory_load_private_key'); pass('vault_directory_load_private_key_generation')
  vault:store_profile_email('alice', 'alice@example.test'); vault:profile_email('alice')
  pass('vault_directory_store_profile_email'); pass('vault_directory_profile_email', 3)
  vault:list_profile_generations('alice'); vault:rotate_private_key('alice')
  pass('vault_directory_list_profile_generations'); pass('vault_directory_rotate_private_key')
  vault:load_owner_signing_key('alice'):free(); vault:load_owner_signing_key_generation('alice', 1):free()
  pass('vault_directory_load_owner_signing_key'); pass('vault_directory_load_owner_signing_key_generation')
  vault:store_contact('bob', contact_public); vault:contact_exists('bob'); vault:load_contact('bob'):public_free(); vault:list_contacts()
  pass('vault_directory_store_contact'); pass('vault_directory_contact_exists'); pass('vault_directory_load_contact'); pass('vault_directory_list_contacts')
  vault:store_contact_signing_key('bob', owner_public); vault:load_contact_signing_key('bob'):public_free()
  pass('vault_directory_store_contact_signing_key'); pass('vault_directory_load_contact_signing_key')
  vault:list_private_keys(); vault:list_private_key_names(); vault:list_contact_names()
  pass('vault_directory_list_private_keys'); pass('vault_directory_list_private_key_names'); pass('vault_directory_list_contact_names')
  vault:store_backup(id, 'encrypted backup bytes'); vault:backup_count(); check(vault:load_backup(id) == 'encrypted backup bytes', 'backup')
  pass('vault_directory_store_backup'); pass('vault_directory_backup_count'); pass('vault_directory_load_backup', 3)
  vault:remember_lockbox(id, '/tmp/example.lbox'); vault:list_known_lockboxes()
  pass('vault_directory_remember_lockbox'); pass('vault_directory_list_known_lockboxes')
  vault:remember_access_slot_label(id, 7, 'primary'); vault:list_access_slot_labels(id); vault:find_access_slot_labels(id, 'primary')
  pass('vault_directory_remember_access_slot_label'); pass('vault_directory_list_access_slot_labels'); pass('vault_directory_find_access_slot_labels')
  vault:remember_password(id, password); vault:remembered_password(id)
  pass('vault_directory_remember_password'); pass('vault_directory_remembered_password', 3)
  local vault_form = vault:define_form('login', 'Login', 'Login form', fields()); vault:resolve_form('login'); vault:list_forms()
  pass('vault_directory_define_form'); pass('vault_directory_resolve_form'); pass('vault_directory_list_forms')
  vault:list_form_revisions(vault_form.type_id); pass('vault_directory_list_form_revisions', 2)
  vault:seed_forms(); pass('vault_directory_seed_forms'); vault:list_form_aliases(); pass('vault_directory_list_form_aliases')
  vault:forget_access_slot_label(id, 7); vault:forget_lockbox('/tmp/example.lbox'); vault:delete_contact('bob')
  pass('vault_directory_forget_access_slot_label'); pass('vault_directory_forget_lockbox'); pass('vault_directory_delete_contact')
  vault:delete_private_key('alice'); vault:restore_private_key('alice', profile, owner, true)
  pass('vault_directory_delete_private_key', 2); pass('vault_directory_restore_private_key', 2)
  vault:free(); pass('vault_directory_free')
  local readonly = api:vault_read_only_open(root, password)
  readonly:list_profile_names(); readonly:list_contact_names(); readonly:list_form_aliases(); readonly:list_known_lockboxes()
  pass('vault_read_only_open'); pass('vault_read_only_list_profile_names', 2); pass('vault_read_only_list_contact_names')
  pass('vault_read_only_list_form_aliases', 2); pass('vault_read_only_list_known_lockboxes')
  readonly:free(); pass('vault_read_only_free')
  api:vault_directory_change_password(root, password, changed); pass('vault_directory_change_password')
  api:vault_directory_open(root, changed):free(); pass('vault_directory_open'); print('ARTIFACT\tlua\tvault-opened\t' .. root)
  api:vault_directory_open_or_create(root, changed):free(); pass('vault_directory_open_or_create')
  owner_public:public_free(); owner:free(); contact_public:public_free(); contact:free(); profile:free()
end

local function default_vault()
  mkdir(assert(os.getenv('LOCKBOX_VAULT_DIR')))
  api:vault_directory_replace_default('default password'):free(); pass('vault_directory_replace_default')
  api:vault_read_only_open_default('default password'):free(); pass('vault_read_only_open_default')
  api:vault_default_directory(); api:vault_default_path(); pass('vault_default_directory', 3); pass('vault_default_path', 2)
  api:vault_directory_open_or_create_default('default password'):free(); pass('vault_directory_open_or_create_default')
  api:vault_directory_change_default_password('default password', 'changed default password'); pass('vault_directory_change_default_password')
  local backup = artifact_root() .. '/default-vault.backup'; os.remove(backup)
  api:vault_backup_default(backup, false); api:vault_restore_default(backup, true)
  pass('vault_backup_default'); pass('vault_restore_default')
end

local function platform_store()
  local platform = api.platform; platform:status(); pass('vault_platform_status', 2)
  platform:set_scope('vault'); pass('vault_platform_set_scope')
  platform:disable(); platform:disabled(); pass('vault_platform_disable'); pass('vault_platform_disabled')
  platform:enable(); pass('vault_platform_enable')
  platform:put_password('platform vault password'); check(platform:get_password() == 'platform vault password', 'platform')
  pass('vault_platform_put_password'); pass('vault_platform_get_password', 3)
  platform:forget_password(); pass('vault_platform_forget_password')
end

local function agent_and_local()
  mkdir(assert(os.getenv('LOCKBOX_SESSION_AGENT_DIR'))); mkdir(assert(os.getenv('LOCKBOX_VAULT_DIR')))
  local directory = api:vault_directory_replace_default('agent vault password'); local profile = api:key_contact_generate()
  directory:store_private_key('default', profile); profile:free(); directory:free()
  local agent = api.agent; agent:forget_all(); pass('vault_forget_all')
  for _ = 1, 200 do if agent:is_running() then break end pause() end
  check(agent:is_running(), 'agent'); pass('vault_agent_serve'); pass('vault_is_running')
  agent:start(); pass('vault_agent_start')
  agent:verify_transport(); pass('vault_agent_verify_transport')
  local id, key = bytes(192, 207), bytes(32, 63)
  agent:put(id, key); check(agent:get(id) == key, 'agent key'); agent:list()
  pass('vault_agent_put'); pass('vault_agent_get', 3); pass('vault_agent_list')
  agent:put_vault_unlock_key('vault-id', key, 120); agent:get_vault_unlock_key('vault-id'); pass('vault_agent_put_vault_unlock_key'); pass('vault_agent_get_vault_unlock_key', 3)
  local owner = api:key_signing_generate(); agent:put_owner_signing_key('vault-id', 'alice', owner, 120); agent:get_owner_signing_key('vault-id', 'alice'):free()
  pass('vault_agent_put_owner_signing_key'); pass('vault_agent_get_owner_signing_key')
  local activity = agent:begin_activity('open'); pass('vault_agent_begin_activity'); agent:end_activity(activity); pass('vault_agent_end_activity')
  agent:sleep_support(); pass('vault_agent_sleep_support'); api:vault_agent_log_path(); api:vault_agent_log_destination()
  pass('vault_agent_log_path', 2); pass('vault_agent_log_destination', 2)
  local local_vault = api:vault_local(); pass('vault_local'); local root = temporary .. separator .. 'revault-lua-local'; remove(root); mkdir(root)
  local password_path = root .. '/password.lbox'; local box = local_vault:create_lockbox_password(password_path, 'local password')
  box:add_file('/data.txt', 'local vault data', false); box:commit(); box:free(); pass('vault_create_lockbox_password', 3)
  local_vault:cache_lockbox_password(password_path, 'local password', 120); pass('vault_cache_lockbox_password')
  local opened = local_vault:open_lockbox_password(password_path, 'local password'); opened:get_file('/data.txt'); opened:free(); pass('vault_open_lockbox_password', 3)
  local_vault:close_lockbox(password_path); pass('vault_close_lockbox')
  local content_path = root .. '/content.lbox'; box = local_vault:create_lockbox_content_key(content_path, key, owner)
  box:add_file('/data.txt', 'local vault data', false); box:commit(); box:free(); pass('vault_create_lockbox_content_key', 3)
  opened = local_vault:open_lockbox_content_key(content_path, key, owner); opened:get_file('/data.txt'); opened:free(); pass('vault_open_lockbox_content_key', 3)
  local contact = api:key_contact_generate(); local public_key = api:key_contact_public_from_bytes(contact:public())
  box = local_vault:create_lockbox_contact(root .. '/contact.lbox', public_key, 'recipient', owner)
  box:add_file('/data.txt', 'local vault data', false); box:commit(); box:free(); pass('vault_create_lockbox_contact', 3)
  public_key:public_free(); contact:free(); local_vault:close_all(); pass('vault_close_all'); local_vault:free(); pass('vault_free'); owner:free()
  agent:forget_owner_signing_key('vault-id', 'alice'); agent:forget_vault_unlock_key('vault-id'); agent:forget(id)
  pass('vault_agent_forget_owner_signing_key'); pass('vault_agent_forget_vault_unlock_key'); pass('vault_agent_forget')
  agent:stop(); pass('vault_agent_stop')
end

local function interop(producer)
  local root = os.getenv('REVAULT_E2E_ARTIFACT_DIR') or '/tmp/revault-e2e-artifacts'
  local box = api:lockbox_open(read(root .. '/' .. producer .. '/archive.lbox'), string.rep('K', 32))
  check(box:get_file('/renamed.txt') == 'replacement payload', 'foreign archive'); box:free()
  local vault = api:vault_directory_open(root .. '/' .. producer .. '/vault', 'new vault password')
  check(vault:structure_version() > 0, 'foreign vault'); vault:free()
  print('INTEROP\tlua\t' .. producer .. '\tarchive\t3')
  print('INTEROP\tlua\t' .. producer .. '\tvault\t2')
end

if arg[1] == '--serve-agent' then api.agent:serve()
elseif arg[1] == '--default' then default_vault()
elseif arg[1] == '--platform' then platform_store()
elseif arg[1] == '--agent' then agent_and_local()
elseif arg[1] == '--interop' then interop(assert(arg[2]))
else archive_lifecycle(); key_lifecycle(); advanced_archive(); vault_lifecycle(); api:last_error(); pass('buffer_last_error') end
