<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RevaultVersion Condition="'$(RevaultVersion)' == ''">0.2.0</RevaultVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Revault.Api" Version="$(RevaultVersion)" />
  </ItemGroup>
</Project>
