"""Generate documented Go domain models and private FlatBuffers adapters."""

from pathlib import Path
import re
import subprocess
from model_docs import description, field_description

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = Path(__file__).with_name("revault_bindings.fbs")
OUTPUT = ROOT / "go/domain_models.go"

SCALARS = {
    "string": "string",
    "bool": "bool",
    "uint": "uint32",
    "ulong": "uint64",
    "ubyte": "byte",
    "LockboxEntryKind": "LockboxEntryKind",
}
PUBLIC_NAMES = {"PlatformStatus": "PlatformCredentialStatus"}


def public_name(name: str) -> str:
    return PUBLIC_NAMES.get(name, name)


def exported(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_"))


def go_type(value: str) -> str:
    if value.startswith("["):
        inner = value[1:-1].split(".")[-1]
        return "[]byte" if inner == "ubyte" else f"[]{SCALARS.get(inner, inner)}"
    return SCALARS.get(value.split(".")[-1], value.split(".")[-1])


tables = {}
current = None
for line in SCHEMA.read_text().splitlines():
    if match := re.match(r"table (\w+) \{", line.strip()):
        current = match.group(1)
        tables[current] = []
    elif current and line.strip() == "}":
        current = None
    elif current and (match := re.match(r"\s*(\w+):([^ ]+) \(id:", line)):
        tables[current].append(match.groups())

wrappers = {name for name in tables if name.endswith("List") or name.startswith("Optional")}
wrappers |= {"StringValue"}
base = [name for name in tables if name not in wrappers]

lines = [
    "// Code generated by bindings/flatbuffers/generate_go_models.py. DO NOT EDIT.",
    "package revault",
    "",
    "import (",
    '  "github.com/google/flatbuffers/go"',
    '  transport "github.com/onepub-dev/revault-api/internal/transport"',
    ")",
    "",
    "// LockboxEntryKind identifies the filesystem object stored at a lockbox path.",
    "type LockboxEntryKind int32",
    "const (",
    "  // LockboxEntryKindUnspecified means no recognized kind was reported.",
    "  LockboxEntryKindUnspecified LockboxEntryKind = iota",
    "  // LockboxEntryKindFile is a regular file.",
    "  LockboxEntryKindFile",
    "  // LockboxEntryKindSymlink is a symbolic link.",
    "  LockboxEntryKindSymlink",
    "  // LockboxEntryKindDirectory is a directory.",
    "  LockboxEntryKindDirectory",
    ")",
    "",
]

for name in base:
    public = public_name(name)
    lines += [f"// {public} represents {description(name)[0].lower() + description(name)[1:]}", f"type {public} struct {{"]
    for field, value in tables[name]:
        lines += [f"  // {exported(field)}: {field_description(name, field)}", f"  {exported(field)} {go_type(value)}"]
    lines += ["}", ""]

for name in base:
    public = public_name(name)
    lines.append(f"func domain{name}(value *transport.{name}T) *{public} {{")
    lines.append("  if value == nil { return nil }")
    lines.append(f"  result := &{public}{{}}")
    for field, value in tables[name]:
        field_name = exported(field)
        raw = value.split(".")[-1]
        if value.startswith("["):
            inner = value[1:-1].split(".")[-1]
            if inner == "ubyte":
                lines.append(f"  result.{field_name} = append([]byte(nil), value.{field_name}...)")
            elif inner in SCALARS:
                lines.append(f"  result.{field_name} = append([]{SCALARS[inner]}(nil), value.{field_name}...)")
            else:
                lines += [f"  result.{field_name} = make([]{inner}, 0, len(value.{field_name}))", f"  for _, item := range value.{field_name} {{ result.{field_name} = append(result.{field_name}, *domain{inner}(item)) }}"]
        elif raw == "LockboxEntryKind":
            lines.append(f"  result.{field_name} = LockboxEntryKind(value.{field_name})")
        elif raw in SCALARS:
            lines.append(f"  result.{field_name} = value.{field_name}")
        else:
            lines.append(f"  if item := domain{raw}(value.{field_name}); item != nil {{ result.{field_name} = *item }}")
    lines += ["  return result", "}", f"func decode{name}(bytes []byte) *{public} {{ return domain{name}(transport.GetRootAs{name}(bytes, 0).UnPack()) }}", ""]

list_types = {
    "StreamChunkList": "StreamChunk", "PageInspectionList": "PageInspection",
    "LockboxEntryList": "LockboxEntry", "VariableList": "Variable",
    "KeySlotList": "KeySlot", "FormDefinitionList": "FormDefinition",
    "FormRecordList": "FormRecord", "ContactList": "Contact",
    "KnownLockboxList": "KnownLockbox", "AccessSlotLabelList": "AccessSlotLabel",
    "AgentEntryList": "AgentEntry", "ProfileHistoryList": "ProfileHistory",
}
for wrapper, item in list_types.items():
    field = "Entries" if wrapper == "LockboxEntryList" else "Values"
    lines += [f"func decode{wrapper}(bytes []byte) []{item} {{", f"  source := transport.GetRootAs{wrapper}(bytes, 0).UnPack().{field}", f"  result := make([]{item}, 0, len(source))", f"  for _, value := range source {{ result = append(result, *domain{item}(value)) }}", "  return result", "}", ""]

lines += [
    "func decodeStringList(bytes []byte) []string { return append([]string(nil), transport.GetRootAsStringList(bytes, 0).UnPack().Values...) }",
    "func decodeOptionalLockboxEntry(bytes []byte) *LockboxEntry { return domainLockboxEntry(transport.GetRootAsOptionalLockboxEntry(bytes, 0).UnPack().Value) }",
    "func decodeOptionalFormRecord(bytes []byte) *FormRecord { return domainFormRecord(transport.GetRootAsOptionalFormRecord(bytes, 0).UnPack().Value) }",
    "func decodeOptionalFormValue(bytes []byte) *FormValue { return domainFormValue(transport.GetRootAsOptionalFormValue(bytes, 0).UnPack().Value) }",
    "func decodeOptionalString(bytes []byte) *string { value := transport.GetRootAsOptionalString(bytes, 0).UnPack(); if !value.Present { return nil }; result := value.Value; return &result }",
    "func encodePathMoves(values []PathMove) []byte {",
    "  items := make([]*transport.PathMoveT, 0, len(values))",
    "  for _, value := range values { items = append(items, &transport.PathMoveT{Source: value.Source, Destination: value.Destination}) }",
    "  builder := flatbuffers.NewBuilder(256); root := (&transport.PathMoveListT{Values: items}).Pack(builder); builder.Finish(root); return append([]byte(nil), builder.FinishedBytes()...)",
    "}",
    "func encodeFormFields(values []FormField) []byte {",
    "  items := make([]*transport.FormFieldT, 0, len(values))",
    "  for _, value := range values { items = append(items, &transport.FormFieldT{Id: value.Id, Label: value.Label, Kind: value.Kind, Required: value.Required}) }",
    "  builder := flatbuffers.NewBuilder(256); root := (&transport.FormFieldListT{Values: items}).Pack(builder); builder.Finish(root); return append([]byte(nil), builder.FinishedBytes()...)",
    "}",
]

OUTPUT.write_text("\n".join(lines) + "\n")
subprocess.run(["gofmt", "-w", str(OUTPUT)], check=True)
