"""User-facing descriptions shared by generated binding domain models."""

DESCRIPTIONS = {
    "LockboxEntry": "Metadata for one file, directory, or symbolic link stored at a lockbox path.",
    "PathMove": "A source and destination pair used to rename a variable or form record atomically.",
    "FormField": "One named input in a reusable form definition, including its display label and sensitivity kind.",
    "FormDefinition": "A versioned form schema used to validate and label structured records in a lockbox.",
    "FormValue": "The current value and sensitivity metadata for one field in a stored form record.",
    "FormRecord": "A named structured record stored at a lockbox path and tied to a form-definition revision.",
    "RecoveryReport": "The files and metadata recovered, or found damaged, while inspecting or salvaging a lockbox.",
    "KeySlot": "One password or contact credential that can unlock a lockbox content key.",
    "CacheStats": "Current capacity, occupancy, hit, and miss counters for an open lockbox cache.",
    "ImportStats": "Time spent reading host files and preparing encrypted pages during the latest import work.",
    "PageObject": "One logical object recorded inside an inspected encrypted lockbox page.",
    "PageInspection": "Layout and utilization details for one encrypted page in a lockbox archive.",
    "FileInspection": "Header, owner-signature, and key-slot information read from a lockbox file without opening its contents.",
    "ProfileGeneration": "One active or retired generation of the contact keys belonging to a named vault profile.",
    "ProfileHistory": "The active generation and rotation history for a named vault profile.",
    "KnownLockbox": "A lockbox identifier and host path remembered by the local vault for later discovery.",
    "AccessSlotLabel": "A local human-readable label attached to one lockbox access slot.",
    "StreamChunk": "A logical or physical byte range emitted while walking the contents of a lockbox.",
    "RuntimeOptions": "The workload and worker policies currently applied to an open lockbox.",
    "Variable": "The name and sensitivity classification of a variable stored in a lockbox.",
    "OwnerInspection": "Whether a lockbox is owner-signed and, when available, the signing-key fingerprint.",
    "Contact": "A named recipient public key stored in the local vault address book.",
    "AgentEntry": "A lockbox key currently held by the local session agent, identified by lockbox and path.",
    "SleepSupport": "The host capabilities used to protect cached secrets across suspend and sleep.",
    "PlatformStatus": "Availability and configuration of the operating-system credential store used for the vault password.",
    "VaultBackupManifest": "The version, size, checksum, and creation time of an exported local-vault backup.",
    "ErrorDetails": "Structured category, version, guidance, and artifact context for the most recent native failure.",
}

def description(name: str) -> str:
    """Return the concrete public description for a domain model."""
    return DESCRIPTIONS[name]


FIELD_DESCRIPTIONS = {
    ("LockboxEntry", "path"): "Absolute lockbox path of the stored entry.",
    ("LockboxEntry", "kind"): "Filesystem kind: file, directory, or symbolic link.",
    ("LockboxEntry", "length"): "Logical file length in bytes; zero for directories.",
    ("LockboxEntry", "permissions"): "Portable Unix permission bits stored with the entry.",
    ("PathMove", "source"): "Existing variable name or form-record path to rename.",
    ("PathMove", "destination"): "New variable name or form-record path.",
    ("FormField", "id"): "Stable field identifier used when reading and writing records.",
    ("FormField", "label"): "Human-readable label presented to a person entering data.",
    ("FormField", "kind"): "Field kind that determines validation and secret handling.",
    ("FormField", "required"): "Whether a record must provide a value for this field.",
    ("FormDefinition", "type_id"): "Stable identifier shared by every revision of this form type.",
    ("FormDefinition", "alias"): "Short name used to resolve the current form revision.",
    ("FormDefinition", "revision"): "Monotonically increasing revision number.",
    ("FormDefinition", "name"): "Human-readable name shown for this form.",
    ("FormDefinition", "description"): "Explanation shown to people completing the form.",
    ("FormDefinition", "fields"): "Ordered inputs accepted by this form revision.",
    ("FormValue", "field_id"): "Identifier of the form field that owns this value.",
    ("FormValue", "label"): "Display label captured from the form revision.",
    ("FormValue", "kind"): "Field kind captured from the form revision.",
    ("FormValue", "value"): "Plain value, or an empty string when the field is secret.",
    ("FormValue", "secret"): "Whether the value must be read through a scoped secret callback.",
    ("FormRecord", "path"): "Absolute lockbox path that identifies the record.",
    ("FormRecord", "name"): "Human-readable name assigned to this record.",
    ("FormRecord", "type_id"): "Stable identifier of the record's form type.",
    ("FormRecord", "definition_alias"): "Alias of the form definition used by the record.",
    ("FormRecord", "definition_revision"): "Exact form revision against which the record was created.",
    ("FormRecord", "values"): "Ordered non-secret field metadata and values.",
    ("RecoveryReport", "intact_files"): "Files whose complete contents remain recoverable.",
    ("RecoveryReport", "intact_file_count"): "Number of completely recoverable files.",
    ("RecoveryReport", "partial_files"): "Number of files for which only some content is recoverable.",
    ("RecoveryReport", "corrupt_records"): "Number of encrypted records that failed validation.",
    ("RecoveryReport", "toc_recovered"): "Whether a usable table of contents was recovered.",
    ("RecoveryReport", "variables_recovered"): "Whether variable metadata was recovered.",
    ("RecoveryReport", "variable_count"): "Number of recovered variables.",
    ("RecoveryReport", "forms_recovered"): "Whether form definitions and records were recovered.",
    ("RecoveryReport", "form_definition_count"): "Number of recovered form definitions.",
    ("RecoveryReport", "form_record_count"): "Number of recovered form records.",
    ("KeySlot", "id"): "Stable slot identifier used when removing this access method.",
    ("KeySlot", "protection"): "Access method, such as password or contact key.",
    ("KeySlot", "algorithm"): "Cryptographic algorithm protecting the content key.",
    ("CacheStats", "limit_bytes"): "Maximum decoded-page memory permitted for the cache.",
    ("CacheStats", "used_bytes"): "Decoded-page memory currently held by the cache.",
    ("CacheStats", "entries"): "Number of decoded pages currently cached.",
    ("CacheStats", "hits"): "Reads served by an already decoded page.",
    ("CacheStats", "misses"): "Reads that required decoding another page.",
    ("ImportStats", "host_stat_nanos"): "Nanoseconds spent reading host filesystem metadata, as decimal text.",
    ("ImportStats", "host_read_nanos"): "Nanoseconds spent reading host file content, as decimal text.",
    ("ImportStats", "frame_prepare_nanos"): "Nanoseconds spent preparing encrypted records, as decimal text.",
    ("ImportStats", "page_write_nanos"): "Nanoseconds spent writing encrypted pages, as decimal text.",
    ("PageObject", "id"): "Object identifier recorded in the encrypted page.",
    ("PageObject", "kind"): "Kind of logical object stored in the page.",
    ("PageObject", "payload_len"): "Encrypted object payload length in bytes.",
    ("PageInspection", "offset"): "Byte offset at which the page begins in the archive.",
    ("PageInspection", "page_id"): "Identifier stored in the page header.",
    ("PageInspection", "sequence"): "Commit sequence that wrote this page.",
    ("PageInspection", "page_size"): "Total encoded page size in bytes.",
    ("PageInspection", "encrypted_body_len"): "Encrypted body length in bytes.",
    ("PageInspection", "unused_bytes"): "Unused capacity remaining in the page.",
    ("PageInspection", "object_count"): "Number of logical objects stored in the page.",
    ("PageInspection", "objects"): "Logical objects discovered in the page.",
    ("FileInspection", "lockbox_id"): "Stable binary identifier read from the lockbox header.",
    ("FileInspection", "header_readable"): "Whether the archive header passed structural validation.",
    ("FileInspection", "key_directory_generation"): "Latest readable access-key directory generation.",
    ("FileInspection", "key_directory_copy_count"): "Number of readable redundant key-directory copies.",
    ("FileInspection", "owner_signed"): "Whether commits require an owner signature.",
    ("FileInspection", "key_slots"): "Password and contact access methods found in the header.",
    ("ProfileGeneration", "index"): "Generation number used to address this key version.",
    ("ProfileGeneration", "status"): "Lifecycle state, such as active or retired.",
    ("ProfileGeneration", "contact_fingerprint"): "Fingerprint of this generation's contact public key.",
    ("ProfileGeneration", "created_at_unix_ms"): "Creation time in Unix milliseconds.",
    ("ProfileGeneration", "retired_at_unix_ms"): "Retirement time in Unix milliseconds when retired.",
    ("ProfileGeneration", "has_retired_at"): "Whether a retirement time is present.",
    ("ProfileHistory", "name"): "Vault profile name whose generations are listed.",
    ("ProfileHistory", "active_generation"): "Generation number currently used for new access grants.",
    ("ProfileHistory", "generations"): "Active and retired contact-key generations.",
    ("KnownLockbox", "lockbox_id"): "Stable binary identifier of the remembered lockbox.",
    ("KnownLockbox", "path"): "Last known host filesystem path of the lockbox.",
    ("KnownLockbox", "last_seen_unix_ms"): "Most recent observation time in Unix milliseconds.",
    ("AccessSlotLabel", "lockbox_id"): "Lockbox whose access slot is labelled.",
    ("AccessSlotLabel", "slot_id"): "Stable identifier of the labelled access slot.",
    ("AccessSlotLabel", "name"): "Local human-readable label for the access slot.",
    ("AccessSlotLabel", "updated_at_unix_ms"): "Last label update time in Unix milliseconds.",
    ("StreamChunk", "path"): "Lockbox file path to which this byte range belongs.",
    ("StreamChunk", "file_offset"): "Logical byte offset within the file.",
    ("StreamChunk", "length"): "Logical range length in bytes.",
    ("StreamChunk", "physical_offset"): "Archive byte offset, when physical streaming is requested.",
    ("StreamChunk", "sparse"): "Whether the range represents a sparse zero-filled extent.",
    ("StreamChunk", "data"): "File bytes for a populated logical range.",
    ("RuntimeOptions", "workload_profile"): "I/O workload policy used to tune page access.",
    ("RuntimeOptions", "worker_policy"): "Worker scheduling policy and effective parallelism.",
    ("Variable", "name"): "Name used to address the variable in the lockbox.",
    ("Variable", "sensitivity"): "Whether the value is ordinary text or a protected secret.",
    ("OwnerInspection", "signed"): "Whether the lockbox requires owner-signed commits.",
    ("OwnerInspection", "fingerprint"): "Owner signing-key fingerprint when one is configured.",
    ("OwnerInspection", "has_fingerprint"): "Whether an owner fingerprint is available.",
    ("Contact", "name"): "Local address-book name of the contact.",
    ("Contact", "key"): "Serialized contact public key used to grant lockbox access.",
    ("AgentEntry", "id"): "Stable lockbox identifier for the cached key.",
    ("AgentEntry", "path"): "Host path associated with the cached lockbox key.",
    ("SleepSupport", "suspend_notifications"): "Whether the host reports impending system suspend.",
    ("SleepSupport", "sleep_inhibition"): "Whether the agent can delay sleep while handling secrets.",
    ("SleepSupport", "supported"): "Whether the host supplies enough integration for safe caching.",
    ("PlatformStatus", "supported"): "Whether a usable operating-system credential store exists.",
    ("PlatformStatus", "disabled"): "Whether the user disabled credential-store integration.",
    ("PlatformStatus", "scope"): "Application-specific scope used to isolate the stored password.",
    ("PlatformStatus", "backend"): "Operating-system credential-store backend in use.",
    ("PlatformStatus", "item"): "Credential item name used by the backend.",
    ("VaultBackupManifest", "format_version"): "Backup container format version.",
    ("VaultBackupManifest", "created_at_unix_ms"): "Backup creation time in Unix milliseconds.",
    ("VaultBackupManifest", "vault_file_name"): "Metadata-vault filename stored in the backup.",
    ("VaultBackupManifest", "vault_size"): "Encrypted vault payload size in bytes.",
    ("VaultBackupManifest", "vault_sha256"): "Lowercase SHA-256 digest of the encrypted vault payload.",
    ("ErrorDetails", "category"): "Stable error category suitable for programmatic handling.",
    ("ErrorDetails", "artifact_kind"): "Kind of archive or vault artifact involved in the failure.",
    ("ErrorDetails", "found_version"): "Format version read from the failing artifact.",
    ("ErrorDetails", "supported_version"): "Newest format version supported by this library.",
    ("ErrorDetails", "message"): "Human-readable explanation of the failure.",
    ("ErrorDetails", "guidance"): "Suggested corrective action for the caller or user.",
}


def field_description(name: str, field: str) -> str:
    """Return the user-facing meaning of one public domain field."""
    return FIELD_DESCRIPTIONS[(name, field)]


def wrapper_description(name: str) -> str:
    """Describe collection and optional result containers without transport terms."""
    explicit = {
        "LockboxEntryList": "Ordered lockbox entries selected by a list operation.",
        "StringList": "Ordered names or identifiers returned by a vault list operation.",
        "PathMoveList": "Atomic variable or form-record renames supplied to a move operation.",
        "FormFieldList": "Ordered field definitions supplied when defining a form.",
        "OptionalLockboxEntry": "The metadata found for a lockbox path, or no value when the path is absent.",
        "OptionalFormRecord": "The form record found at a lockbox path, or no value when absent.",
        "OptionalFormValue": "The requested non-secret form value, or no value when the field is absent.",
        "OptionalString": "A text lookup that distinguishes an absent value from an empty string.",
        "StringValue": "One text result returned by the native API.",
    }
    if name in explicit:
        return explicit[name]
    item = name.removesuffix("List")
    return f"Ordered {item} values returned by the corresponding list operation."
