// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: revault_bindings.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockboxEntry_Kind int32

const (
	LockboxEntry_KIND_UNSPECIFIED LockboxEntry_Kind = 0
	LockboxEntry_FILE             LockboxEntry_Kind = 1
	LockboxEntry_SYMLINK          LockboxEntry_Kind = 2
	LockboxEntry_DIRECTORY        LockboxEntry_Kind = 3
)

// Enum value maps for LockboxEntry_Kind.
var (
	LockboxEntry_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "FILE",
		2: "SYMLINK",
		3: "DIRECTORY",
	}
	LockboxEntry_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"FILE":             1,
		"SYMLINK":          2,
		"DIRECTORY":        3,
	}
)

func (x LockboxEntry_Kind) Enum() *LockboxEntry_Kind {
	p := new(LockboxEntry_Kind)
	*p = x
	return p
}

func (x LockboxEntry_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockboxEntry_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_revault_bindings_proto_enumTypes[0].Descriptor()
}

func (LockboxEntry_Kind) Type() protoreflect.EnumType {
	return &file_revault_bindings_proto_enumTypes[0]
}

func (x LockboxEntry_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockboxEntry_Kind.Descriptor instead.
func (LockboxEntry_Kind) EnumDescriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{0, 0}
}

type LockboxEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind          LockboxEntry_Kind      `protobuf:"varint,2,opt,name=kind,proto3,enum=revault.bindings.LockboxEntry_Kind" json:"kind,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Permissions   uint32                 `protobuf:"varint,4,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockboxEntry) Reset() {
	*x = LockboxEntry{}
	mi := &file_revault_bindings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockboxEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockboxEntry) ProtoMessage() {}

func (x *LockboxEntry) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockboxEntry.ProtoReflect.Descriptor instead.
func (*LockboxEntry) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{0}
}

func (x *LockboxEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LockboxEntry) GetKind() LockboxEntry_Kind {
	if x != nil {
		return x.Kind
	}
	return LockboxEntry_KIND_UNSPECIFIED
}

func (x *LockboxEntry) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *LockboxEntry) GetPermissions() uint32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

type LockboxEntryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LockboxEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockboxEntryList) Reset() {
	*x = LockboxEntryList{}
	mi := &file_revault_bindings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockboxEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockboxEntryList) ProtoMessage() {}

func (x *LockboxEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockboxEntryList.ProtoReflect.Descriptor instead.
func (*LockboxEntryList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{1}
}

func (x *LockboxEntryList) GetEntries() []*LockboxEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type OptionalLockboxEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *LockboxEntry          `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalLockboxEntry) Reset() {
	*x = OptionalLockboxEntry{}
	mi := &file_revault_bindings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalLockboxEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalLockboxEntry) ProtoMessage() {}

func (x *OptionalLockboxEntry) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalLockboxEntry.ProtoReflect.Descriptor instead.
func (*OptionalLockboxEntry) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{2}
}

func (x *OptionalLockboxEntry) GetValue() *LockboxEntry {
	if x != nil {
		return x.Value
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_revault_bindings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{3}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type PathMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMove) Reset() {
	*x = PathMove{}
	mi := &file_revault_bindings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMove) ProtoMessage() {}

func (x *PathMove) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMove.ProtoReflect.Descriptor instead.
func (*PathMove) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{4}
}

func (x *PathMove) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PathMove) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type PathMoveList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*PathMove            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMoveList) Reset() {
	*x = PathMoveList{}
	mi := &file_revault_bindings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMoveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMoveList) ProtoMessage() {}

func (x *PathMoveList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMoveList.ProtoReflect.Descriptor instead.
func (*PathMoveList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{5}
}

func (x *PathMoveList) GetValues() []*PathMove {
	if x != nil {
		return x.Values
	}
	return nil
}

type ByteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteList) Reset() {
	*x = ByteList{}
	mi := &file_revault_bindings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteList) ProtoMessage() {}

func (x *ByteList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteList.ProtoReflect.Descriptor instead.
func (*ByteList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{6}
}

func (x *ByteList) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type FormField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormField) Reset() {
	*x = FormField{}
	mi := &file_revault_bindings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormField) ProtoMessage() {}

func (x *FormField) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormField.ProtoReflect.Descriptor instead.
func (*FormField) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{7}
}

func (x *FormField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FormField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormField) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FormField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type FormFieldList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*FormField           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormFieldList) Reset() {
	*x = FormFieldList{}
	mi := &file_revault_bindings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormFieldList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormFieldList) ProtoMessage() {}

func (x *FormFieldList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormFieldList.ProtoReflect.Descriptor instead.
func (*FormFieldList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{8}
}

func (x *FormFieldList) GetValues() []*FormField {
	if x != nil {
		return x.Values
	}
	return nil
}

type FormDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Revision      uint32                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*FormField           `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormDefinition) Reset() {
	*x = FormDefinition{}
	mi := &file_revault_bindings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormDefinition) ProtoMessage() {}

func (x *FormDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormDefinition.ProtoReflect.Descriptor instead.
func (*FormDefinition) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{9}
}

func (x *FormDefinition) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *FormDefinition) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *FormDefinition) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *FormDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FormDefinition) GetFields() []*FormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FormDefinitionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*FormDefinition      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormDefinitionList) Reset() {
	*x = FormDefinitionList{}
	mi := &file_revault_bindings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormDefinitionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormDefinitionList) ProtoMessage() {}

func (x *FormDefinitionList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormDefinitionList.ProtoReflect.Descriptor instead.
func (*FormDefinitionList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{10}
}

func (x *FormDefinitionList) GetValues() []*FormDefinition {
	if x != nil {
		return x.Values
	}
	return nil
}

type FormValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldId       string                 `protobuf:"bytes,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Secret        bool                   `protobuf:"varint,5,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormValue) Reset() {
	*x = FormValue{}
	mi := &file_revault_bindings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormValue) ProtoMessage() {}

func (x *FormValue) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormValue.ProtoReflect.Descriptor instead.
func (*FormValue) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{11}
}

func (x *FormValue) GetFieldId() string {
	if x != nil {
		return x.FieldId
	}
	return ""
}

func (x *FormValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FormValue) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FormValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FormValue) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

type FormRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Path               string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeId             string                 `protobuf:"bytes,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	DefinitionAlias    string                 `protobuf:"bytes,4,opt,name=definition_alias,json=definitionAlias,proto3" json:"definition_alias,omitempty"`
	DefinitionRevision uint32                 `protobuf:"varint,5,opt,name=definition_revision,json=definitionRevision,proto3" json:"definition_revision,omitempty"`
	Values             []*FormValue           `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FormRecord) Reset() {
	*x = FormRecord{}
	mi := &file_revault_bindings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormRecord) ProtoMessage() {}

func (x *FormRecord) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormRecord.ProtoReflect.Descriptor instead.
func (*FormRecord) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{12}
}

func (x *FormRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FormRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormRecord) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *FormRecord) GetDefinitionAlias() string {
	if x != nil {
		return x.DefinitionAlias
	}
	return ""
}

func (x *FormRecord) GetDefinitionRevision() uint32 {
	if x != nil {
		return x.DefinitionRevision
	}
	return 0
}

func (x *FormRecord) GetValues() []*FormValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type FormRecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*FormRecord          `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormRecordList) Reset() {
	*x = FormRecordList{}
	mi := &file_revault_bindings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormRecordList) ProtoMessage() {}

func (x *FormRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormRecordList.ProtoReflect.Descriptor instead.
func (*FormRecordList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{13}
}

func (x *FormRecordList) GetValues() []*FormRecord {
	if x != nil {
		return x.Values
	}
	return nil
}

type OptionalFormRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *FormRecord            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalFormRecord) Reset() {
	*x = OptionalFormRecord{}
	mi := &file_revault_bindings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalFormRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalFormRecord) ProtoMessage() {}

func (x *OptionalFormRecord) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalFormRecord.ProtoReflect.Descriptor instead.
func (*OptionalFormRecord) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{14}
}

func (x *OptionalFormRecord) GetValue() *FormRecord {
	if x != nil {
		return x.Value
	}
	return nil
}

type OptionalFormValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *FormValue             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalFormValue) Reset() {
	*x = OptionalFormValue{}
	mi := &file_revault_bindings_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalFormValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalFormValue) ProtoMessage() {}

func (x *OptionalFormValue) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalFormValue.ProtoReflect.Descriptor instead.
func (*OptionalFormValue) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{15}
}

func (x *OptionalFormValue) GetValue() *FormValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type RecoveryReport struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IntactFiles         []*LockboxEntry        `protobuf:"bytes,1,rep,name=intact_files,json=intactFiles,proto3" json:"intact_files,omitempty"`
	IntactFileCount     uint64                 `protobuf:"varint,2,opt,name=intact_file_count,json=intactFileCount,proto3" json:"intact_file_count,omitempty"`
	PartialFiles        uint64                 `protobuf:"varint,3,opt,name=partial_files,json=partialFiles,proto3" json:"partial_files,omitempty"`
	CorruptRecords      uint64                 `protobuf:"varint,4,opt,name=corrupt_records,json=corruptRecords,proto3" json:"corrupt_records,omitempty"`
	TocRecovered        bool                   `protobuf:"varint,5,opt,name=toc_recovered,json=tocRecovered,proto3" json:"toc_recovered,omitempty"`
	VariablesRecovered  bool                   `protobuf:"varint,6,opt,name=variables_recovered,json=variablesRecovered,proto3" json:"variables_recovered,omitempty"`
	VariableCount       uint64                 `protobuf:"varint,7,opt,name=variable_count,json=variableCount,proto3" json:"variable_count,omitempty"`
	FormsRecovered      bool                   `protobuf:"varint,8,opt,name=forms_recovered,json=formsRecovered,proto3" json:"forms_recovered,omitempty"`
	FormDefinitionCount uint64                 `protobuf:"varint,9,opt,name=form_definition_count,json=formDefinitionCount,proto3" json:"form_definition_count,omitempty"`
	FormRecordCount     uint64                 `protobuf:"varint,10,opt,name=form_record_count,json=formRecordCount,proto3" json:"form_record_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecoveryReport) Reset() {
	*x = RecoveryReport{}
	mi := &file_revault_bindings_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryReport) ProtoMessage() {}

func (x *RecoveryReport) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryReport.ProtoReflect.Descriptor instead.
func (*RecoveryReport) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{16}
}

func (x *RecoveryReport) GetIntactFiles() []*LockboxEntry {
	if x != nil {
		return x.IntactFiles
	}
	return nil
}

func (x *RecoveryReport) GetIntactFileCount() uint64 {
	if x != nil {
		return x.IntactFileCount
	}
	return 0
}

func (x *RecoveryReport) GetPartialFiles() uint64 {
	if x != nil {
		return x.PartialFiles
	}
	return 0
}

func (x *RecoveryReport) GetCorruptRecords() uint64 {
	if x != nil {
		return x.CorruptRecords
	}
	return 0
}

func (x *RecoveryReport) GetTocRecovered() bool {
	if x != nil {
		return x.TocRecovered
	}
	return false
}

func (x *RecoveryReport) GetVariablesRecovered() bool {
	if x != nil {
		return x.VariablesRecovered
	}
	return false
}

func (x *RecoveryReport) GetVariableCount() uint64 {
	if x != nil {
		return x.VariableCount
	}
	return 0
}

func (x *RecoveryReport) GetFormsRecovered() bool {
	if x != nil {
		return x.FormsRecovered
	}
	return false
}

func (x *RecoveryReport) GetFormDefinitionCount() uint64 {
	if x != nil {
		return x.FormDefinitionCount
	}
	return 0
}

func (x *RecoveryReport) GetFormRecordCount() uint64 {
	if x != nil {
		return x.FormRecordCount
	}
	return 0
}

type KeySlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Protection    string                 `protobuf:"bytes,2,opt,name=protection,proto3" json:"protection,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySlot) Reset() {
	*x = KeySlot{}
	mi := &file_revault_bindings_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySlot) ProtoMessage() {}

func (x *KeySlot) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySlot.ProtoReflect.Descriptor instead.
func (*KeySlot) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{17}
}

func (x *KeySlot) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KeySlot) GetProtection() string {
	if x != nil {
		return x.Protection
	}
	return ""
}

func (x *KeySlot) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type KeySlotList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KeySlot             `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySlotList) Reset() {
	*x = KeySlotList{}
	mi := &file_revault_bindings_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySlotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySlotList) ProtoMessage() {}

func (x *KeySlotList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySlotList.ProtoReflect.Descriptor instead.
func (*KeySlotList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{18}
}

func (x *KeySlotList) GetValues() []*KeySlot {
	if x != nil {
		return x.Values
	}
	return nil
}

type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LimitBytes    uint64                 `protobuf:"varint,1,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	Entries       uint64                 `protobuf:"varint,3,opt,name=entries,proto3" json:"entries,omitempty"`
	Hits          uint64                 `protobuf:"varint,4,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        uint64                 `protobuf:"varint,5,opt,name=misses,proto3" json:"misses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_revault_bindings_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{19}
}

func (x *CacheStats) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *CacheStats) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *CacheStats) GetEntries() uint64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *CacheStats) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *CacheStats) GetMisses() uint64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

type ImportStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HostStatNanos     string                 `protobuf:"bytes,1,opt,name=host_stat_nanos,json=hostStatNanos,proto3" json:"host_stat_nanos,omitempty"`
	HostReadNanos     string                 `protobuf:"bytes,2,opt,name=host_read_nanos,json=hostReadNanos,proto3" json:"host_read_nanos,omitempty"`
	FramePrepareNanos string                 `protobuf:"bytes,3,opt,name=frame_prepare_nanos,json=framePrepareNanos,proto3" json:"frame_prepare_nanos,omitempty"`
	PageWriteNanos    string                 `protobuf:"bytes,4,opt,name=page_write_nanos,json=pageWriteNanos,proto3" json:"page_write_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImportStats) Reset() {
	*x = ImportStats{}
	mi := &file_revault_bindings_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportStats) ProtoMessage() {}

func (x *ImportStats) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportStats.ProtoReflect.Descriptor instead.
func (*ImportStats) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{20}
}

func (x *ImportStats) GetHostStatNanos() string {
	if x != nil {
		return x.HostStatNanos
	}
	return ""
}

func (x *ImportStats) GetHostReadNanos() string {
	if x != nil {
		return x.HostReadNanos
	}
	return ""
}

func (x *ImportStats) GetFramePrepareNanos() string {
	if x != nil {
		return x.FramePrepareNanos
	}
	return ""
}

func (x *ImportStats) GetPageWriteNanos() string {
	if x != nil {
		return x.PageWriteNanos
	}
	return ""
}

type PageObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	PayloadLen    uint64                 `protobuf:"varint,3,opt,name=payload_len,json=payloadLen,proto3" json:"payload_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageObject) Reset() {
	*x = PageObject{}
	mi := &file_revault_bindings_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageObject) ProtoMessage() {}

func (x *PageObject) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageObject.ProtoReflect.Descriptor instead.
func (*PageObject) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{21}
}

func (x *PageObject) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PageObject) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PageObject) GetPayloadLen() uint64 {
	if x != nil {
		return x.PayloadLen
	}
	return 0
}

type PageInspection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Offset           uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	PageId           uint64                 `protobuf:"varint,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Sequence         uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PageSize         uint64                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	EncryptedBodyLen uint64                 `protobuf:"varint,5,opt,name=encrypted_body_len,json=encryptedBodyLen,proto3" json:"encrypted_body_len,omitempty"`
	UnusedBytes      uint64                 `protobuf:"varint,6,opt,name=unused_bytes,json=unusedBytes,proto3" json:"unused_bytes,omitempty"`
	ObjectCount      uint64                 `protobuf:"varint,7,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	Objects          []*PageObject          `protobuf:"bytes,8,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PageInspection) Reset() {
	*x = PageInspection{}
	mi := &file_revault_bindings_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInspection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInspection) ProtoMessage() {}

func (x *PageInspection) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInspection.ProtoReflect.Descriptor instead.
func (*PageInspection) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{22}
}

func (x *PageInspection) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PageInspection) GetPageId() uint64 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *PageInspection) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PageInspection) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInspection) GetEncryptedBodyLen() uint64 {
	if x != nil {
		return x.EncryptedBodyLen
	}
	return 0
}

func (x *PageInspection) GetUnusedBytes() uint64 {
	if x != nil {
		return x.UnusedBytes
	}
	return 0
}

func (x *PageInspection) GetObjectCount() uint64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *PageInspection) GetObjects() []*PageObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type PageInspectionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*PageInspection      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInspectionList) Reset() {
	*x = PageInspectionList{}
	mi := &file_revault_bindings_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInspectionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInspectionList) ProtoMessage() {}

func (x *PageInspectionList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInspectionList.ProtoReflect.Descriptor instead.
func (*PageInspectionList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{23}
}

func (x *PageInspectionList) GetValues() []*PageInspection {
	if x != nil {
		return x.Values
	}
	return nil
}

type FileInspection struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LockboxId              []byte                 `protobuf:"bytes,1,opt,name=lockbox_id,json=lockboxId,proto3" json:"lockbox_id,omitempty"`
	HeaderReadable         bool                   `protobuf:"varint,2,opt,name=header_readable,json=headerReadable,proto3" json:"header_readable,omitempty"`
	KeyDirectoryGeneration uint64                 `protobuf:"varint,3,opt,name=key_directory_generation,json=keyDirectoryGeneration,proto3" json:"key_directory_generation,omitempty"`
	KeyDirectoryCopyCount  uint64                 `protobuf:"varint,4,opt,name=key_directory_copy_count,json=keyDirectoryCopyCount,proto3" json:"key_directory_copy_count,omitempty"`
	OwnerSigned            bool                   `protobuf:"varint,5,opt,name=owner_signed,json=ownerSigned,proto3" json:"owner_signed,omitempty"`
	KeySlots               []*KeySlot             `protobuf:"bytes,6,rep,name=key_slots,json=keySlots,proto3" json:"key_slots,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileInspection) Reset() {
	*x = FileInspection{}
	mi := &file_revault_bindings_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInspection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInspection) ProtoMessage() {}

func (x *FileInspection) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInspection.ProtoReflect.Descriptor instead.
func (*FileInspection) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{24}
}

func (x *FileInspection) GetLockboxId() []byte {
	if x != nil {
		return x.LockboxId
	}
	return nil
}

func (x *FileInspection) GetHeaderReadable() bool {
	if x != nil {
		return x.HeaderReadable
	}
	return false
}

func (x *FileInspection) GetKeyDirectoryGeneration() uint64 {
	if x != nil {
		return x.KeyDirectoryGeneration
	}
	return 0
}

func (x *FileInspection) GetKeyDirectoryCopyCount() uint64 {
	if x != nil {
		return x.KeyDirectoryCopyCount
	}
	return 0
}

func (x *FileInspection) GetOwnerSigned() bool {
	if x != nil {
		return x.OwnerSigned
	}
	return false
}

func (x *FileInspection) GetKeySlots() []*KeySlot {
	if x != nil {
		return x.KeySlots
	}
	return nil
}

type ProfileGeneration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ContactFingerprint []byte                 `protobuf:"bytes,3,opt,name=contact_fingerprint,json=contactFingerprint,proto3" json:"contact_fingerprint,omitempty"`
	CreatedAtUnixMs    uint64                 `protobuf:"varint,4,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	RetiredAtUnixMs    uint64                 `protobuf:"varint,5,opt,name=retired_at_unix_ms,json=retiredAtUnixMs,proto3" json:"retired_at_unix_ms,omitempty"`
	HasRetiredAt       bool                   `protobuf:"varint,6,opt,name=has_retired_at,json=hasRetiredAt,proto3" json:"has_retired_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProfileGeneration) Reset() {
	*x = ProfileGeneration{}
	mi := &file_revault_bindings_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGeneration) ProtoMessage() {}

func (x *ProfileGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileGeneration.ProtoReflect.Descriptor instead.
func (*ProfileGeneration) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{25}
}

func (x *ProfileGeneration) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProfileGeneration) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProfileGeneration) GetContactFingerprint() []byte {
	if x != nil {
		return x.ContactFingerprint
	}
	return nil
}

func (x *ProfileGeneration) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *ProfileGeneration) GetRetiredAtUnixMs() uint64 {
	if x != nil {
		return x.RetiredAtUnixMs
	}
	return 0
}

func (x *ProfileGeneration) GetHasRetiredAt() bool {
	if x != nil {
		return x.HasRetiredAt
	}
	return false
}

type ProfileHistory struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActiveGeneration uint32                 `protobuf:"varint,2,opt,name=active_generation,json=activeGeneration,proto3" json:"active_generation,omitempty"`
	Generations      []*ProfileGeneration   `protobuf:"bytes,3,rep,name=generations,proto3" json:"generations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProfileHistory) Reset() {
	*x = ProfileHistory{}
	mi := &file_revault_bindings_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileHistory) ProtoMessage() {}

func (x *ProfileHistory) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileHistory.ProtoReflect.Descriptor instead.
func (*ProfileHistory) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{26}
}

func (x *ProfileHistory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileHistory) GetActiveGeneration() uint32 {
	if x != nil {
		return x.ActiveGeneration
	}
	return 0
}

func (x *ProfileHistory) GetGenerations() []*ProfileGeneration {
	if x != nil {
		return x.Generations
	}
	return nil
}

type KnownLockbox struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LockboxId      []byte                 `protobuf:"bytes,1,opt,name=lockbox_id,json=lockboxId,proto3" json:"lockbox_id,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	LastSeenUnixMs uint64                 `protobuf:"varint,3,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KnownLockbox) Reset() {
	*x = KnownLockbox{}
	mi := &file_revault_bindings_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLockbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLockbox) ProtoMessage() {}

func (x *KnownLockbox) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLockbox.ProtoReflect.Descriptor instead.
func (*KnownLockbox) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{27}
}

func (x *KnownLockbox) GetLockboxId() []byte {
	if x != nil {
		return x.LockboxId
	}
	return nil
}

func (x *KnownLockbox) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KnownLockbox) GetLastSeenUnixMs() uint64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type KnownLockboxList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KnownLockbox        `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLockboxList) Reset() {
	*x = KnownLockboxList{}
	mi := &file_revault_bindings_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLockboxList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLockboxList) ProtoMessage() {}

func (x *KnownLockboxList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLockboxList.ProtoReflect.Descriptor instead.
func (*KnownLockboxList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{28}
}

func (x *KnownLockboxList) GetValues() []*KnownLockbox {
	if x != nil {
		return x.Values
	}
	return nil
}

type AccessSlotLabel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LockboxId       []byte                 `protobuf:"bytes,1,opt,name=lockbox_id,json=lockboxId,proto3" json:"lockbox_id,omitempty"`
	SlotId          uint64                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAtUnixMs uint64                 `protobuf:"varint,4,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessSlotLabel) Reset() {
	*x = AccessSlotLabel{}
	mi := &file_revault_bindings_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSlotLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSlotLabel) ProtoMessage() {}

func (x *AccessSlotLabel) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSlotLabel.ProtoReflect.Descriptor instead.
func (*AccessSlotLabel) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{29}
}

func (x *AccessSlotLabel) GetLockboxId() []byte {
	if x != nil {
		return x.LockboxId
	}
	return nil
}

func (x *AccessSlotLabel) GetSlotId() uint64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AccessSlotLabel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessSlotLabel) GetUpdatedAtUnixMs() uint64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type AccessSlotLabelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AccessSlotLabel     `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessSlotLabelList) Reset() {
	*x = AccessSlotLabelList{}
	mi := &file_revault_bindings_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSlotLabelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSlotLabelList) ProtoMessage() {}

func (x *AccessSlotLabelList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSlotLabelList.ProtoReflect.Descriptor instead.
func (*AccessSlotLabelList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{30}
}

func (x *AccessSlotLabelList) GetValues() []*AccessSlotLabel {
	if x != nil {
		return x.Values
	}
	return nil
}

type StreamChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FileOffset     uint64                 `protobuf:"varint,2,opt,name=file_offset,json=fileOffset,proto3" json:"file_offset,omitempty"`
	Length         uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	PhysicalOffset uint64                 `protobuf:"varint,4,opt,name=physical_offset,json=physicalOffset,proto3" json:"physical_offset,omitempty"`
	Sparse         bool                   `protobuf:"varint,5,opt,name=sparse,proto3" json:"sparse,omitempty"`
	Data           []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_revault_bindings_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{31}
}

func (x *StreamChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamChunk) GetFileOffset() uint64 {
	if x != nil {
		return x.FileOffset
	}
	return 0
}

func (x *StreamChunk) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StreamChunk) GetPhysicalOffset() uint64 {
	if x != nil {
		return x.PhysicalOffset
	}
	return 0
}

func (x *StreamChunk) GetSparse() bool {
	if x != nil {
		return x.Sparse
	}
	return false
}

func (x *StreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamChunkList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*StreamChunk         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunkList) Reset() {
	*x = StreamChunkList{}
	mi := &file_revault_bindings_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunkList) ProtoMessage() {}

func (x *StreamChunkList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunkList.ProtoReflect.Descriptor instead.
func (*StreamChunkList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{32}
}

func (x *StreamChunkList) GetValues() []*StreamChunk {
	if x != nil {
		return x.Values
	}
	return nil
}

type RuntimeOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkloadProfile string                 `protobuf:"bytes,1,opt,name=workload_profile,json=workloadProfile,proto3" json:"workload_profile,omitempty"`
	WorkerPolicy    string                 `protobuf:"bytes,2,opt,name=worker_policy,json=workerPolicy,proto3" json:"worker_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeOptions) Reset() {
	*x = RuntimeOptions{}
	mi := &file_revault_bindings_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeOptions) ProtoMessage() {}

func (x *RuntimeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeOptions.ProtoReflect.Descriptor instead.
func (*RuntimeOptions) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{33}
}

func (x *RuntimeOptions) GetWorkloadProfile() string {
	if x != nil {
		return x.WorkloadProfile
	}
	return ""
}

func (x *RuntimeOptions) GetWorkerPolicy() string {
	if x != nil {
		return x.WorkerPolicy
	}
	return ""
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sensitivity   string                 `protobuf:"bytes,2,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_revault_bindings_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{34}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetSensitivity() string {
	if x != nil {
		return x.Sensitivity
	}
	return ""
}

type VariableList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Variable            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableList) Reset() {
	*x = VariableList{}
	mi := &file_revault_bindings_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableList) ProtoMessage() {}

func (x *VariableList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableList.ProtoReflect.Descriptor instead.
func (*VariableList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{35}
}

func (x *VariableList) GetValues() []*Variable {
	if x != nil {
		return x.Values
	}
	return nil
}

type OptionalString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	mi := &file_revault_bindings_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{36}
}

func (x *OptionalString) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OwnerInspection struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Signed         bool                   `protobuf:"varint,1,opt,name=signed,proto3" json:"signed,omitempty"`
	Fingerprint    string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	HasFingerprint bool                   `protobuf:"varint,3,opt,name=has_fingerprint,json=hasFingerprint,proto3" json:"has_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OwnerInspection) Reset() {
	*x = OwnerInspection{}
	mi := &file_revault_bindings_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerInspection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerInspection) ProtoMessage() {}

func (x *OwnerInspection) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerInspection.ProtoReflect.Descriptor instead.
func (*OwnerInspection) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{37}
}

func (x *OwnerInspection) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *OwnerInspection) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *OwnerInspection) GetHasFingerprint() bool {
	if x != nil {
		return x.HasFingerprint
	}
	return false
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_revault_bindings_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{38}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ContactList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Contact             `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactList) Reset() {
	*x = ContactList{}
	mi := &file_revault_bindings_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactList) ProtoMessage() {}

func (x *ContactList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactList.ProtoReflect.Descriptor instead.
func (*ContactList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{39}
}

func (x *ContactList) GetValues() []*Contact {
	if x != nil {
		return x.Values
	}
	return nil
}

type ProfileHistoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ProfileHistory      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileHistoryList) Reset() {
	*x = ProfileHistoryList{}
	mi := &file_revault_bindings_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileHistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileHistoryList) ProtoMessage() {}

func (x *ProfileHistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileHistoryList.ProtoReflect.Descriptor instead.
func (*ProfileHistoryList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{40}
}

func (x *ProfileHistoryList) GetValues() []*ProfileHistory {
	if x != nil {
		return x.Values
	}
	return nil
}

type AgentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEntry) Reset() {
	*x = AgentEntry{}
	mi := &file_revault_bindings_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEntry) ProtoMessage() {}

func (x *AgentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEntry.ProtoReflect.Descriptor instead.
func (*AgentEntry) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{41}
}

func (x *AgentEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AgentEntryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AgentEntry          `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEntryList) Reset() {
	*x = AgentEntryList{}
	mi := &file_revault_bindings_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEntryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEntryList) ProtoMessage() {}

func (x *AgentEntryList) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEntryList.ProtoReflect.Descriptor instead.
func (*AgentEntryList) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{42}
}

func (x *AgentEntryList) GetValues() []*AgentEntry {
	if x != nil {
		return x.Values
	}
	return nil
}

type SleepSupport struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SuspendNotifications bool                   `protobuf:"varint,1,opt,name=suspend_notifications,json=suspendNotifications,proto3" json:"suspend_notifications,omitempty"`
	SleepInhibition      bool                   `protobuf:"varint,2,opt,name=sleep_inhibition,json=sleepInhibition,proto3" json:"sleep_inhibition,omitempty"`
	Supported            bool                   `protobuf:"varint,3,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SleepSupport) Reset() {
	*x = SleepSupport{}
	mi := &file_revault_bindings_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepSupport) ProtoMessage() {}

func (x *SleepSupport) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepSupport.ProtoReflect.Descriptor instead.
func (*SleepSupport) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{43}
}

func (x *SleepSupport) GetSuspendNotifications() bool {
	if x != nil {
		return x.SuspendNotifications
	}
	return false
}

func (x *SleepSupport) GetSleepInhibition() bool {
	if x != nil {
		return x.SleepInhibition
	}
	return false
}

func (x *SleepSupport) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type PlatformStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	Disabled      bool                   `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	Item          string                 `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformStatus) Reset() {
	*x = PlatformStatus{}
	mi := &file_revault_bindings_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStatus) ProtoMessage() {}

func (x *PlatformStatus) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStatus.ProtoReflect.Descriptor instead.
func (*PlatformStatus) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{44}
}

func (x *PlatformStatus) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *PlatformStatus) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *PlatformStatus) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PlatformStatus) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *PlatformStatus) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type StringValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValue) Reset() {
	*x = StringValue{}
	mi := &file_revault_bindings_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValue) ProtoMessage() {}

func (x *StringValue) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValue.ProtoReflect.Descriptor instead.
func (*StringValue) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{45}
}

func (x *StringValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VaultBackupManifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion   uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	CreatedAtUnixMs uint64                 `protobuf:"varint,2,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	VaultFileName   string                 `protobuf:"bytes,3,opt,name=vault_file_name,json=vaultFileName,proto3" json:"vault_file_name,omitempty"`
	VaultSize       uint64                 `protobuf:"varint,4,opt,name=vault_size,json=vaultSize,proto3" json:"vault_size,omitempty"`
	VaultSha256     string                 `protobuf:"bytes,5,opt,name=vault_sha256,json=vaultSha256,proto3" json:"vault_sha256,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VaultBackupManifest) Reset() {
	*x = VaultBackupManifest{}
	mi := &file_revault_bindings_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultBackupManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultBackupManifest) ProtoMessage() {}

func (x *VaultBackupManifest) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultBackupManifest.ProtoReflect.Descriptor instead.
func (*VaultBackupManifest) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{46}
}

func (x *VaultBackupManifest) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *VaultBackupManifest) GetCreatedAtUnixMs() uint64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *VaultBackupManifest) GetVaultFileName() string {
	if x != nil {
		return x.VaultFileName
	}
	return ""
}

func (x *VaultBackupManifest) GetVaultSize() uint64 {
	if x != nil {
		return x.VaultSize
	}
	return 0
}

func (x *VaultBackupManifest) GetVaultSha256() string {
	if x != nil {
		return x.VaultSha256
	}
	return ""
}

type ErrorDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Category         string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	ArtifactKind     string                 `protobuf:"bytes,2,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	FoundVersion     uint32                 `protobuf:"varint,3,opt,name=found_version,json=foundVersion,proto3" json:"found_version,omitempty"`
	SupportedVersion uint32                 `protobuf:"varint,4,opt,name=supported_version,json=supportedVersion,proto3" json:"supported_version,omitempty"`
	Message          string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Guidance         string                 `protobuf:"bytes,6,opt,name=guidance,proto3" json:"guidance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_revault_bindings_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_revault_bindings_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_revault_bindings_proto_rawDescGZIP(), []int{47}
}

func (x *ErrorDetails) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ErrorDetails) GetArtifactKind() string {
	if x != nil {
		return x.ArtifactKind
	}
	return ""
}

func (x *ErrorDetails) GetFoundVersion() uint32 {
	if x != nil {
		return x.FoundVersion
	}
	return 0
}

func (x *ErrorDetails) GetSupportedVersion() uint32 {
	if x != nil {
		return x.SupportedVersion
	}
	return 0
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetGuidance() string {
	if x != nil {
		return x.Guidance
	}
	return ""
}

var File_revault_bindings_proto protoreflect.FileDescriptor

const file_revault_bindings_proto_rawDesc = "" +
	"\n" +
	"\x16revault_bindings.proto\x12\x10revault.bindings\"\xd9\x01\n" +
	"\fLockboxEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x127\n" +
	"\x04kind\x18\x02 \x01(\x0e2#.revault.bindings.LockboxEntry.KindR\x04kind\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12 \n" +
	"\vpermissions\x18\x04 \x01(\rR\vpermissions\"B\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FILE\x10\x01\x12\v\n" +
	"\aSYMLINK\x10\x02\x12\r\n" +
	"\tDIRECTORY\x10\x03\"L\n" +
	"\x10LockboxEntryList\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.revault.bindings.LockboxEntryR\aentries\"L\n" +
	"\x14OptionalLockboxEntry\x124\n" +
	"\x05value\x18\x01 \x01(\v2\x1e.revault.bindings.LockboxEntryR\x05value\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"D\n" +
	"\bPathMove\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"B\n" +
	"\fPathMoveList\x122\n" +
	"\x06values\x18\x01 \x03(\v2\x1a.revault.bindings.PathMoveR\x06values\"\"\n" +
	"\bByteList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"a\n" +
	"\tFormField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"D\n" +
	"\rFormFieldList\x123\n" +
	"\x06values\x18\x01 \x03(\v2\x1b.revault.bindings.FormFieldR\x06values\"\xc6\x01\n" +
	"\x0eFormDefinition\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\rR\brevision\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x123\n" +
	"\x06fields\x18\x06 \x03(\v2\x1b.revault.bindings.FormFieldR\x06fields\"N\n" +
	"\x12FormDefinitionList\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .revault.bindings.FormDefinitionR\x06values\"~\n" +
	"\tFormValue\x12\x19\n" +
	"\bfield_id\x18\x01 \x01(\tR\afieldId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\bR\x06secret\"\xde\x01\n" +
	"\n" +
	"FormRecord\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\tR\x06typeId\x12)\n" +
	"\x10definition_alias\x18\x04 \x01(\tR\x0fdefinitionAlias\x12/\n" +
	"\x13definition_revision\x18\x05 \x01(\rR\x12definitionRevision\x123\n" +
	"\x06values\x18\x06 \x03(\v2\x1b.revault.bindings.FormValueR\x06values\"F\n" +
	"\x0eFormRecordList\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.revault.bindings.FormRecordR\x06values\"H\n" +
	"\x12OptionalFormRecord\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.revault.bindings.FormRecordR\x05value\"F\n" +
	"\x11OptionalFormValue\x121\n" +
	"\x05value\x18\x01 \x01(\v2\x1b.revault.bindings.FormValueR\x05value\"\xd3\x03\n" +
	"\x0eRecoveryReport\x12A\n" +
	"\fintact_files\x18\x01 \x03(\v2\x1e.revault.bindings.LockboxEntryR\vintactFiles\x12*\n" +
	"\x11intact_file_count\x18\x02 \x01(\x04R\x0fintactFileCount\x12#\n" +
	"\rpartial_files\x18\x03 \x01(\x04R\fpartialFiles\x12'\n" +
	"\x0fcorrupt_records\x18\x04 \x01(\x04R\x0ecorruptRecords\x12#\n" +
	"\rtoc_recovered\x18\x05 \x01(\bR\ftocRecovered\x12/\n" +
	"\x13variables_recovered\x18\x06 \x01(\bR\x12variablesRecovered\x12%\n" +
	"\x0evariable_count\x18\a \x01(\x04R\rvariableCount\x12'\n" +
	"\x0fforms_recovered\x18\b \x01(\bR\x0eformsRecovered\x122\n" +
	"\x15form_definition_count\x18\t \x01(\x04R\x13formDefinitionCount\x12*\n" +
	"\x11form_record_count\x18\n" +
	" \x01(\x04R\x0fformRecordCount\"W\n" +
	"\aKeySlot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1e\n" +
	"\n" +
	"protection\x18\x02 \x01(\tR\n" +
	"protection\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\"@\n" +
	"\vKeySlotList\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.revault.bindings.KeySlotR\x06values\"\x92\x01\n" +
	"\n" +
	"CacheStats\x12\x1f\n" +
	"\vlimit_bytes\x18\x01 \x01(\x04R\n" +
	"limitBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12\x18\n" +
	"\aentries\x18\x03 \x01(\x04R\aentries\x12\x12\n" +
	"\x04hits\x18\x04 \x01(\x04R\x04hits\x12\x16\n" +
	"\x06misses\x18\x05 \x01(\x04R\x06misses\"\xb7\x01\n" +
	"\vImportStats\x12&\n" +
	"\x0fhost_stat_nanos\x18\x01 \x01(\tR\rhostStatNanos\x12&\n" +
	"\x0fhost_read_nanos\x18\x02 \x01(\tR\rhostReadNanos\x12.\n" +
	"\x13frame_prepare_nanos\x18\x03 \x01(\tR\x11framePrepareNanos\x12(\n" +
	"\x10page_write_nanos\x18\x04 \x01(\tR\x0epageWriteNanos\"Q\n" +
	"\n" +
	"PageObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vpayload_len\x18\x03 \x01(\x04R\n" +
	"payloadLen\"\xa6\x02\n" +
	"\x0ePageInspection\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\x04R\x06pageId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x04R\bpageSize\x12,\n" +
	"\x12encrypted_body_len\x18\x05 \x01(\x04R\x10encryptedBodyLen\x12!\n" +
	"\funused_bytes\x18\x06 \x01(\x04R\vunusedBytes\x12!\n" +
	"\fobject_count\x18\a \x01(\x04R\vobjectCount\x126\n" +
	"\aobjects\x18\b \x03(\v2\x1c.revault.bindings.PageObjectR\aobjects\"N\n" +
	"\x12PageInspectionList\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .revault.bindings.PageInspectionR\x06values\"\xa6\x02\n" +
	"\x0eFileInspection\x12\x1d\n" +
	"\n" +
	"lockbox_id\x18\x01 \x01(\fR\tlockboxId\x12'\n" +
	"\x0fheader_readable\x18\x02 \x01(\bR\x0eheaderReadable\x128\n" +
	"\x18key_directory_generation\x18\x03 \x01(\x04R\x16keyDirectoryGeneration\x127\n" +
	"\x18key_directory_copy_count\x18\x04 \x01(\x04R\x15keyDirectoryCopyCount\x12!\n" +
	"\fowner_signed\x18\x05 \x01(\bR\vownerSigned\x126\n" +
	"\tkey_slots\x18\x06 \x03(\v2\x19.revault.bindings.KeySlotR\bkeySlots\"\xf2\x01\n" +
	"\x11ProfileGeneration\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x13contact_fingerprint\x18\x03 \x01(\fR\x12contactFingerprint\x12+\n" +
	"\x12created_at_unix_ms\x18\x04 \x01(\x04R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12retired_at_unix_ms\x18\x05 \x01(\x04R\x0fretiredAtUnixMs\x12$\n" +
	"\x0ehas_retired_at\x18\x06 \x01(\bR\fhasRetiredAt\"\x98\x01\n" +
	"\x0eProfileHistory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x11active_generation\x18\x02 \x01(\rR\x10activeGeneration\x12E\n" +
	"\vgenerations\x18\x03 \x03(\v2#.revault.bindings.ProfileGenerationR\vgenerations\"l\n" +
	"\fKnownLockbox\x12\x1d\n" +
	"\n" +
	"lockbox_id\x18\x01 \x01(\fR\tlockboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12)\n" +
	"\x11last_seen_unix_ms\x18\x03 \x01(\x04R\x0elastSeenUnixMs\"J\n" +
	"\x10KnownLockboxList\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.revault.bindings.KnownLockboxR\x06values\"\x8a\x01\n" +
	"\x0fAccessSlotLabel\x12\x1d\n" +
	"\n" +
	"lockbox_id\x18\x01 \x01(\fR\tlockboxId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x04R\x06slotId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x12updated_at_unix_ms\x18\x04 \x01(\x04R\x0fupdatedAtUnixMs\"P\n" +
	"\x13AccessSlotLabelList\x129\n" +
	"\x06values\x18\x01 \x03(\v2!.revault.bindings.AccessSlotLabelR\x06values\"\xaf\x01\n" +
	"\vStreamChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vfile_offset\x18\x02 \x01(\x04R\n" +
	"fileOffset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12'\n" +
	"\x0fphysical_offset\x18\x04 \x01(\x04R\x0ephysicalOffset\x12\x16\n" +
	"\x06sparse\x18\x05 \x01(\bR\x06sparse\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"H\n" +
	"\x0fStreamChunkList\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.revault.bindings.StreamChunkR\x06values\"`\n" +
	"\x0eRuntimeOptions\x12)\n" +
	"\x10workload_profile\x18\x01 \x01(\tR\x0fworkloadProfile\x12#\n" +
	"\rworker_policy\x18\x02 \x01(\tR\fworkerPolicy\"@\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vsensitivity\x18\x02 \x01(\tR\vsensitivity\"B\n" +
	"\fVariableList\x122\n" +
	"\x06values\x18\x01 \x03(\v2\x1a.revault.bindings.VariableR\x06values\"@\n" +
	"\x0eOptionalString\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"t\n" +
	"\x0fOwnerInspection\x12\x16\n" +
	"\x06signed\x18\x01 \x01(\bR\x06signed\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12'\n" +
	"\x0fhas_fingerprint\x18\x03 \x01(\bR\x0ehasFingerprint\"/\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"@\n" +
	"\vContactList\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.revault.bindings.ContactR\x06values\"N\n" +
	"\x12ProfileHistoryList\x128\n" +
	"\x06values\x18\x01 \x03(\v2 .revault.bindings.ProfileHistoryR\x06values\"0\n" +
	"\n" +
	"AgentEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"F\n" +
	"\x0eAgentEntryList\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.revault.bindings.AgentEntryR\x06values\"\x8c\x01\n" +
	"\fSleepSupport\x123\n" +
	"\x15suspend_notifications\x18\x01 \x01(\bR\x14suspendNotifications\x12)\n" +
	"\x10sleep_inhibition\x18\x02 \x01(\bR\x0fsleepInhibition\x12\x1c\n" +
	"\tsupported\x18\x03 \x01(\bR\tsupported\"\x8e\x01\n" +
	"\x0ePlatformStatus\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\x12\x12\n" +
	"\x04item\x18\x05 \x01(\tR\x04item\"#\n" +
	"\vStringValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xd3\x01\n" +
	"\x13VaultBackupManifest\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12+\n" +
	"\x12created_at_unix_ms\x18\x02 \x01(\x04R\x0fcreatedAtUnixMs\x12&\n" +
	"\x0fvault_file_name\x18\x03 \x01(\tR\rvaultFileName\x12\x1d\n" +
	"\n" +
	"vault_size\x18\x04 \x01(\x04R\tvaultSize\x12!\n" +
	"\fvault_sha256\x18\x05 \x01(\tR\vvaultSha256\"\xd7\x01\n" +
	"\fErrorDetails\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12#\n" +
	"\rartifact_kind\x18\x02 \x01(\tR\fartifactKind\x12#\n" +
	"\rfound_version\x18\x03 \x01(\rR\ffoundVersion\x12+\n" +
	"\x11supported_version\x18\x04 \x01(\rR\x10supportedVersion\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\bguidance\x18\x06 \x01(\tR\bguidanceB,Z*github.com/onepub-dev/revault-api/messagesb\x06proto3"

var (
	file_revault_bindings_proto_rawDescOnce sync.Once
	file_revault_bindings_proto_rawDescData []byte
)

func file_revault_bindings_proto_rawDescGZIP() []byte {
	file_revault_bindings_proto_rawDescOnce.Do(func() {
		file_revault_bindings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revault_bindings_proto_rawDesc), len(file_revault_bindings_proto_rawDesc)))
	})
	return file_revault_bindings_proto_rawDescData
}

var file_revault_bindings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_revault_bindings_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_revault_bindings_proto_goTypes = []any{
	(LockboxEntry_Kind)(0),       // 0: revault.bindings.LockboxEntry.Kind
	(*LockboxEntry)(nil),         // 1: revault.bindings.LockboxEntry
	(*LockboxEntryList)(nil),     // 2: revault.bindings.LockboxEntryList
	(*OptionalLockboxEntry)(nil), // 3: revault.bindings.OptionalLockboxEntry
	(*StringList)(nil),           // 4: revault.bindings.StringList
	(*PathMove)(nil),             // 5: revault.bindings.PathMove
	(*PathMoveList)(nil),         // 6: revault.bindings.PathMoveList
	(*ByteList)(nil),             // 7: revault.bindings.ByteList
	(*FormField)(nil),            // 8: revault.bindings.FormField
	(*FormFieldList)(nil),        // 9: revault.bindings.FormFieldList
	(*FormDefinition)(nil),       // 10: revault.bindings.FormDefinition
	(*FormDefinitionList)(nil),   // 11: revault.bindings.FormDefinitionList
	(*FormValue)(nil),            // 12: revault.bindings.FormValue
	(*FormRecord)(nil),           // 13: revault.bindings.FormRecord
	(*FormRecordList)(nil),       // 14: revault.bindings.FormRecordList
	(*OptionalFormRecord)(nil),   // 15: revault.bindings.OptionalFormRecord
	(*OptionalFormValue)(nil),    // 16: revault.bindings.OptionalFormValue
	(*RecoveryReport)(nil),       // 17: revault.bindings.RecoveryReport
	(*KeySlot)(nil),              // 18: revault.bindings.KeySlot
	(*KeySlotList)(nil),          // 19: revault.bindings.KeySlotList
	(*CacheStats)(nil),           // 20: revault.bindings.CacheStats
	(*ImportStats)(nil),          // 21: revault.bindings.ImportStats
	(*PageObject)(nil),           // 22: revault.bindings.PageObject
	(*PageInspection)(nil),       // 23: revault.bindings.PageInspection
	(*PageInspectionList)(nil),   // 24: revault.bindings.PageInspectionList
	(*FileInspection)(nil),       // 25: revault.bindings.FileInspection
	(*ProfileGeneration)(nil),    // 26: revault.bindings.ProfileGeneration
	(*ProfileHistory)(nil),       // 27: revault.bindings.ProfileHistory
	(*KnownLockbox)(nil),         // 28: revault.bindings.KnownLockbox
	(*KnownLockboxList)(nil),     // 29: revault.bindings.KnownLockboxList
	(*AccessSlotLabel)(nil),      // 30: revault.bindings.AccessSlotLabel
	(*AccessSlotLabelList)(nil),  // 31: revault.bindings.AccessSlotLabelList
	(*StreamChunk)(nil),          // 32: revault.bindings.StreamChunk
	(*StreamChunkList)(nil),      // 33: revault.bindings.StreamChunkList
	(*RuntimeOptions)(nil),       // 34: revault.bindings.RuntimeOptions
	(*Variable)(nil),             // 35: revault.bindings.Variable
	(*VariableList)(nil),         // 36: revault.bindings.VariableList
	(*OptionalString)(nil),       // 37: revault.bindings.OptionalString
	(*OwnerInspection)(nil),      // 38: revault.bindings.OwnerInspection
	(*Contact)(nil),              // 39: revault.bindings.Contact
	(*ContactList)(nil),          // 40: revault.bindings.ContactList
	(*ProfileHistoryList)(nil),   // 41: revault.bindings.ProfileHistoryList
	(*AgentEntry)(nil),           // 42: revault.bindings.AgentEntry
	(*AgentEntryList)(nil),       // 43: revault.bindings.AgentEntryList
	(*SleepSupport)(nil),         // 44: revault.bindings.SleepSupport
	(*PlatformStatus)(nil),       // 45: revault.bindings.PlatformStatus
	(*StringValue)(nil),          // 46: revault.bindings.StringValue
	(*VaultBackupManifest)(nil),  // 47: revault.bindings.VaultBackupManifest
	(*ErrorDetails)(nil),         // 48: revault.bindings.ErrorDetails
}
var file_revault_bindings_proto_depIdxs = []int32{
	0,  // 0: revault.bindings.LockboxEntry.kind:type_name -> revault.bindings.LockboxEntry.Kind
	1,  // 1: revault.bindings.LockboxEntryList.entries:type_name -> revault.bindings.LockboxEntry
	1,  // 2: revault.bindings.OptionalLockboxEntry.value:type_name -> revault.bindings.LockboxEntry
	5,  // 3: revault.bindings.PathMoveList.values:type_name -> revault.bindings.PathMove
	8,  // 4: revault.bindings.FormFieldList.values:type_name -> revault.bindings.FormField
	8,  // 5: revault.bindings.FormDefinition.fields:type_name -> revault.bindings.FormField
	10, // 6: revault.bindings.FormDefinitionList.values:type_name -> revault.bindings.FormDefinition
	12, // 7: revault.bindings.FormRecord.values:type_name -> revault.bindings.FormValue
	13, // 8: revault.bindings.FormRecordList.values:type_name -> revault.bindings.FormRecord
	13, // 9: revault.bindings.OptionalFormRecord.value:type_name -> revault.bindings.FormRecord
	12, // 10: revault.bindings.OptionalFormValue.value:type_name -> revault.bindings.FormValue
	1,  // 11: revault.bindings.RecoveryReport.intact_files:type_name -> revault.bindings.LockboxEntry
	18, // 12: revault.bindings.KeySlotList.values:type_name -> revault.bindings.KeySlot
	22, // 13: revault.bindings.PageInspection.objects:type_name -> revault.bindings.PageObject
	23, // 14: revault.bindings.PageInspectionList.values:type_name -> revault.bindings.PageInspection
	18, // 15: revault.bindings.FileInspection.key_slots:type_name -> revault.bindings.KeySlot
	26, // 16: revault.bindings.ProfileHistory.generations:type_name -> revault.bindings.ProfileGeneration
	28, // 17: revault.bindings.KnownLockboxList.values:type_name -> revault.bindings.KnownLockbox
	30, // 18: revault.bindings.AccessSlotLabelList.values:type_name -> revault.bindings.AccessSlotLabel
	32, // 19: revault.bindings.StreamChunkList.values:type_name -> revault.bindings.StreamChunk
	35, // 20: revault.bindings.VariableList.values:type_name -> revault.bindings.Variable
	39, // 21: revault.bindings.ContactList.values:type_name -> revault.bindings.Contact
	27, // 22: revault.bindings.ProfileHistoryList.values:type_name -> revault.bindings.ProfileHistory
	42, // 23: revault.bindings.AgentEntryList.values:type_name -> revault.bindings.AgentEntry
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_revault_bindings_proto_init() }
func file_revault_bindings_proto_init() {
	if File_revault_bindings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revault_bindings_proto_rawDesc), len(file_revault_bindings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_revault_bindings_proto_goTypes,
		DependencyIndexes: file_revault_bindings_proto_depIdxs,
		EnumInfos:         file_revault_bindings_proto_enumTypes,
		MessageInfos:      file_revault_bindings_proto_msgTypes,
	}.Build()
	File_revault_bindings_proto = out.File
	file_revault_bindings_proto_goTypes = nil
	file_revault_bindings_proto_depIdxs = nil
}
