// Generated by bindings/flatbuffers/generate_dart_models.py.

import 'dart:typed_data';
import 'generated/flatbuffers/revault_bindings_revault.internal_generated.dart' as fb;

/// The kind of filesystem object represented by a [LockboxEntry].
enum LockboxEntryKind {
  /// No recognized filesystem kind was reported.
  unspecified,
  /// A regular file containing bytes.
  file,
  /// A symbolic link containing a target path.
  symlink,
  /// A directory that may contain other entries.
  directory,
}

/// Metadata for one file, directory, or symbolic link stored at a lockbox path.
final class LockboxEntry {
  final fb.LockboxEntry? _view;
  final String? _path;
  /// Absolute lockbox path of the stored entry.
  late final String path = _view == null ? _path! : _view.path ?? '';
  final LockboxEntryKind? _kind;
  /// Filesystem kind: file, directory, or symbolic link.
  late final LockboxEntryKind kind = _view == null ? _kind! : LockboxEntryKind.values[_view.kind.value];
  final int? _length;
  /// Logical file length in bytes; zero for directories.
  late final int length = _view == null ? _length! : _view.length;
  final int? _permissions;
  /// Portable Unix permission bits stored with the entry.
  late final int permissions = _view == null ? _permissions! : _view.permissions;

  /// Creates a LockboxEntry value for an API input or application-owned copy.
  LockboxEntry({String path = '', LockboxEntryKind kind = LockboxEntryKind.unspecified, int length = 0, int permissions = 0}) : _view = null, _path = path, _kind = kind, _length = length, _permissions = permissions;
  LockboxEntry._from(this._view) : _path = null, _kind = null, _length = null, _permissions = null;
}

/// A source and destination pair used to rename a variable or form record atomically.
final class PathMove {
  final fb.PathMove? _view;
  final String? _source;
  /// Existing variable name or form-record path to rename.
  late final String source = _view == null ? _source! : _view.source ?? '';
  final String? _destination;
  /// New variable name or form-record path.
  late final String destination = _view == null ? _destination! : _view.destination ?? '';

  /// Creates a PathMove value for an API input or application-owned copy.
  PathMove({String source = '', String destination = ''}) : _view = null, _source = source, _destination = destination;
  PathMove._from(this._view) : _source = null, _destination = null;
}

/// One named input in a reusable form definition, including its display label and sensitivity kind.
final class FormField {
  final fb.FormField? _view;
  final String? _id;
  /// Stable field identifier used when reading and writing records.
  late final String id = _view == null ? _id! : _view.id ?? '';
  final String? _label;
  /// Human-readable label presented to a person entering data.
  late final String label = _view == null ? _label! : _view.label ?? '';
  final String? _kind;
  /// Field kind that determines validation and secret handling.
  late final String kind = _view == null ? _kind! : _view.kind ?? '';
  final bool? _required;
  /// Whether a record must provide a value for this field.
  late final bool required = _view == null ? _required! : _view.$required;

  /// Creates a FormField value for an API input or application-owned copy.
  FormField({String id = '', String label = '', String kind = '', bool required = false}) : _view = null, _id = id, _label = label, _kind = kind, _required = required;
  FormField._from(this._view) : _id = null, _label = null, _kind = null, _required = null;
}

/// A versioned form schema used to validate and label structured records in a lockbox.
final class FormDefinition {
  final fb.FormDefinition? _view;
  final String? _typeId;
  /// Stable identifier shared by every revision of this form type.
  late final String typeId = _view == null ? _typeId! : _view.typeId ?? '';
  final String? _alias;
  /// Short name used to resolve the current form revision.
  late final String alias = _view == null ? _alias! : _view.alias ?? '';
  final int? _revision;
  /// Monotonically increasing revision number.
  late final int revision = _view == null ? _revision! : _view.revision;
  final String? _name;
  /// Human-readable name shown for this form.
  late final String name = _view == null ? _name! : _view.name ?? '';
  final String? _description;
  /// Explanation shown to people completing the form.
  late final String description = _view == null ? _description! : _view.description ?? '';
  final List<FormField>? _fields;
  /// Ordered inputs accepted by this form revision.
  late final List<FormField> fields = _view == null ? _fields! : List<FormField>.unmodifiable((_view.fields ?? const []).map(FormField._from));

  /// Creates a FormDefinition value for an API input or application-owned copy.
  FormDefinition({String typeId = '', String alias = '', int revision = 0, String name = '', String description = '', List<FormField> fields = const []}) : _view = null, _typeId = typeId, _alias = alias, _revision = revision, _name = name, _description = description, _fields = fields;
  FormDefinition._from(this._view) : _typeId = null, _alias = null, _revision = null, _name = null, _description = null, _fields = null;
}

/// The current value and sensitivity metadata for one field in a stored form record.
final class FormValue {
  final fb.FormValue? _view;
  final String? _fieldId;
  /// Identifier of the form field that owns this value.
  late final String fieldId = _view == null ? _fieldId! : _view.fieldId ?? '';
  final String? _label;
  /// Display label captured from the form revision.
  late final String label = _view == null ? _label! : _view.label ?? '';
  final String? _kind;
  /// Field kind captured from the form revision.
  late final String kind = _view == null ? _kind! : _view.kind ?? '';
  final String? _value;
  /// Plain value, or an empty string when the field is secret.
  late final String value = _view == null ? _value! : _view.value ?? '';
  final bool? _secret;
  /// Whether the value must be read through a scoped secret callback.
  late final bool secret = _view == null ? _secret! : _view.secret;

  /// Creates a FormValue value for an API input or application-owned copy.
  FormValue({String fieldId = '', String label = '', String kind = '', String value = '', bool secret = false}) : _view = null, _fieldId = fieldId, _label = label, _kind = kind, _value = value, _secret = secret;
  FormValue._from(this._view) : _fieldId = null, _label = null, _kind = null, _value = null, _secret = null;
}

/// A named structured record stored at a lockbox path and tied to a form-definition revision.
final class FormRecord {
  final fb.FormRecord? _view;
  final String? _path;
  /// Absolute lockbox path that identifies the record.
  late final String path = _view == null ? _path! : _view.path ?? '';
  final String? _name;
  /// Human-readable name assigned to this record.
  late final String name = _view == null ? _name! : _view.name ?? '';
  final String? _typeId;
  /// Stable identifier of the record's form type.
  late final String typeId = _view == null ? _typeId! : _view.typeId ?? '';
  final String? _definitionAlias;
  /// Alias of the form definition used by the record.
  late final String definitionAlias = _view == null ? _definitionAlias! : _view.definitionAlias ?? '';
  final int? _definitionRevision;
  /// Exact form revision against which the record was created.
  late final int definitionRevision = _view == null ? _definitionRevision! : _view.definitionRevision;
  final List<FormValue>? _values;
  /// Ordered non-secret field metadata and values.
  late final List<FormValue> values = _view == null ? _values! : List<FormValue>.unmodifiable((_view.values ?? const []).map(FormValue._from));

  /// Creates a FormRecord value for an API input or application-owned copy.
  FormRecord({String path = '', String name = '', String typeId = '', String definitionAlias = '', int definitionRevision = 0, List<FormValue> values = const []}) : _view = null, _path = path, _name = name, _typeId = typeId, _definitionAlias = definitionAlias, _definitionRevision = definitionRevision, _values = values;
  FormRecord._from(this._view) : _path = null, _name = null, _typeId = null, _definitionAlias = null, _definitionRevision = null, _values = null;
}

/// The files and metadata recovered, or found damaged, while inspecting or salvaging a lockbox.
final class RecoveryReport {
  final fb.RecoveryReport? _view;
  final List<LockboxEntry>? _intactFiles;
  /// Files whose complete contents remain recoverable.
  late final List<LockboxEntry> intactFiles = _view == null ? _intactFiles! : List<LockboxEntry>.unmodifiable((_view.intactFiles ?? const []).map(LockboxEntry._from));
  final int? _intactFileCount;
  /// Number of completely recoverable files.
  late final int intactFileCount = _view == null ? _intactFileCount! : _view.intactFileCount;
  final int? _partialFiles;
  /// Number of files for which only some content is recoverable.
  late final int partialFiles = _view == null ? _partialFiles! : _view.partialFiles;
  final int? _corruptRecords;
  /// Number of encrypted records that failed validation.
  late final int corruptRecords = _view == null ? _corruptRecords! : _view.corruptRecords;
  final bool? _tocRecovered;
  /// Whether a usable table of contents was recovered.
  late final bool tocRecovered = _view == null ? _tocRecovered! : _view.tocRecovered;
  final bool? _variablesRecovered;
  /// Whether variable metadata was recovered.
  late final bool variablesRecovered = _view == null ? _variablesRecovered! : _view.variablesRecovered;
  final int? _variableCount;
  /// Number of recovered variables.
  late final int variableCount = _view == null ? _variableCount! : _view.variableCount;
  final bool? _formsRecovered;
  /// Whether form definitions and records were recovered.
  late final bool formsRecovered = _view == null ? _formsRecovered! : _view.formsRecovered;
  final int? _formDefinitionCount;
  /// Number of recovered form definitions.
  late final int formDefinitionCount = _view == null ? _formDefinitionCount! : _view.formDefinitionCount;
  final int? _formRecordCount;
  /// Number of recovered form records.
  late final int formRecordCount = _view == null ? _formRecordCount! : _view.formRecordCount;

  /// Creates a RecoveryReport value for an API input or application-owned copy.
  RecoveryReport({List<LockboxEntry> intactFiles = const [], int intactFileCount = 0, int partialFiles = 0, int corruptRecords = 0, bool tocRecovered = false, bool variablesRecovered = false, int variableCount = 0, bool formsRecovered = false, int formDefinitionCount = 0, int formRecordCount = 0}) : _view = null, _intactFiles = intactFiles, _intactFileCount = intactFileCount, _partialFiles = partialFiles, _corruptRecords = corruptRecords, _tocRecovered = tocRecovered, _variablesRecovered = variablesRecovered, _variableCount = variableCount, _formsRecovered = formsRecovered, _formDefinitionCount = formDefinitionCount, _formRecordCount = formRecordCount;
  RecoveryReport._from(this._view) : _intactFiles = null, _intactFileCount = null, _partialFiles = null, _corruptRecords = null, _tocRecovered = null, _variablesRecovered = null, _variableCount = null, _formsRecovered = null, _formDefinitionCount = null, _formRecordCount = null;
}

/// One password or contact credential that can unlock a lockbox content key.
final class KeySlot {
  final fb.KeySlot? _view;
  final int? _id;
  /// Stable slot identifier used when removing this access method.
  late final int id = _view == null ? _id! : _view.id;
  final String? _protection;
  /// Access method, such as password or contact key.
  late final String protection = _view == null ? _protection! : _view.protection ?? '';
  final String? _algorithm;
  /// Cryptographic algorithm protecting the content key.
  late final String algorithm = _view == null ? _algorithm! : _view.algorithm ?? '';

  /// Creates a KeySlot value for an API input or application-owned copy.
  KeySlot({int id = 0, String protection = '', String algorithm = ''}) : _view = null, _id = id, _protection = protection, _algorithm = algorithm;
  KeySlot._from(this._view) : _id = null, _protection = null, _algorithm = null;
}

/// Current capacity, occupancy, hit, and miss counters for an open lockbox cache.
final class CacheStats {
  final fb.CacheStats? _view;
  final int? _limitBytes;
  /// Maximum decoded-page memory permitted for the cache.
  late final int limitBytes = _view == null ? _limitBytes! : _view.limitBytes;
  final int? _usedBytes;
  /// Decoded-page memory currently held by the cache.
  late final int usedBytes = _view == null ? _usedBytes! : _view.usedBytes;
  final int? _entries;
  /// Number of decoded pages currently cached.
  late final int entries = _view == null ? _entries! : _view.entries;
  final int? _hits;
  /// Reads served by an already decoded page.
  late final int hits = _view == null ? _hits! : _view.hits;
  final int? _misses;
  /// Reads that required decoding another page.
  late final int misses = _view == null ? _misses! : _view.misses;

  /// Creates a CacheStats value for an API input or application-owned copy.
  CacheStats({int limitBytes = 0, int usedBytes = 0, int entries = 0, int hits = 0, int misses = 0}) : _view = null, _limitBytes = limitBytes, _usedBytes = usedBytes, _entries = entries, _hits = hits, _misses = misses;
  CacheStats._from(this._view) : _limitBytes = null, _usedBytes = null, _entries = null, _hits = null, _misses = null;
}

/// Time spent reading host files and preparing encrypted pages during the latest import work.
final class ImportStats {
  final fb.ImportStats? _view;
  final String? _hostStatNanos;
  /// Nanoseconds spent reading host filesystem metadata, as decimal text.
  late final String hostStatNanos = _view == null ? _hostStatNanos! : _view.hostStatNanos ?? '';
  final String? _hostReadNanos;
  /// Nanoseconds spent reading host file content, as decimal text.
  late final String hostReadNanos = _view == null ? _hostReadNanos! : _view.hostReadNanos ?? '';
  final String? _framePrepareNanos;
  /// Nanoseconds spent preparing encrypted records, as decimal text.
  late final String framePrepareNanos = _view == null ? _framePrepareNanos! : _view.framePrepareNanos ?? '';
  final String? _pageWriteNanos;
  /// Nanoseconds spent writing encrypted pages, as decimal text.
  late final String pageWriteNanos = _view == null ? _pageWriteNanos! : _view.pageWriteNanos ?? '';

  /// Creates a ImportStats value for an API input or application-owned copy.
  ImportStats({String hostStatNanos = '', String hostReadNanos = '', String framePrepareNanos = '', String pageWriteNanos = ''}) : _view = null, _hostStatNanos = hostStatNanos, _hostReadNanos = hostReadNanos, _framePrepareNanos = framePrepareNanos, _pageWriteNanos = pageWriteNanos;
  ImportStats._from(this._view) : _hostStatNanos = null, _hostReadNanos = null, _framePrepareNanos = null, _pageWriteNanos = null;
}

/// One logical object recorded inside an inspected encrypted lockbox page.
final class PageObject {
  final fb.PageObject? _view;
  final int? _id;
  /// Object identifier recorded in the encrypted page.
  late final int id = _view == null ? _id! : _view.id;
  final String? _kind;
  /// Kind of logical object stored in the page.
  late final String kind = _view == null ? _kind! : _view.kind ?? '';
  final int? _payloadLen;
  /// Encrypted object payload length in bytes.
  late final int payloadLen = _view == null ? _payloadLen! : _view.payloadLen;

  /// Creates a PageObject value for an API input or application-owned copy.
  PageObject({int id = 0, String kind = '', int payloadLen = 0}) : _view = null, _id = id, _kind = kind, _payloadLen = payloadLen;
  PageObject._from(this._view) : _id = null, _kind = null, _payloadLen = null;
}

/// Layout and utilization details for one encrypted page in a lockbox archive.
final class PageInspection {
  final fb.PageInspection? _view;
  final int? _offset;
  /// Byte offset at which the page begins in the archive.
  late final int offset = _view == null ? _offset! : _view.offset;
  final int? _pageId;
  /// Identifier stored in the page header.
  late final int pageId = _view == null ? _pageId! : _view.pageId;
  final int? _sequence;
  /// Commit sequence that wrote this page.
  late final int sequence = _view == null ? _sequence! : _view.sequence;
  final int? _pageSize;
  /// Total encoded page size in bytes.
  late final int pageSize = _view == null ? _pageSize! : _view.pageSize;
  final int? _encryptedBodyLen;
  /// Encrypted body length in bytes.
  late final int encryptedBodyLen = _view == null ? _encryptedBodyLen! : _view.encryptedBodyLen;
  final int? _unusedBytes;
  /// Unused capacity remaining in the page.
  late final int unusedBytes = _view == null ? _unusedBytes! : _view.unusedBytes;
  final int? _objectCount;
  /// Number of logical objects stored in the page.
  late final int objectCount = _view == null ? _objectCount! : _view.objectCount;
  final List<PageObject>? _objects;
  /// Logical objects discovered in the page.
  late final List<PageObject> objects = _view == null ? _objects! : List<PageObject>.unmodifiable((_view.objects ?? const []).map(PageObject._from));

  /// Creates a PageInspection value for an API input or application-owned copy.
  PageInspection({int offset = 0, int pageId = 0, int sequence = 0, int pageSize = 0, int encryptedBodyLen = 0, int unusedBytes = 0, int objectCount = 0, List<PageObject> objects = const []}) : _view = null, _offset = offset, _pageId = pageId, _sequence = sequence, _pageSize = pageSize, _encryptedBodyLen = encryptedBodyLen, _unusedBytes = unusedBytes, _objectCount = objectCount, _objects = objects;
  PageInspection._from(this._view) : _offset = null, _pageId = null, _sequence = null, _pageSize = null, _encryptedBodyLen = null, _unusedBytes = null, _objectCount = null, _objects = null;
}

/// Header, owner-signature, and key-slot information read from a lockbox file without opening its contents.
final class FileInspection {
  final fb.FileInspection? _view;
  final Uint8List? _lockboxId;
  /// Stable binary identifier read from the lockbox header.
  late final Uint8List lockboxId = _view == null ? _lockboxId! : Uint8List.fromList(_view.lockboxId ?? const <int>[]);
  final bool? _headerReadable;
  /// Whether the archive header passed structural validation.
  late final bool headerReadable = _view == null ? _headerReadable! : _view.headerReadable;
  final int? _keyDirectoryGeneration;
  /// Latest readable access-key directory generation.
  late final int keyDirectoryGeneration = _view == null ? _keyDirectoryGeneration! : _view.keyDirectoryGeneration;
  final int? _keyDirectoryCopyCount;
  /// Number of readable redundant key-directory copies.
  late final int keyDirectoryCopyCount = _view == null ? _keyDirectoryCopyCount! : _view.keyDirectoryCopyCount;
  final bool? _ownerSigned;
  /// Whether commits require an owner signature.
  late final bool ownerSigned = _view == null ? _ownerSigned! : _view.ownerSigned;
  final List<KeySlot>? _keySlots;
  /// Password and contact access methods found in the header.
  late final List<KeySlot> keySlots = _view == null ? _keySlots! : List<KeySlot>.unmodifiable((_view.keySlots ?? const []).map(KeySlot._from));

  /// Creates a FileInspection value for an API input or application-owned copy.
  FileInspection({required Uint8List lockboxId, bool headerReadable = false, int keyDirectoryGeneration = 0, int keyDirectoryCopyCount = 0, bool ownerSigned = false, List<KeySlot> keySlots = const []}) : _view = null, _lockboxId = lockboxId, _headerReadable = headerReadable, _keyDirectoryGeneration = keyDirectoryGeneration, _keyDirectoryCopyCount = keyDirectoryCopyCount, _ownerSigned = ownerSigned, _keySlots = keySlots;
  FileInspection._from(this._view) : _lockboxId = null, _headerReadable = null, _keyDirectoryGeneration = null, _keyDirectoryCopyCount = null, _ownerSigned = null, _keySlots = null;
}

/// One active or retired generation of the contact keys belonging to a named vault profile.
final class ProfileGeneration {
  final fb.ProfileGeneration? _view;
  final int? _index;
  /// Generation number used to address this key version.
  late final int index = _view == null ? _index! : _view.index;
  final String? _status;
  /// Lifecycle state, such as active or retired.
  late final String status = _view == null ? _status! : _view.status ?? '';
  final Uint8List? _contactFingerprint;
  /// Fingerprint of this generation's contact public key.
  late final Uint8List contactFingerprint = _view == null ? _contactFingerprint! : Uint8List.fromList(_view.contactFingerprint ?? const <int>[]);
  final int? _createdAtUnixMs;
  /// Creation time in Unix milliseconds.
  late final int createdAtUnixMs = _view == null ? _createdAtUnixMs! : _view.createdAtUnixMs;
  final int? _retiredAtUnixMs;
  /// Retirement time in Unix milliseconds when retired.
  late final int retiredAtUnixMs = _view == null ? _retiredAtUnixMs! : _view.retiredAtUnixMs;
  final bool? _hasRetiredAt;
  /// Whether a retirement time is present.
  late final bool hasRetiredAt = _view == null ? _hasRetiredAt! : _view.hasRetiredAt;

  /// Creates a ProfileGeneration value for an API input or application-owned copy.
  ProfileGeneration({int index = 0, String status = '', required Uint8List contactFingerprint, int createdAtUnixMs = 0, int retiredAtUnixMs = 0, bool hasRetiredAt = false}) : _view = null, _index = index, _status = status, _contactFingerprint = contactFingerprint, _createdAtUnixMs = createdAtUnixMs, _retiredAtUnixMs = retiredAtUnixMs, _hasRetiredAt = hasRetiredAt;
  ProfileGeneration._from(this._view) : _index = null, _status = null, _contactFingerprint = null, _createdAtUnixMs = null, _retiredAtUnixMs = null, _hasRetiredAt = null;
}

/// The active generation and rotation history for a named vault profile.
final class ProfileHistory {
  final fb.ProfileHistory? _view;
  final String? _name;
  /// Vault profile name whose generations are listed.
  late final String name = _view == null ? _name! : _view.name ?? '';
  final int? _activeGeneration;
  /// Generation number currently used for new access grants.
  late final int activeGeneration = _view == null ? _activeGeneration! : _view.activeGeneration;
  final List<ProfileGeneration>? _generations;
  /// Active and retired contact-key generations.
  late final List<ProfileGeneration> generations = _view == null ? _generations! : List<ProfileGeneration>.unmodifiable((_view.generations ?? const []).map(ProfileGeneration._from));

  /// Creates a ProfileHistory value for an API input or application-owned copy.
  ProfileHistory({String name = '', int activeGeneration = 0, List<ProfileGeneration> generations = const []}) : _view = null, _name = name, _activeGeneration = activeGeneration, _generations = generations;
  ProfileHistory._from(this._view) : _name = null, _activeGeneration = null, _generations = null;
}

/// A lockbox identifier and host path remembered by the local vault for later discovery.
final class KnownLockbox {
  final fb.KnownLockbox? _view;
  final Uint8List? _lockboxId;
  /// Stable binary identifier of the remembered lockbox.
  late final Uint8List lockboxId = _view == null ? _lockboxId! : Uint8List.fromList(_view.lockboxId ?? const <int>[]);
  final String? _path;
  /// Last known host filesystem path of the lockbox.
  late final String path = _view == null ? _path! : _view.path ?? '';
  final int? _lastSeenUnixMs;
  /// Most recent observation time in Unix milliseconds.
  late final int lastSeenUnixMs = _view == null ? _lastSeenUnixMs! : _view.lastSeenUnixMs;

  /// Creates a KnownLockbox value for an API input or application-owned copy.
  KnownLockbox({required Uint8List lockboxId, String path = '', int lastSeenUnixMs = 0}) : _view = null, _lockboxId = lockboxId, _path = path, _lastSeenUnixMs = lastSeenUnixMs;
  KnownLockbox._from(this._view) : _lockboxId = null, _path = null, _lastSeenUnixMs = null;
}

/// A local human-readable label attached to one lockbox access slot.
final class AccessSlotLabel {
  final fb.AccessSlotLabel? _view;
  final Uint8List? _lockboxId;
  /// Lockbox whose access slot is labelled.
  late final Uint8List lockboxId = _view == null ? _lockboxId! : Uint8List.fromList(_view.lockboxId ?? const <int>[]);
  final int? _slotId;
  /// Stable identifier of the labelled access slot.
  late final int slotId = _view == null ? _slotId! : _view.slotId;
  final String? _name;
  /// Local human-readable label for the access slot.
  late final String name = _view == null ? _name! : _view.name ?? '';
  final int? _updatedAtUnixMs;
  /// Last label update time in Unix milliseconds.
  late final int updatedAtUnixMs = _view == null ? _updatedAtUnixMs! : _view.updatedAtUnixMs;

  /// Creates a AccessSlotLabel value for an API input or application-owned copy.
  AccessSlotLabel({required Uint8List lockboxId, int slotId = 0, String name = '', int updatedAtUnixMs = 0}) : _view = null, _lockboxId = lockboxId, _slotId = slotId, _name = name, _updatedAtUnixMs = updatedAtUnixMs;
  AccessSlotLabel._from(this._view) : _lockboxId = null, _slotId = null, _name = null, _updatedAtUnixMs = null;
}

/// A logical or physical byte range emitted while walking the contents of a lockbox.
final class StreamChunk {
  final fb.StreamChunk? _view;
  final String? _path;
  /// Lockbox file path to which this byte range belongs.
  late final String path = _view == null ? _path! : _view.path ?? '';
  final int? _fileOffset;
  /// Logical byte offset within the file.
  late final int fileOffset = _view == null ? _fileOffset! : _view.fileOffset;
  final int? _length;
  /// Logical range length in bytes.
  late final int length = _view == null ? _length! : _view.length;
  final int? _physicalOffset;
  /// Archive byte offset, when physical streaming is requested.
  late final int physicalOffset = _view == null ? _physicalOffset! : _view.physicalOffset;
  final bool? _sparse;
  /// Whether the range represents a sparse zero-filled extent.
  late final bool sparse = _view == null ? _sparse! : _view.sparse;
  final Uint8List? _data;
  /// File bytes for a populated logical range.
  late final Uint8List data = _view == null ? _data! : Uint8List.fromList(_view.data ?? const <int>[]);

  /// Creates a StreamChunk value for an API input or application-owned copy.
  StreamChunk({String path = '', int fileOffset = 0, int length = 0, int physicalOffset = 0, bool sparse = false, required Uint8List data}) : _view = null, _path = path, _fileOffset = fileOffset, _length = length, _physicalOffset = physicalOffset, _sparse = sparse, _data = data;
  StreamChunk._from(this._view) : _path = null, _fileOffset = null, _length = null, _physicalOffset = null, _sparse = null, _data = null;
}

/// The workload and worker policies currently applied to an open lockbox.
final class RuntimeOptions {
  final fb.RuntimeOptions? _view;
  final String? _workloadProfile;
  /// I/O workload policy used to tune page access.
  late final String workloadProfile = _view == null ? _workloadProfile! : _view.workloadProfile ?? '';
  final String? _workerPolicy;
  /// Worker scheduling policy and effective parallelism.
  late final String workerPolicy = _view == null ? _workerPolicy! : _view.workerPolicy ?? '';

  /// Creates a RuntimeOptions value for an API input or application-owned copy.
  RuntimeOptions({String workloadProfile = '', String workerPolicy = ''}) : _view = null, _workloadProfile = workloadProfile, _workerPolicy = workerPolicy;
  RuntimeOptions._from(this._view) : _workloadProfile = null, _workerPolicy = null;
}

/// The name and sensitivity classification of a variable stored in a lockbox.
final class Variable {
  final fb.Variable? _view;
  final String? _name;
  /// Name used to address the variable in the lockbox.
  late final String name = _view == null ? _name! : _view.name ?? '';
  final String? _sensitivity;
  /// Whether the value is ordinary text or a protected secret.
  late final String sensitivity = _view == null ? _sensitivity! : _view.sensitivity ?? '';

  /// Creates a Variable value for an API input or application-owned copy.
  Variable({String name = '', String sensitivity = ''}) : _view = null, _name = name, _sensitivity = sensitivity;
  Variable._from(this._view) : _name = null, _sensitivity = null;
}

/// Whether a lockbox is owner-signed and, when available, the signing-key fingerprint.
final class OwnerInspection {
  final fb.OwnerInspection? _view;
  final bool? _signed;
  /// Whether the lockbox requires owner-signed commits.
  late final bool signed = _view == null ? _signed! : _view.signed;
  final String? _fingerprint;
  /// Owner signing-key fingerprint when one is configured.
  late final String fingerprint = _view == null ? _fingerprint! : _view.fingerprint ?? '';
  final bool? _hasFingerprint;
  /// Whether an owner fingerprint is available.
  late final bool hasFingerprint = _view == null ? _hasFingerprint! : _view.hasFingerprint;

  /// Creates a OwnerInspection value for an API input or application-owned copy.
  OwnerInspection({bool signed = false, String fingerprint = '', bool hasFingerprint = false}) : _view = null, _signed = signed, _fingerprint = fingerprint, _hasFingerprint = hasFingerprint;
  OwnerInspection._from(this._view) : _signed = null, _fingerprint = null, _hasFingerprint = null;
}

/// A named recipient public key stored in the local vault address book.
final class Contact {
  final fb.Contact? _view;
  final String? _name;
  /// Local address-book name of the contact.
  late final String name = _view == null ? _name! : _view.name ?? '';
  final Uint8List? _key;
  /// Serialized contact public key used to grant lockbox access.
  late final Uint8List key = _view == null ? _key! : Uint8List.fromList(_view.key ?? const <int>[]);

  /// Creates a Contact value for an API input or application-owned copy.
  Contact({String name = '', required Uint8List key}) : _view = null, _name = name, _key = key;
  Contact._from(this._view) : _name = null, _key = null;
}

/// A lockbox key currently held by the local session agent, identified by lockbox and path.
final class AgentEntry {
  final fb.AgentEntry? _view;
  final String? _id;
  /// Stable lockbox identifier for the cached key.
  late final String id = _view == null ? _id! : _view.id ?? '';
  final String? _path;
  /// Host path associated with the cached lockbox key.
  late final String path = _view == null ? _path! : _view.path ?? '';

  /// Creates a AgentEntry value for an API input or application-owned copy.
  AgentEntry({String id = '', String path = ''}) : _view = null, _id = id, _path = path;
  AgentEntry._from(this._view) : _id = null, _path = null;
}

/// The host capabilities used to protect cached secrets across suspend and sleep.
final class SleepSupport {
  final fb.SleepSupport? _view;
  final bool? _suspendNotifications;
  /// Whether the host reports impending system suspend.
  late final bool suspendNotifications = _view == null ? _suspendNotifications! : _view.suspendNotifications;
  final bool? _sleepInhibition;
  /// Whether the agent can delay sleep while handling secrets.
  late final bool sleepInhibition = _view == null ? _sleepInhibition! : _view.sleepInhibition;
  final bool? _supported;
  /// Whether the host supplies enough integration for safe caching.
  late final bool supported = _view == null ? _supported! : _view.supported;

  /// Creates a SleepSupport value for an API input or application-owned copy.
  SleepSupport({bool suspendNotifications = false, bool sleepInhibition = false, bool supported = false}) : _view = null, _suspendNotifications = suspendNotifications, _sleepInhibition = sleepInhibition, _supported = supported;
  SleepSupport._from(this._view) : _suspendNotifications = null, _sleepInhibition = null, _supported = null;
}

/// Availability and configuration of the operating-system credential store used for the vault password.
final class PlatformStatus {
  final fb.PlatformStatus? _view;
  final bool? _supported;
  /// Whether a usable operating-system credential store exists.
  late final bool supported = _view == null ? _supported! : _view.supported;
  final bool? _disabled;
  /// Whether the user disabled credential-store integration.
  late final bool disabled = _view == null ? _disabled! : _view.disabled;
  final String? _scope;
  /// Application-specific scope used to isolate the stored password.
  late final String scope = _view == null ? _scope! : _view.scope ?? '';
  final String? _backend;
  /// Operating-system credential-store backend in use.
  late final String backend = _view == null ? _backend! : _view.backend ?? '';
  final String? _item;
  /// Credential item name used by the backend.
  late final String item = _view == null ? _item! : _view.item ?? '';

  /// Creates a PlatformStatus value for an API input or application-owned copy.
  PlatformStatus({bool supported = false, bool disabled = false, String scope = '', String backend = '', String item = ''}) : _view = null, _supported = supported, _disabled = disabled, _scope = scope, _backend = backend, _item = item;
  PlatformStatus._from(this._view) : _supported = null, _disabled = null, _scope = null, _backend = null, _item = null;
}

/// The version, size, checksum, and creation time of an exported local-vault backup.
final class VaultBackupManifest {
  final fb.VaultBackupManifest? _view;
  final int? _formatVersion;
  /// Backup container format version.
  late final int formatVersion = _view == null ? _formatVersion! : _view.formatVersion;
  final int? _createdAtUnixMs;
  /// Backup creation time in Unix milliseconds.
  late final int createdAtUnixMs = _view == null ? _createdAtUnixMs! : _view.createdAtUnixMs;
  final String? _vaultFileName;
  /// Metadata-vault filename stored in the backup.
  late final String vaultFileName = _view == null ? _vaultFileName! : _view.vaultFileName ?? '';
  final int? _vaultSize;
  /// Encrypted vault payload size in bytes.
  late final int vaultSize = _view == null ? _vaultSize! : _view.vaultSize;
  final String? _vaultSha256;
  /// Lowercase SHA-256 digest of the encrypted vault payload.
  late final String vaultSha256 = _view == null ? _vaultSha256! : _view.vaultSha256 ?? '';

  /// Creates a VaultBackupManifest value for an API input or application-owned copy.
  VaultBackupManifest({int formatVersion = 0, int createdAtUnixMs = 0, String vaultFileName = '', int vaultSize = 0, String vaultSha256 = ''}) : _view = null, _formatVersion = formatVersion, _createdAtUnixMs = createdAtUnixMs, _vaultFileName = vaultFileName, _vaultSize = vaultSize, _vaultSha256 = vaultSha256;
  VaultBackupManifest._from(this._view) : _formatVersion = null, _createdAtUnixMs = null, _vaultFileName = null, _vaultSize = null, _vaultSha256 = null;
}

/// Structured category, version, guidance, and artifact context for the most recent native failure.
final class ErrorDetails {
  final fb.ErrorDetails? _view;
  final String? _category;
  /// Stable error category suitable for programmatic handling.
  late final String category = _view == null ? _category! : _view.category ?? '';
  final String? _artifactKind;
  /// Kind of archive or vault artifact involved in the failure.
  late final String artifactKind = _view == null ? _artifactKind! : _view.artifactKind ?? '';
  final int? _foundVersion;
  /// Format version read from the failing artifact.
  late final int foundVersion = _view == null ? _foundVersion! : _view.foundVersion;
  final int? _supportedVersion;
  /// Newest format version supported by this library.
  late final int supportedVersion = _view == null ? _supportedVersion! : _view.supportedVersion;
  final String? _message;
  /// Human-readable explanation of the failure.
  late final String message = _view == null ? _message! : _view.message ?? '';
  final String? _guidance;
  /// Suggested corrective action for the caller or user.
  late final String guidance = _view == null ? _guidance! : _view.guidance ?? '';

  /// Creates a ErrorDetails value for an API input or application-owned copy.
  ErrorDetails({String category = '', String artifactKind = '', int foundVersion = 0, int supportedVersion = 0, String message = '', String guidance = ''}) : _view = null, _category = category, _artifactKind = artifactKind, _foundVersion = foundVersion, _supportedVersion = supportedVersion, _message = message, _guidance = guidance;
  ErrorDetails._from(this._view) : _category = null, _artifactKind = null, _foundVersion = null, _supportedVersion = null, _message = null, _guidance = null;
}

/// Private decoders used by the native operation layer.
abstract final class DomainDecoders {
  /// Decodes a native LockboxEntry result without copying its fields.
  static LockboxEntry lockboxEntry(Uint8List bytes) => LockboxEntry._from(fb.LockboxEntry(bytes));
  /// Decodes a native PathMove result without copying its fields.
  static PathMove pathMove(Uint8List bytes) => PathMove._from(fb.PathMove(bytes));
  /// Decodes a native FormField result without copying its fields.
  static FormField formField(Uint8List bytes) => FormField._from(fb.FormField(bytes));
  /// Decodes a native FormDefinition result without copying its fields.
  static FormDefinition formDefinition(Uint8List bytes) => FormDefinition._from(fb.FormDefinition(bytes));
  /// Decodes a native FormValue result without copying its fields.
  static FormValue formValue(Uint8List bytes) => FormValue._from(fb.FormValue(bytes));
  /// Decodes a native FormRecord result without copying its fields.
  static FormRecord formRecord(Uint8List bytes) => FormRecord._from(fb.FormRecord(bytes));
  /// Decodes a native RecoveryReport result without copying its fields.
  static RecoveryReport recoveryReport(Uint8List bytes) => RecoveryReport._from(fb.RecoveryReport(bytes));
  /// Decodes a native KeySlot result without copying its fields.
  static KeySlot keySlot(Uint8List bytes) => KeySlot._from(fb.KeySlot(bytes));
  /// Decodes a native CacheStats result without copying its fields.
  static CacheStats cacheStats(Uint8List bytes) => CacheStats._from(fb.CacheStats(bytes));
  /// Decodes a native ImportStats result without copying its fields.
  static ImportStats importStats(Uint8List bytes) => ImportStats._from(fb.ImportStats(bytes));
  /// Decodes a native PageObject result without copying its fields.
  static PageObject pageObject(Uint8List bytes) => PageObject._from(fb.PageObject(bytes));
  /// Decodes a native PageInspection result without copying its fields.
  static PageInspection pageInspection(Uint8List bytes) => PageInspection._from(fb.PageInspection(bytes));
  /// Decodes a native FileInspection result without copying its fields.
  static FileInspection fileInspection(Uint8List bytes) => FileInspection._from(fb.FileInspection(bytes));
  /// Decodes a native ProfileGeneration result without copying its fields.
  static ProfileGeneration profileGeneration(Uint8List bytes) => ProfileGeneration._from(fb.ProfileGeneration(bytes));
  /// Decodes a native ProfileHistory result without copying its fields.
  static ProfileHistory profileHistory(Uint8List bytes) => ProfileHistory._from(fb.ProfileHistory(bytes));
  /// Decodes a native KnownLockbox result without copying its fields.
  static KnownLockbox knownLockbox(Uint8List bytes) => KnownLockbox._from(fb.KnownLockbox(bytes));
  /// Decodes a native AccessSlotLabel result without copying its fields.
  static AccessSlotLabel accessSlotLabel(Uint8List bytes) => AccessSlotLabel._from(fb.AccessSlotLabel(bytes));
  /// Decodes a native StreamChunk result without copying its fields.
  static StreamChunk streamChunk(Uint8List bytes) => StreamChunk._from(fb.StreamChunk(bytes));
  /// Decodes a native RuntimeOptions result without copying its fields.
  static RuntimeOptions runtimeOptions(Uint8List bytes) => RuntimeOptions._from(fb.RuntimeOptions(bytes));
  /// Decodes a native Variable result without copying its fields.
  static Variable variable(Uint8List bytes) => Variable._from(fb.Variable(bytes));
  /// Decodes a native OwnerInspection result without copying its fields.
  static OwnerInspection ownerInspection(Uint8List bytes) => OwnerInspection._from(fb.OwnerInspection(bytes));
  /// Decodes a native Contact result without copying its fields.
  static Contact contact(Uint8List bytes) => Contact._from(fb.Contact(bytes));
  /// Decodes a native AgentEntry result without copying its fields.
  static AgentEntry agentEntry(Uint8List bytes) => AgentEntry._from(fb.AgentEntry(bytes));
  /// Decodes a native SleepSupport result without copying its fields.
  static SleepSupport sleepSupport(Uint8List bytes) => SleepSupport._from(fb.SleepSupport(bytes));
  /// Decodes a native PlatformStatus result without copying its fields.
  static PlatformStatus platformStatus(Uint8List bytes) => PlatformStatus._from(fb.PlatformStatus(bytes));
  /// Decodes a native VaultBackupManifest result without copying its fields.
  static VaultBackupManifest vaultBackupManifest(Uint8List bytes) => VaultBackupManifest._from(fb.VaultBackupManifest(bytes));
  /// Decodes a native ErrorDetails result without copying its fields.
  static ErrorDetails errorDetails(Uint8List bytes) => ErrorDetails._from(fb.ErrorDetails(bytes));
  /// Decodes a native list of StreamChunk values.
  static List<StreamChunk> streamChunkList(Uint8List bytes) => List<StreamChunk>.unmodifiable((fb.StreamChunkList(bytes).values ?? const []).map(StreamChunk._from));
  /// Decodes a native list of PageInspection values.
  static List<PageInspection> pageInspectionList(Uint8List bytes) => List<PageInspection>.unmodifiable((fb.PageInspectionList(bytes).values ?? const []).map(PageInspection._from));
  /// Decodes a native list of Variable values.
  static List<Variable> variableList(Uint8List bytes) => List<Variable>.unmodifiable((fb.VariableList(bytes).values ?? const []).map(Variable._from));
  /// Decodes a native list of KeySlot values.
  static List<KeySlot> keySlotList(Uint8List bytes) => List<KeySlot>.unmodifiable((fb.KeySlotList(bytes).values ?? const []).map(KeySlot._from));
  /// Decodes a native list of FormDefinition values.
  static List<FormDefinition> formDefinitionList(Uint8List bytes) => List<FormDefinition>.unmodifiable((fb.FormDefinitionList(bytes).values ?? const []).map(FormDefinition._from));
  /// Decodes a native list of FormRecord values.
  static List<FormRecord> formRecordList(Uint8List bytes) => List<FormRecord>.unmodifiable((fb.FormRecordList(bytes).values ?? const []).map(FormRecord._from));
  /// Decodes a native list of Contact values.
  static List<Contact> contactList(Uint8List bytes) => List<Contact>.unmodifiable((fb.ContactList(bytes).values ?? const []).map(Contact._from));
  /// Decodes a native list of KnownLockbox values.
  static List<KnownLockbox> knownLockboxList(Uint8List bytes) => List<KnownLockbox>.unmodifiable((fb.KnownLockboxList(bytes).values ?? const []).map(KnownLockbox._from));
  /// Decodes a native list of AccessSlotLabel values.
  static List<AccessSlotLabel> accessSlotLabelList(Uint8List bytes) => List<AccessSlotLabel>.unmodifiable((fb.AccessSlotLabelList(bytes).values ?? const []).map(AccessSlotLabel._from));
  /// Decodes a native list of AgentEntry values.
  static List<AgentEntry> agentEntryList(Uint8List bytes) => List<AgentEntry>.unmodifiable((fb.AgentEntryList(bytes).values ?? const []).map(AgentEntry._from));
  /// Decodes a native list of ProfileHistory values.
  static List<ProfileHistory> profileHistoryList(Uint8List bytes) => List<ProfileHistory>.unmodifiable((fb.ProfileHistoryList(bytes).values ?? const []).map(ProfileHistory._from));
  /// Decodes lockbox entry metadata.
  static List<LockboxEntry> lockboxEntryList(Uint8List bytes) => List<LockboxEntry>.unmodifiable((fb.LockboxEntryList(bytes).entries ?? const []).map(LockboxEntry._from));
  /// Decodes a list of UTF-8 strings.
  static List<String> stringList(Uint8List bytes) => List<String>.unmodifiable(fb.StringList(bytes).values ?? const []);
  /// Decodes optional lockbox entry metadata.
  static LockboxEntry? optionalLockboxEntry(Uint8List bytes) { final value = fb.OptionalLockboxEntry(bytes).value; return value == null ? null : LockboxEntry._from(value); }
  /// Decodes an optional form record.
  static FormRecord? optionalFormRecord(Uint8List bytes) { final value = fb.OptionalFormRecord(bytes).value; return value == null ? null : FormRecord._from(value); }
  /// Decodes an optional form value.
  static FormValue? optionalFormValue(Uint8List bytes) { final value = fb.OptionalFormValue(bytes).value; return value == null ? null : FormValue._from(value); }
  /// Decodes an optional UTF-8 string.
  static String? optionalString(Uint8List bytes) { final value = fb.OptionalString(bytes); return value.present ? value.value : null; }
  /// Encodes atomic path moves for the native ABI.
  static Uint8List pathMoves(List<PathMove> values) => fb.PathMoveListObjectBuilder(values: values.map((value) => fb.PathMoveObjectBuilder(source: value.source, destination: value.destination)).toList()).toBytes();
  /// Encodes form fields for the native ABI.
  static Uint8List formFields(List<FormField> values) => fb.FormFieldListObjectBuilder(values: values.map((value) => fb.FormFieldObjectBuilder(id: value.id, label: value.label, kind: value.kind, $required: value.required)).toList()).toBytes();
}
