package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	revault "github.com/onepub-dev/revault-api"
)

func pass(symbol string, assertions ...int) {
	count := 1
	if len(assertions) > 0 {
		count = assertions[0]
	}
	fmt.Printf("PASS\tgo\t%s\t%d\n", symbol, count)
}
func check(condition bool, message string) {
	if !condition {
		panic(message)
	}
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
func mustValue[T any](value T, err error) T { must(err); return value }
func artifactRoot() string {
	root := os.Getenv("REVAULT_E2E_ARTIFACT_DIR")
	if root == "" {
		root = "/tmp/revault-e2e-artifacts"
	}
	root = filepath.Join(root, "go")
	must(os.MkdirAll(root, 0700))
	return root
}

func archiveLifecycle() {
	key := bytes.Repeat([]byte{'K'}, 32)
	box := mustValue(revault.Create(key))
	defer box.Close()
	pass("lockbox_create")
	must(box.AddFile("/hello.txt", []byte("hello from go conformance"), false))
	check(box.Exists("/hello.txt"), "added file")
	pass("lockbox_add_file", 2)
	check(bytes.Equal(mustValue(box.GetFile("/hello.txt")), []byte("hello from go conformance")), "file content")
	pass("lockbox_get_file", 3)
	must(box.AddFileWithPermissions("/hello.txt", []byte("replacement payload"), 0640, true))
	check(box.Permissions("/hello.txt") == 0640, "permissions")
	pass("lockbox_add_file_with_permissions", 2)
	pass("lockbox_permissions")
	must(box.CreateDirectory("/tree", true))
	check(box.IsDirectory("/tree"), "directory")
	pass("lockbox_create_dir", 2)
	pass("lockbox_is_dir")
	must(box.CreateParentDirectories("/tree/a/b/file"))
	check(box.IsDirectory("/tree/a/b"), "parents")
	pass("lockbox_create_parent_dirs", 2)
	must(box.Rename("/hello.txt", "/renamed.txt"))
	check(box.Exists("/renamed.txt") && !box.Exists("/hello.txt"), "rename")
	pass("lockbox_rename", 3)
	pass("lockbox_exists", 2)
	must(box.SetPermissions("/renamed.txt", 0600))
	check(box.Permissions("/renamed.txt") == 0600, "set permissions")
	pass("lockbox_set_permissions", 2)
	check(bytes.Equal(mustValue(box.ReadRange("/renamed.txt", 0, 11)), []byte("replacement")), "range")
	pass("lockbox_read_range", 3)
	must(box.SetVariable("normal", "value"))
	check(*mustValue(box.GetVariable("normal")) == "value", "variable")
	pass("lockbox_set_variable")
	pass("lockbox_get_variable", 3)
	must(box.MoveVariables([]revault.PathMove{{Source: "normal", Destination: "moved"}}))
	check(*mustValue(box.GetVariable("moved")) == "value", "moved variable")
	must(box.MoveVariables([]revault.PathMove{{Source: "moved", Destination: "normal"}}))
	pass("lockbox_move_variables", 3)
	must(box.SetSecretVariable("secret", []byte("hidden")))
	pass("lockbox_set_secret_variable")
	must(box.WithSecretVariable("secret", func(value []byte) error {
		check(string(value) == "hidden", "secret variable")
		return nil
	}))
	pass("lockbox_get_secret_variable")
	pass("secret_len")
	pass("secret_copy")
	pass("secret_free")
	check(mustValue(box.VariableSensitivity("secret")) != nil, "sensitivity")
	pass("lockbox_variable_sensitivity", 2)
	check(len(mustValue(box.ListVariables())) == 2, "variables")
	pass("lockbox_list_variables")
	must(box.DeleteVariable("normal"))
	pass("lockbox_delete_variable")
	must(box.AddSymlink("/link", "/renamed.txt", false))
	check(mustValue(box.SymlinkTarget("/link")) == "/renamed.txt", "symlink")
	pass("lockbox_add_symlink")
	pass("lockbox_get_symlink_target", 3)
	check(len(mustValue(box.List("/", true))) > 0, "list")
	check(mustValue(box.Stat("/renamed.txt")) != nil, "stat")
	pass("lockbox_list", 2)
	pass("lockbox_stat", 2)
	must(box.SetWorkloadProfile("read-mostly"))
	must(box.SetWorkerPolicy("single", 1))
	check(mustValue(box.RuntimeOptions()).WorkloadProfile != "", "runtime options")
	pass("lockbox_set_workload_profile")
	pass("lockbox_set_worker_policy")
	pass("lockbox_runtime_options")
	must(box.Commit())
	check(box.StorageLength() > 0, "storage")
	pass("lockbox_commit")
	pass("lockbox_storage_len")
	archive := mustValue(box.Bytes())
	check(len(archive) > 0, "archive bytes")
	pass("lockbox_to_bytes", 2)
	pass("buffer_free")
	formatVersion := revault.LockboxFormatVersion()
	check(formatVersion > 0, "lockbox format version")
	check(revault.ProbeLockboxFormatVersion(archive) == formatVersion, "lockbox format probe")
	pass("lockbox_format_version", 2)
	pass("lockbox_probe_format_version", 2)
	check(revault.ProbeLockboxFormatVersion([]byte("bad")) == 0, "invalid format probe")
	details := mustValue(revault.LastErrorDetails())
	check(details.Message != "", "structured error details")
	pass("buffer_last_error_details", 2)
	path := filepath.Join(artifactRoot(), "archive.lbox")
	must(os.WriteFile(path, archive, 0600))
	fmt.Printf("ARTIFACT\tgo\tarchive-created\t%s\n", path)
	opened := mustValue(revault.Open(archive, key))
	defer opened.Close()
	check(bytes.Equal(mustValue(opened.GetFile("/renamed.txt")), []byte("replacement payload")), "open")
	pass("lockbox_open", 2)
	fmt.Printf("ARTIFACT\tgo\tarchive-opened\t%s\n", path)
	must(opened.Delete("/renamed.txt"))
	check(!opened.Exists("/renamed.txt"), "delete")
	pass("lockbox_delete", 2)
	must(opened.RemoveDirectory("/tree", true))
	check(!opened.Exists("/tree"), "remove dir")
	pass("lockbox_remove_dir", 2)
	pass("lockbox_free", 2)
}

func keyLifecycle() {
	content := make([]byte, 32)
	for index := range content {
		content[index] = byte(index)
	}
	contact := mustValue(revault.GenerateContactKeyPair())
	defer contact.Close()
	pass("key_contact_generate")
	private := mustValue(contact.PrivateRecord())
	check(len(private) > 32, "private record")
	pass("key_contact_private", 2)
	contactCopy := mustValue(revault.ContactKeyPairFromPrivate(private))
	defer contactCopy.Close()
	pass("key_contact_from_private")
	publicBytes := mustValue(contact.PublicBytes())
	check(len(publicBytes) > 0, "public record")
	pass("key_contact_public", 2)
	public := mustValue(revault.NewContactPublicKey(publicBytes))
	defer public.Close()
	pass("key_contact_public_from_bytes")
	wrapped := mustValue(public.Encrypt(content))
	defer wrapped.Close()
	pass("key_contact_encrypt")
	check(bytes.Equal(mustValue(contactCopy.Decrypt(wrapped)), content), "decrypt")
	pass("key_contact_decrypt", 3)
	check(len(mustValue(wrapped.PublicBytes())) > 0, "wrapped public")
	check(len(mustValue(wrapped.Ciphertext())) > 0, "wrapped cipher")
	check(len(mustValue(wrapped.EncryptedBytes())) > 0, "wrapped encrypted")
	pass("key_contact_wrapped_public", 2)
	pass("key_contact_wrapped_ciphertext", 2)
	pass("key_contact_wrapped_encrypted", 2)
	exportedPrivate := mustValue(contact.Export("raw-hex"))
	importedPrivate := mustValue(revault.ImportContactKeyPair(exportedPrivate))
	defer importedPrivate.Close()
	pass("vault_key_export_private", 2)
	pass("vault_key_import_private")
	exportedPublic := mustValue(public.Export("lockbox-pem"))
	importedPublic := mustValue(revault.ImportContactPublicKey(exportedPublic))
	defer importedPublic.Close()
	pass("vault_key_export_public", 2)
	pass("vault_key_import_public")
	fingerprint := mustValue(importedPublic.Fingerprint())
	check(len(fingerprint) >= 12, "fingerprint")
	pass("vault_key_fingerprint", 2)
	hex := mustValue(revault.FormatKeyHex(fingerprint))
	check(bytes.Equal(mustValue(revault.DecodeKeyHex(hex)), fingerprint), "hex")
	pass("vault_key_format_hex", 2)
	pass("vault_key_decode_hex", 2)
	code := mustValue(revault.FormatKeyCrockford(fingerprint[:12]))
	check(mustValue(revault.FormatKeyCrockfordReading(code)) != "", "reading")
	check(bytes.Equal(mustValue(revault.DecodeKeyCrockford(code)), fingerprint[:12]), "crockford")
	pass("vault_key_format_crockford", 2)
	pass("vault_key_format_crockford_reading", 2)
	pass("vault_key_decode_crockford", 2)
	plainHex := mustValue(revault.HexEncode(content))
	check(bytes.Equal(mustValue(revault.HexDecode(plainHex)), content), "plain hex")
	pass("vault_key_hex_encode", 2)
	pass("vault_key_hex_decode", 2)
	signing := mustValue(revault.GenerateSigningKeyPair())
	defer signing.Close()
	pass("key_signing_generate")
	signingPrivate := mustValue(signing.PrivateRecord())
	signingPublic := mustValue(signing.PublicBytes())
	check(len(signingPrivate) > 0 && len(signingPublic) > 0, "signing records")
	pass("key_signing_private", 2)
	pass("key_signing_public", 2)
	signingCopy := mustValue(revault.SigningKeyPairFromPrivate(signingPrivate))
	defer signingCopy.Close()
	pass("key_signing_from_private")
	signingPublicKey := mustValue(revault.NewSigningPublicKey(signingPublic))
	defer signingPublicKey.Close()
	pass("key_signing_public_from_bytes")
	pass("key_contact_wrapped_free")
	pass("key_contact_public_free", 2)
	pass("key_contact_free", 3)
	pass("key_signing_public_free", 2)
	pass("key_signing_free", 3)
}

func formFields() []revault.FormField {
	return []revault.FormField{
		{Id: "username", Label: "Username", Kind: "text", Required: true},
		{Id: "password", Label: "Password", Kind: "secret", Required: true},
	}
}

func advancedArchive() {
	key := bytes.Repeat([]byte{'A'}, 32)
	options := revault.DefaultLockboxOptions()
	options.CacheBytes = 4 << 20
	options.Workload = "bulk-import"
	options.Worker = "single"
	options.Jobs = 1
	box := mustValue(revault.CreateWithOptions(key, options))
	defer box.Close()
	pass("lockbox_create_with_options")
	must(box.AddFile("/account.txt", []byte("account data"), false))
	check(len(mustValue(box.ListWithOptions("/", "*.txt", true, true, false, false, 20))) == 1, "filtered list")
	pass("lockbox_list_with_options", 2)
	definition := mustValue(box.DefineForm("account", "Account", "Account form", formFields()))
	check(definition.TypeId != "", "form type")
	pass("lockbox_define_form", 2)
	check(len(mustValue(box.ListFormDefinitions())) == 1, "definitions")
	check(mustValue(box.ResolveForm("account")).TypeId == definition.TypeId, "resolve")
	check(len(mustValue(box.ListFormRevisions(definition.TypeId))) == 1, "revisions")
	pass("lockbox_list_form_definitions")
	pass("lockbox_resolve_form")
	pass("lockbox_list_form_revisions")
	record := mustValue(box.CreateFormRecord("/account.form", "account", "Primary"))
	check(record.Path == "/account.form", "record")
	pass("lockbox_create_form_record")
	must(box.SetFormField("/account.form", "username", "alice"))
	pass("lockbox_set_form_field")
	must(box.SetSecretFormField("/account.form", "password", []byte("hidden")))
	pass("lockbox_set_secret_form_field")
	must(box.WithSecretFormField("/account.form", "password", func(value []byte) error {
		check(string(value) == "hidden", "secret form field")
		return nil
	}))
	pass("lockbox_get_secret_form_field")
	check(len(mustValue(box.GetFormRecord("/account.form")).Values) == 2, "record values")
	check(mustValue(box.GetFormField("/account.form", "username")).Value == "alice", "field")
	check(len(mustValue(box.ListFormRecords())) == 1, "records")
	pass("lockbox_get_form_record")
	pass("lockbox_get_form_field")
	pass("lockbox_list_form_records")
	must(box.MoveFormRecords([]revault.PathMove{{Source: "/account.form", Destination: "/moved.form"}}))
	check(len(mustValue(box.GetFormRecord("/moved.form")).Values) == 2, "moved form record")
	must(box.MoveFormRecords([]revault.PathMove{{Source: "/moved.form", Destination: "/account.form"}}))
	pass("lockbox_move_form_records", 3)
	signing := mustValue(revault.GenerateSigningKeyPair())
	defer signing.Close()
	must(box.SetOwnerSigningKey(signing))
	pass("lockbox_set_owner_signing_key")
	passwordSlot := mustValue(box.AddPassword([]byte("archive password")))
	check(passwordSlot != ^uint64(0), "password slot")
	pass("lockbox_add_password")
	contact := mustValue(revault.GenerateContactKeyPair())
	defer contact.Close()
	public := mustValue(contact.PublicKey())
	defer public.Close()
	contactSlot := mustValue(box.AddContact(public, "recipient"))
	check(contactSlot != ^uint64(0), "contact slot")
	pass("lockbox_add_contact")
	check(len(mustValue(box.ListKeySlots())) >= 2, "slots")
	pass("lockbox_list_key_slots")
	must(box.DeleteKey(passwordSlot))
	pass("lockbox_delete_key")
	must(box.Commit())
	check(mustValue(box.OwnerInspection()).Signed, "owner")
	pass("lockbox_owner_inspection", 2)
	check(mustValue(box.CacheStats()).LimitBytes > 0, "cache")
	check(mustValue(box.ImportStats()).HostReadNanos != "", "import")
	must(box.ResetImportStats())
	check(len(mustValue(box.PageInspection())) > 0, "pages")
	check(mustValue(box.RecoveryReport()).IntactFileCount > 0, "recovery")
	check(mustValue(box.RenderRecoveryReport(true, 100)) != "", "render")
	check(len(mustValue(box.StreamContent(false))) > 0, "stream")
	check(len(mustValue(box.ID())) > 0, "id")
	pass("lockbox_cache_stats")
	pass("lockbox_import_stats")
	pass("lockbox_reset_import_stats")
	pass("lockbox_page_inspection")
	pass("lockbox_recovery_report")
	pass("lockbox_recovery_report_render", 2)
	pass("lockbox_stream_content")
	pass("lockbox_id", 2)
	archive := mustValue(box.Bytes())
	path := filepath.Join(artifactRoot(), "advanced.lbox")
	must(os.WriteFile(path, archive, 0600))
	check(mustValue(revault.InspectLockboxFile(path)).HeaderReadable, "inspect")
	check(mustValue(revault.ScanLockboxPath(path, key)).IntactFileCount > 0, "scan path")
	check(mustValue(revault.ScanLockbox(archive, key)).IntactFileCount > 0, "scan")
	pass("lockbox_inspect_file")
	pass("lockbox_recovery_scan_path")
	pass("lockbox_recovery_scan")
	damaged := append([]byte(nil), archive...)
	damaged = damaged[:len(damaged)-32]
	salvaged := mustValue(revault.SalvageLockbox(damaged, key, signing))
	check(salvaged.StorageLength() > 0, "salvage")
	salvaged.Close()
	pass("lockbox_recovery_salvage", 2)
	openedOptions := mustValue(revault.OpenWithOptions(archive, key, options))
	check(bytes.Equal(mustValue(openedOptions.GetFile("/account.txt")), []byte("account data")), "option open")
	openedOptions.Close()
	pass("lockbox_open_with_options", 2)
	passwordBox := mustValue(revault.CreateWithPassword([]byte("archive password")))
	must(passwordBox.AddFile("/password.txt", []byte("password protected"), false))
	must(passwordBox.Commit())
	passwordArchive := mustValue(passwordBox.Bytes())
	passwordBox.Close()
	pass("lockbox_create_password")
	passwordOpen := mustValue(revault.OpenWithPassword(passwordArchive, []byte("archive password")))
	check(bytes.Equal(mustValue(passwordOpen.GetFile("/password.txt")), []byte("password protected")), "password open")
	passwordOpen.Close()
	pass("lockbox_open_password", 2)
	contactBox := mustValue(revault.CreateForContact(public))
	must(contactBox.AddFile("/contact.txt", []byte("contact protected"), false))
	must(contactBox.Commit())
	contactArchive := mustValue(contactBox.Bytes())
	contactBox.Close()
	pass("lockbox_create_contact")
	contactOpen := mustValue(revault.OpenWithContact(contactArchive, contact))
	check(bytes.Equal(mustValue(contactOpen.GetFile("/contact.txt")), []byte("contact protected")), "contact open")
	contactOpen.Close()
	pass("lockbox_open_contact", 2)
	signedBox := mustValue(revault.CreateSigned(key, signing))
	must(signedBox.Commit())
	check(mustValue(signedBox.OwnerInspection()).Signed, "signed box")
	signedBox.Close()
	pass("lockbox_create_with_signing_key", 2)
	extractRoot := filepath.Join(artifactRoot(), "extract")
	os.RemoveAll(extractRoot)
	must(os.MkdirAll(extractRoot, 0700))
	must(box.ExtractFile("/account.txt", filepath.Join(extractRoot, "account.txt"), false))
	check(fileExists(filepath.Join(extractRoot, "account.txt")), "extract file")
	pass("lockbox_extract_file", 2)
	must(box.ExtractDirectory(filepath.Join(extractRoot, "tree"), 1<<20, 4<<20, 100, false, true, false))
	check(fileExists(filepath.Join(extractRoot, "tree")), "extract dir")
	pass("lockbox_extract_directory", 2)
	must(box.DeleteFormRecord("/account.form"))
	pass("lockbox_delete_form_record")
}

func fileExists(path string) bool { _, err := os.Stat(path); return err == nil }

func vaultLifecycle() {
	root := filepath.Join(artifactRoot(), "vault")
	must(os.MkdirAll(root, 0700))
	password := []byte("vault password")
	newPassword := []byte("new vault password")
	id := make([]byte, 16)
	for index := range id {
		id[index] = byte(0xa0 + index)
	}
	profile := mustValue(revault.GenerateContactKeyPair())
	defer profile.Close()
	contact := mustValue(revault.GenerateContactKeyPair())
	defer contact.Close()
	contactPublic := mustValue(contact.PublicKey())
	defer contactPublic.Close()
	owner := mustValue(revault.GenerateSigningKeyPair())
	defer owner.Close()
	ownerPublic := mustValue(owner.PublicKey())
	defer ownerPublic.Close()
	vault := mustValue(revault.ReplaceVaultDirectory(root, password))
	pass("vault_directory_replace")
	fmt.Printf("ARTIFACT\tgo\tvault-created\t%s\n", root)
	check(mustValue(vault.Root()) == root, "root")
	check(vault.StructureVersion() > 0, "version")
	pass("vault_directory_root", 3)
	pass("vault_directory_structure_version")
	currentVersion := revault.CurrentVaultStructureVersion()
	check(currentVersion == vault.StructureVersion(), "current vault structure version")
	check(revault.ProbeVaultStructureVersion(root, password) == currentVersion, "vault structure probe")
	pass("vault_structure_version_current", 2)
	pass("vault_directory_probe_structure_version", 2)
	must(vault.StorePrivateKey("alice", profile))
	check(vault.PrivateKeyExists("alice"), "profile exists")
	loadedProfile := mustValue(vault.LoadPrivateKey("alice"))
	loadedProfile.Close()
	firstGeneration := mustValue(vault.LoadPrivateKeyGeneration("alice", 1))
	firstGeneration.Close()
	pass("vault_directory_store_private_key")
	pass("vault_directory_private_key_exists")
	pass("vault_directory_load_private_key")
	pass("vault_directory_load_private_key_generation")
	must(vault.StoreProfileEmail("alice", "alice@example.test"))
	email := mustValue(vault.ProfileEmail("alice"))
	check(email != nil && *email == "alice@example.test", "email")
	pass("vault_directory_store_profile_email")
	pass("vault_directory_profile_email", 3)
	check(len(mustValue(vault.ListProfileGenerations("alice")).Generations) == 1, "history")
	check(len(mustValue(vault.RotatePrivateKey("alice")).Generations) == 2, "rotation")
	pass("vault_directory_list_profile_generations")
	pass("vault_directory_rotate_private_key")
	loadedOwner := mustValue(vault.LoadOwnerSigningKey("alice"))
	loadedOwner.Close()
	loadedOwnerGeneration := mustValue(vault.LoadOwnerSigningKeyGeneration("alice", 1))
	loadedOwnerGeneration.Close()
	pass("vault_directory_load_owner_signing_key")
	pass("vault_directory_load_owner_signing_key_generation")
	must(vault.StoreContact("bob", contactPublic))
	check(vault.ContactExists("bob"), "contact exists")
	loadedContact := mustValue(vault.LoadContact("bob"))
	loadedContact.Close()
	check(len(mustValue(vault.ListContacts())) == 1, "contacts")
	pass("vault_directory_store_contact")
	pass("vault_directory_contact_exists")
	pass("vault_directory_load_contact")
	pass("vault_directory_list_contacts")
	must(vault.StoreContactSigningKey("bob", ownerPublic))
	loadedContactSigning := mustValue(vault.LoadContactSigningKey("bob"))
	loadedContactSigning.Close()
	pass("vault_directory_store_contact_signing_key")
	pass("vault_directory_load_contact_signing_key")
	check(len(mustValue(vault.ListPrivateKeys())) > 0, "private keys")
	check(len(mustValue(vault.ListPrivateKeyNames())) > 0, "private names")
	check(len(mustValue(vault.ListContactNames())) > 0, "contact names")
	pass("vault_directory_list_private_keys")
	pass("vault_directory_list_private_key_names")
	pass("vault_directory_list_contact_names")
	must(vault.StoreBackup(id, []byte("encrypted backup bytes")))
	check(vault.BackupCount() == 1, "backup count")
	check(bytes.Equal(mustValue(vault.LoadBackup(id)), []byte("encrypted backup bytes")), "backup")
	pass("vault_directory_store_backup")
	pass("vault_directory_backup_count")
	pass("vault_directory_load_backup", 3)
	must(vault.RememberLockbox(id, "/tmp/example.lbox"))
	check(len(mustValue(vault.ListKnownLockboxes())) == 1, "known")
	pass("vault_directory_remember_lockbox")
	pass("vault_directory_list_known_lockboxes")
	must(vault.RememberAccessSlotLabel(id, 7, "primary"))
	check(len(mustValue(vault.ListAccessSlotLabels(id))) == 1, "labels")
	check(len(mustValue(vault.FindAccessSlotLabels(id, "primary"))) == 1, "label find")
	pass("vault_directory_remember_access_slot_label")
	pass("vault_directory_list_access_slot_labels")
	pass("vault_directory_find_access_slot_labels")
	must(vault.RememberPassword(id, password))
	check(bytes.Equal(mustValue(vault.RememberedPassword(id)), password), "remember password")
	pass("vault_directory_remember_password")
	pass("vault_directory_remembered_password", 3)
	vaultForm := mustValue(vault.DefineForm("login", "Login", "Login form", formFields()))
	check(vaultForm.TypeId != "", "define form")
	check(mustValue(vault.ResolveForm("login")).TypeId != "", "resolve form")
	check(len(mustValue(vault.ListForms())) > 0, "forms")
	pass("vault_directory_define_form")
	pass("vault_directory_resolve_form")
	pass("vault_directory_list_forms")
	check(len(mustValue(vault.ListFormRevisions(vaultForm.TypeId))) > 0, "vault form revisions")
	pass("vault_directory_list_form_revisions", 2)
	check(vault.SeedForms() > 0, "seed")
	pass("vault_directory_seed_forms")
	check(len(mustValue(vault.ListFormAliases())) > 0, "aliases")
	pass("vault_directory_list_form_aliases")
	must(vault.ForgetAccessSlotLabel(id, 7))
	must(vault.ForgetLockbox("/tmp/example.lbox"))
	must(vault.DeleteContact("bob"))
	pass("vault_directory_forget_access_slot_label")
	pass("vault_directory_forget_lockbox")
	pass("vault_directory_delete_contact")
	must(vault.DeletePrivateKey("alice"))
	check(!vault.PrivateKeyExists("alice"), "deleted")
	must(vault.RestorePrivateKey("alice", profile, owner, true))
	check(vault.PrivateKeyExists("alice"), "restored")
	pass("vault_directory_delete_private_key", 2)
	pass("vault_directory_restore_private_key", 2)
	vault.Close()
	pass("vault_directory_free")
	readonly := mustValue(revault.OpenReadOnlyVaultDirectory(root, password))
	check(len(mustValue(readonly.ListProfileNames())) > 0, "read-only profiles")
	mustValue(readonly.ListContactNames())
	check(len(mustValue(readonly.ListFormAliases())) > 0, "read-only forms")
	mustValue(readonly.ListKnownLockboxes())
	pass("vault_read_only_open")
	pass("vault_read_only_list_profile_names", 2)
	pass("vault_read_only_list_contact_names")
	pass("vault_read_only_list_form_aliases", 2)
	pass("vault_read_only_list_known_lockboxes")
	readonly.Close()
	pass("vault_read_only_free")
	must(revault.ChangeVaultDirectoryPassword(root, password, newPassword))
	pass("vault_directory_change_password")
	reopened := mustValue(revault.OpenVaultDirectory(root, newPassword))
	check(reopened.StructureVersion() > 0, "reopen")
	reopened.Close()
	pass("vault_directory_open")
	fmt.Printf("ARTIFACT\tgo\tvault-opened\t%s\n", root)
	opened := mustValue(revault.OpenOrCreateVaultDirectory(root, newPassword))
	check(opened.StructureVersion() > 0, "open create")
	opened.Close()
	pass("vault_directory_open_or_create")
}

func defaultVaultLifecycle() {
	root := filepath.Join(artifactRoot(), "default-vault")
	must(os.MkdirAll(root, 0700))
	must(os.Setenv("LOCKBOX_VAULT_DIR", root))
	vault := mustValue(revault.ReplaceDefaultVaultDirectory([]byte("default password")))
	vault.Close()
	pass("vault_directory_replace_default")
	readonly := mustValue(revault.OpenDefaultReadOnlyVaultDirectory([]byte("default password")))
	readonly.Close()
	pass("vault_read_only_open_default")
	check(mustValue(revault.DefaultVaultDirectory()) == root, "default dir")
	check(filepath.Dir(mustValue(revault.DefaultVaultPath())) == root, "default path")
	pass("vault_default_directory", 3)
	pass("vault_default_path", 2)
	opened := mustValue(revault.OpenOrCreateDefaultVaultDirectory([]byte("default password")))
	opened.Close()
	pass("vault_directory_open_or_create_default")
	must(revault.ChangeDefaultVaultDirectoryPassword([]byte("default password"), []byte("changed default password")))
	pass("vault_directory_change_default_password")
	backup := filepath.Join(artifactRoot(), "default-vault.backup")
	os.Remove(backup)
	check(mustValue(revault.BackupDefaultVault(backup, false)).VaultSize > 0, "backup default")
	check(mustValue(revault.RestoreDefaultVault(backup, true)).VaultSize > 0, "restore default")
	pass("vault_backup_default")
	pass("vault_restore_default")
}

func agentAndLocalVault() {
	agentDir := mustValue(os.MkdirTemp("", "revault-go-agent-"))
	agentVaultDir := mustValue(os.MkdirTemp("", "revault-go-agent-vault-"))
	must(os.Setenv("LOCKBOX_SESSION_AGENT_DIR", agentDir))
	must(os.Setenv("LOCKBOX_VAULT_DIR", agentVaultDir))
	must(os.Setenv("LOCKBOX_VAULT_PASSWORD", "agent vault password"))
	vault := mustValue(revault.ReplaceDefaultVaultDirectory([]byte("agent vault password")))
	profile := mustValue(revault.GenerateContactKeyPair())
	must(vault.StorePrivateKey("default", profile))
	profile.Close()
	vault.Close()
	must(revault.ForgetAllAgentSecrets())
	pass("vault_forget_all")
	child := exec.Command(os.Args[0], "--serve-agent")
	child.Stdout = os.Stderr
	child.Stderr = os.Stderr
	must(child.Start())
	running := false
	for attempt := 0; attempt < 200; attempt++ {
		if revault.AgentIsRunning() {
			running = true
			break
		}
		time.Sleep(50 * time.Millisecond)
	}
	check(running, "agent start")
	pass("vault_agent_serve")
	pass("vault_is_running")
	must(revault.StartAgent())
	pass("vault_agent_start")
	must(revault.VerifyAgentTransport())
	pass("vault_agent_verify_transport")
	id := make([]byte, 16)
	key := make([]byte, 32)
	for index := range id {
		id[index] = byte(0xc0 + index)
	}
	for index := range key {
		key[index] = byte(0x20 + index)
	}
	must(revault.PutAgentKey(id, key))
	check(bytes.Equal(mustValue(revault.GetAgentKey(id)), key), "agent key")
	check(len(mustValue(revault.ListAgentKeys())) > 0, "agent list")
	pass("vault_agent_put")
	pass("vault_agent_get", 3)
	pass("vault_agent_list")
	must(revault.PutAgentVaultUnlockKey("vault-id", key, 120))
	check(bytes.Equal(mustValue(revault.GetAgentVaultUnlockKey("vault-id")), key), "vault key")
	pass("vault_agent_put_vault_unlock_key")
	pass("vault_agent_get_vault_unlock_key", 3)
	owner := mustValue(revault.GenerateSigningKeyPair())
	defer owner.Close()
	must(revault.PutAgentOwnerSigningKey("vault-id", "alice", owner, 120))
	loadedOwner := mustValue(revault.GetAgentOwnerSigningKey("vault-id", "alice"))
	check(len(mustValue(loadedOwner.PublicBytes())) > 0, "owner key")
	loadedOwner.Close()
	pass("vault_agent_put_owner_signing_key")
	pass("vault_agent_get_owner_signing_key")
	activity := mustValue(revault.BeginAgentActivity("open"))
	pass("vault_agent_begin_activity")
	activity.Close()
	pass("vault_agent_end_activity")
	mustValue(revault.AgentSleepSupport())
	pass("vault_agent_sleep_support")
	check(mustValue(revault.AgentLogPath()) != "", "log path")
	check(mustValue(revault.AgentLogDestination()) != "", "log destination")
	pass("vault_agent_log_path", 2)
	pass("vault_agent_log_destination", 2)
	local := mustValue(revault.OpenLocalVault())
	pass("vault_local")
	localRoot := mustValue(os.MkdirTemp("", "revault-go-local-"))
	payload := []byte("local vault data")
	passwordPath := filepath.Join(localRoot, "password.lbox")
	passwordBox := mustValue(local.CreateWithPassword(passwordPath, []byte("local password")))
	must(passwordBox.AddFile("/data.txt", payload, false))
	must(passwordBox.Commit())
	passwordBox.Close()
	pass("vault_create_lockbox_password", 3)
	must(local.CachePassword(passwordPath, []byte("local password"), 120))
	pass("vault_cache_lockbox_password")
	passwordOpen := mustValue(local.OpenWithPassword(passwordPath, []byte("local password")))
	check(bytes.Equal(mustValue(passwordOpen.GetFile("/data.txt")), payload), "password open")
	passwordOpen.Close()
	pass("vault_open_lockbox_password", 3)
	must(local.CloseLockbox(passwordPath))
	pass("vault_close_lockbox")
	contentPath := filepath.Join(localRoot, "content.lbox")
	contentBox := mustValue(local.CreateWithContentKey(contentPath, key, owner))
	must(contentBox.AddFile("/data.txt", payload, false))
	must(contentBox.Commit())
	contentBox.Close()
	pass("vault_create_lockbox_content_key", 3)
	contentOpen := mustValue(local.OpenWithContentKey(contentPath, key, owner))
	check(bytes.Equal(mustValue(contentOpen.GetFile("/data.txt")), payload), "content open")
	contentOpen.Close()
	pass("vault_open_lockbox_content_key", 3)
	contact := mustValue(revault.GenerateContactKeyPair())
	defer contact.Close()
	public := mustValue(contact.PublicKey())
	defer public.Close()
	contactPath := filepath.Join(localRoot, "contact.lbox")
	contactBox := mustValue(local.CreateForContact(contactPath, public, "recipient", owner))
	must(contactBox.AddFile("/data.txt", payload, false))
	must(contactBox.Commit())
	contactBox.Close()
	pass("vault_create_lockbox_contact", 3)
	must(local.CloseAll())
	pass("vault_close_all")
	local.Close()
	pass("vault_free")
	must(revault.ForgetAgentOwnerSigningKey("vault-id", "alice"))
	must(revault.ForgetAgentVaultUnlockKey("vault-id"))
	must(revault.ForgetAgentKey(id))
	pass("vault_agent_forget_owner_signing_key")
	pass("vault_agent_forget_vault_unlock_key")
	pass("vault_agent_forget")
	must(revault.StopAgent())
	pass("vault_agent_stop")
	must(child.Wait())
}

func platformSecretStore() {
	root := mustValue(os.MkdirTemp("", "revault-go-platform-"))
	must(os.Setenv("LOCKBOX_VAULT_DIR", root))
	mustValue(revault.PlatformStatus())
	pass("vault_platform_status", 2)
	must(revault.SetPlatformScope("vault"))
	pass("vault_platform_set_scope")
	must(revault.DisablePlatformStore())
	check(revault.PlatformStoreDisabled(), "disabled")
	pass("vault_platform_disable")
	pass("vault_platform_disabled")
	must(revault.EnablePlatformStore())
	check(!revault.PlatformStoreDisabled(), "enabled")
	pass("vault_platform_enable")
	must(revault.PutPlatformPassword([]byte("platform vault password")))
	check(bytes.Equal(mustValue(revault.GetPlatformPassword()), []byte("platform vault password")), "platform password")
	pass("vault_platform_put_password")
	pass("vault_platform_get_password", 3)
	must(revault.ForgetPlatformPassword())
	pass("vault_platform_forget_password")
}

func interopOpen(producer string) {
	base := os.Getenv("REVAULT_E2E_ARTIFACT_DIR")
	if base == "" {
		base = "/tmp/revault-e2e-artifacts"
	}
	archive := mustValue(os.ReadFile(filepath.Join(base, producer, "archive.lbox")))
	box := mustValue(revault.Open(archive, bytes.Repeat([]byte{'K'}, 32)))
	check(bytes.Equal(mustValue(box.GetFile("/renamed.txt")), []byte("replacement payload")), "foreign archive")
	box.Close()
	vault := mustValue(revault.OpenVaultDirectory(filepath.Join(base, producer, "vault"), []byte("new vault password")))
	check(vault.StructureVersion() > 0, "foreign vault")
	vault.Close()
	fmt.Printf("INTEROP\tgo\t%s\tarchive\t3\n", producer)
	fmt.Printf("INTEROP\tgo\t%s\tvault\t2\n", producer)
}

func main() {
	if len(os.Args) == 2 && os.Args[1] == "--serve-agent" {
		must(revault.ServeAgent())
		return
	}
	if len(os.Args) == 2 && os.Args[1] == "--agent" {
		agentAndLocalVault()
		return
	}
	if len(os.Args) == 2 && os.Args[1] == "--platform" {
		platformSecretStore()
		return
	}
	if len(os.Args) == 3 && os.Args[1] == "--interop" {
		interopOpen(os.Args[2])
		return
	}
	archiveLifecycle()
	keyLifecycle()
	advancedArchive()
	vaultLifecycle()
	defaultVaultLifecycle()
	agentAndLocalVault()
	platformSecretStore()
	_ = revault.LastError()
	pass("buffer_last_error")
}
