// This file is @generated by prost-build.
/// Integers are Unix seconds. IDs and challenges are freshly random per request.
/// The server signs SIGNING_DOMAIN || canonical prost encoding of UnlockRequest.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnlockRequest {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub application_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub server_boot_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub challenge: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "6")]
    pub issued_at: u64,
    #[prost(uint64, tag = "7")]
    pub expires_at: u64,
    #[prost(string, tag = "8")]
    pub recipient_key_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "9")]
    pub recipient_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "10")]
    pub lockbox_id: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub requested_scope: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub origin: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SignedUnlockRequest {
    #[prost(message, optional, tag = "1")]
    pub request: ::core::option::Option<UnlockRequest>,
    #[prost(bytes = "vec", tag = "2")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// Context supplied exclusively by the extension background using MessageSender.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BrowserRequest {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub origin: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub extension_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub frame_id: u32,
    #[prost(oneof = "browser_request::Operation", tags = "5, 6, 7")]
    pub operation: ::core::option::Option<browser_request::Operation>,
}
/// Nested message and enum types in `BrowserRequest`.
pub mod browser_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Operation {
        #[prost(bool, tag = "5")]
        GetCapabilities(bool),
        #[prost(message, tag = "6")]
        RequestUnlock(super::SignedUnlockRequest),
        #[prost(string, tag = "7")]
        CancelRequest(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnlockEnvelope {
    #[prost(message, optional, tag = "1")]
    pub binding: ::core::option::Option<UnlockRequest>,
    #[prost(bytes = "vec", tag = "2")]
    pub encapsulated_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub ciphertext: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub tag: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BrowserResponse {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub envelope: ::core::option::Option<UnlockEnvelope>,
}
